### ISSUE TITLE
Tax rates is not falling into the invoice page during creating

### ISSUE THREAD

**Issue by mmarj** [wp-erp/wp-erp#1032]
**How to reproduce:**
- Firstly, please make sure you have the [Tax Rates](https://wperp.com/docs/accounting/tax/tax-rates/) configured first.
- Then create an invoice with the Tax Rate
- Select the Tax and you will notice it's not showing the predefined tax rate on the right side as well not adding the tax value with the **total amount**

Screencast: Pl[ease check this screencast video](https://drive.google.com/file/d/1tAXJnNLWn5XNW_YaGtNrXJE7jnecDnRv/view?usp=sharing) for further clarification.

**Comment by itowhid06** [comment]
I just tested it and it is working as expected. Though I think you have not selected tax category in the product that is why you are facing the issue.
