### ISSUE TITLE
Can not Edit/delete the created expenses on the ERP Accounting transaction

### ISSUE THREAD

**Issue by mmarj** [wp-erp/wp-erp#1033]
**How to reproduce**
- Create an Expense and save it.
- Then next try to Edit/delete the created one, you will notice there no action available to do so.

**Reference screenshot**: [http://prntscr.com/rlicu2](http://prntscr.com/rlicu2)

**Comment by itowhid06** [comment]
Expense is a direct transaction and you can not edit or delete it. In fact you can not delete any transactions form WP ERP Accounting.

**Comment by pikurasa** [comment]
Why do you not allow transactions to be deleted?
