### ISSUE TITLE
No action of Add new button of custom model

### ISSUE THREAD

**Issue by Gordiann** [wp-erp/wp-erp#1049]
Hello!

I need your help. I created own model (class, function) to add, edit and delete violations of my employees. I did it inside HRM module with the help of your code (I just found and copied/past all necessary code as it done, for example, for Education of employee). All works good, but my 'Add new item' button doesn't open a form. Browser throw me to the top of the page.

Could you help me, please?

**Comment by thebengalboy** [comment]
Hello @Gordiann 

It's really not possible to understand how you customized and what is happening in the customized situation.  As you are a developer, I'd recommend you to debug the problem and work on the exact point based on the error. I believe you can do that :)

Thanks
