### ISSUE TITLE
Allow notification in CRM Schedule not work

### ISSUE THREAD

**Issue by namdk89** [wp-erp/wp-erp#1050]
I recently installed wperp, currently I have the following problem:
Emails between agents and contacts works, notification when a new contact is asigned works. Only problem detected is the schedule notifications.

**Comment by namdk89** [comment]
For more infomation: I'm using gsuite.

**Comment by thebengalboy** [comment]
Can you please describe what is the problem with schedule notifications?

**Comment by namdk89** [comment]
I setup a schedule call and tick allow notification before 10 minutes. But email notification not being sent when the time has come.
[https://photos.app.goo.gl/KqtYjbFmuB9KUpwXA](url)

**Comment by thebengalboy** [comment]
No image found!

@namdk89 It's more likely you need support, not a plugin issue actually. So, I'd request you to [contact our support center](https://wperp.com/contact/) with your site details to get the problem resolved.

Thanks
