### ISSUE TITLE
Disable Invoice email notification

### ISSUE THREAD

**Issue by chanifalfath** [wp-erp/wp-erp#1053]
Hello there,

Can we disable Invoice email notification from Accounting?
So currently after we create sales transaction (invoice) it will sending an email notification to client.
Some client don't like this notification, and want this to be disable.
Any chance we get some feature to disable/enable this? and maybe custom the message?
And maybe for now - could you let me know where i can edit/disable this directly from the code?

![invoice-notification](https://user-images.githubusercontent.com/1436709/80474532-c35a3480-8971-11ea-9e65-1a4fc2d109a9.jpeg)

Many Thanks
Chanif

**Comment by thebengalboy** [comment]
Hello @chanifalfath 

Thanks for arising the fact. We believe disabling from the codes is not a good use case for all the users and hence, we are planning to have a template for this email with the enable/disable option. Also, it'll let you write your own email.

Thanks

**Comment by thebengalboy** [comment]
Hello @chanifalfath 

We have brought that feature. Now, you can enable/disable the email templates for accounting. Available under the WPERP->Settings->Emails.

Thanks
