### ISSUE TITLE
Problem in Editing Inventory Items

### ISSUE THREAD

**Issue by mhmdadel** [wp-erp/wp-erp#1054]
When trying to edit an inventory item, the "Product Type" field by default is ( inventory ) and cannot be changed.
The problem if an inventory item "Product Type" is service the field of the Product Type back to the default which is  ( inventory ) and cannot be edited.

**Comment by thebengalboy** [comment]
Hello @mhmdadel 

Yes, product type is not changeable once you set. It's not a bug, it's intentional.

You need to be sure whether it's a product or service, before adding it.

Thanks
