### ISSUE TITLE
Multisite Errors. 

### ISSUE THREAD

**Issue by jjlast** [wp-erp/wp-erp#1064]
First was getting this one: 

Fatal error: Uncaught Exception: Table 'XXXXXXX.wp_4_usermeta' doesn't exist in /home/XXXXX/webapps/XXXXXdevelopment/wp-content/plugins/erp/vendor/tareq1988/wp-eloquent/src/Eloquent/Database.php:150`

it was effecting the employees section. i couldn't add any employees from the admin. i was able to fix this by adding "base_" to the prefix here: 

https://github.com/wp-erp/wp-erp/blob/4d692315a76069c58e29d7a30dda060afbe98d00/modules/hrm/includes/functions-employee.php#L71

https://github.com/wp-erp/wp-erp/blob/4d692315a76069c58e29d7a30dda060afbe98d00/modules/hrm/includes/functions-employee.php#L74

I also updated, the UserMeta.php in the /erp/vendor/tareq1988/wp-eloquent/src/WP. I at least got the employees section working from that. 

Now i am getting the same kind of error but for the the users table on the CRM main dashboard. Specifically in "my schedules". Also cant add any kind of activity to a contact. 

edit: typos.

**Comment by thebengalboy** [comment]
Hello @jjlast 

Are you using multisite in the network mode? I mean, does WPERP activated in the network?

Thanks

**Comment by jjlast** [comment]
@thebengalboy cheers! 

no, it's not network activated and i've already tried using a default theme with no other plugins activated, but it's still giving me missing table errors. specifically with the users table now. this is not on the main site though. it's on with what be number 4 in the network. 

i am still playing with it, but i feel like i am just missing an instance or two where that user table is breaking things. couldn't that be updated to "{$wpdb->base_prefix}users" as well?

thanks for the quick reply. much appreciated.

**Comment by jjlast** [comment]
i think i have at least narrowed things down to....these errors are only happening on a subsite. if the wp-erp plugin is installed on the main site, it appears to be be fine. when it's on a subsite though, it's not able to find the users or usermeta tables. which again, are shared globally. so it's looking for something like "wp3_users" when the users table is still "wp_users". 

which would explain why it works fine when it's installed on the main site.

**Comment by thebengalboy** [comment]
Hello @jjlast 

Officially WPERP is not designed for multisite networks. So, that can be a problem, I understand.

Please consider using it on the main site or the singe sites only.

As this is not a core issue, and we are not going to make it compatible with the multisite nearby, I'm closing this issue here.

Thanks
