### ISSUE TITLE
Please support "dd.mm.yyyy" as "Date Format"

### ISSUE THREAD

**Issue by koppor** [wp-erp/wp-erp#1069]
Currently, the erp-settings allow for 5 date formats. The German one (dd.mm.yyyy) is not listed. Would it be possible to add this?

![grafik](https://user-images.githubusercontent.com/1366654/87255617-9efbf780-c48c-11ea-80dd-11a0ba3662d8.png)

**Comment by nurul-umbhiya** [comment]
We will add this feature in next release which is 1.6.5

**Comment by nurul-umbhiya** [comment]
added in version 1.6.5

**Comment by stvogel** [comment]
Great that this is fixed in the settings. But the format did not appear in the "Setup-Wizard".
Not essential, but would be nice to be able to directly set the date-format correctly.
