### ISSUE TITLE
Tax payment doesn't support decimal values

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#1076]
**How to reproduce  the issue**
Please navigate to **WP-Admin->WP ERP->Accounting->Tax->Tax Payment->Record/create Sales Tax Payment**
Try to enter a value with a decimal number like: 16.20

**What should be**
It should support decimal values. 2 decimal is proposed

**Reference:**
<img width="1280" alt="Screenshot 2020-07-29 at 10 33 47 AM" src="https://user-images.githubusercontent.com/5962216/88757319-89264c00-d187-11ea-9b59-abc3a30eabab.png">

**Comment by emran-wedevs** [comment]
Issue solved.
