### ISSUE TITLE
CRM Contact Owner gets reset with contact form integration

### ISSUE THREAD

**Issue by dev-masta** [wp-erp/wp-erp#1077]
We're using erp-gravity-forms plugin.

For each form we can select an Owner in the Settings, and whoever submits such a form will get his new CRM Contact Owner set to the Owner that was selected in the Settings.

This is definitely not the desired behavior.

We also use the Deals plugin and have multiple pipelines so our Sales Team (Coaches) can track the progress of the Customer.
We use Gravity Forms to collect some answers from the Customer on the front end and the goal is to display those answers on the Deal page.
That has all been achieved with some custom coding.

But every time someone submits a gravity form, his CRM Contact Owner gets changed because of the Setting.

I've tried selecting the first option in the dropdown (Select Owner) so the value of that field is 0 and not the Owner ID, because no Owner is selected.
Even though that field is marked as Required, it allows me to save the settings for that form.

But that only got me to a point where the Contact now has a contact_owner in the wp_peoples tables set to NULL.

---

Can I suggest that you add a new filter hook in the file
erp\modules\crm\includes\contact-forms\class-contact-forms-integration.php
in the method save_submitted_form_data( $data, $plugin, $form_id )
right before erp_insert_people() function is called?

That would allow me to get the current CRM Contact Owner and send it with the rest of the contact's data array.

Right now I've manually edited the plugin's file, which is only a quick fix and definitely not a permanent solution.

Thank you!

**Comment by nurul-umbhiya** [comment]
For now, we are adding a hook as you've specified. We'll look into this issue shortly.

**Comment by nurul-umbhiya** [comment]
here you go:
`
/**
   * @since 1.6.5
*/
$contact = apply_filters( 'erp_pre_contact_form_people_data', $contact, $data, $plugin, $form_id );`
