### ISSUE TITLE
How to do payment refund?

### ISSUE THREAD

**Issue by amikodesign** [wp-erp/wp-erp#1085]
Is there a way to do the payment refund if the received payment was a deposit?

Also for the send email function in invoice, can we hav a standard template like To, invoice url with clickable, and Regards?

For the email template for accounting, how to include invoice url? i didnt saw the url tag provided.

**Comment by thebengalboy** [comment]
Hello @amikodesign 

Sales or Purchase return feature is not available at this moment but yes, we have a plan for this already and hoping to start working soon on it.

The available tags for the Email Templates are available below the template. Like this: https://prnt.sc/u6xpx9

As this is more likely a support topic, not a plugin issue- I'm closing it here. If you get more queries alike, please feel free to contact our support center.

Thanks
