### ISSUE TITLE
Company and contact filterings are not loading data correctly

### ISSUE THREAD

**Issue by MarcCeleiro** [wp-erp/wp-erp#1086]
The company and contact filters in the CRM load the names correctly, but when you click on them, the list is empty. This error appears with any role (CRM administrator or CRM editor). In some cases, we have also found the name of some contacts in the list of the company filter.

The ideal would be to be able to see, in the filter list, all the companies and contacts (regardless of the owner), and when clicking on the name, see this contact/company in the list.

[https://player.vimeo.com/video/452280987](https://player.vimeo.com/video/452280987)

**Comment by thebengalboy** [comment]
Hello @MarcCeleiro 

We have investigated the issue, and found, this 'Filter by Company' field is not required on the Company list page. Let me describe why.

It's necessary for the 'Contacts' page, to filter the contacts based on the company. I mean, let's say filter by company X, and you can see the contacts that are assigned to the company X.

So, this was basically for the contacts. Somehow, it was placed in the Company list page as well, which was not intentional. 

Except that, you have the Company search option already to search the company on the list.

Thanks

**Comment by MarcCeleiro** [comment]
I reopen this issue, because even with the latest version 1.7.4, we still have the same problem. In our CRM, whether you have the role of administrator or agent, when you search for a contact that does exist, the list appears empty. Neither your companies nor those of others appear. Ideally, both the administrator and the agent should be able to see all the companies when searching, but the agents should not be able to modify the details of the companies that are not theirs.

**Screenshot 1**: I have successfully created a company called "Test"

![screenshot1](https://user-images.githubusercontent.com/11487343/103467744-60b40680-4d52-11eb-86dd-0adc05bf5f78.png)


**Screenshot 2**: I use the search engine and enter the word "Test".

![screenshot2](https://user-images.githubusercontent.com/11487343/103467773-bab4cc00-4d52-11eb-9ad6-ba14f5d12ff7.png)


**Screenshot 3**: The list of results appears empty.

![screenshot3](https://user-images.githubusercontent.com/11487343/103467772-b8eb0880-4d52-11eb-9c76-67dbdfcc1555.png)

Thanks.

**Comment by MarcCeleiro** [comment]
Any updates, @thebengalboy? Thanks ;)

**Comment by thebengalboy** [comment]
Hello @MarcCeleiro 

Sorry, I somehow overlooked or did not notice you bumped this issue. My apologies for that.

Anyway, the search was working before exactly how you want it now- which we had to change based on multiple requests from the users. Yes, they had a valid point to argue here. Let me describe.

When searching with **Marc** as an agent, if the **Marc** is not available for that agent, he/she gets an empty result. But, if we show him the whole list that he/she doesn't own, that would be a privacy concern.

Suppose, agent searched with **Marc** but we showed him **Marius** or even **Marc** that other agents own. In that case, this agent can know someone else owns a contact/company with that name or this company has a lead with that name--which is a real privacy concern.

I hope you understand.

**Comment by MarcCeleiro** [comment]
@thebengalboy No problem, don't worry :)

Yes, correct, you are absolutely right. In the last message I wrote I was wrong: Agents should only see their own companies. The problem is that the screenshots are made using a user with the "CRM Manager" role, which should have access to all companies (or this is how I understand it should be), and that this would be a bug. I'm right?

Thank you very much in advance!

**Comment by thebengalboy** [comment]
Yes, you are right. Managers should be able to see all. Even they have the right to update any contact. If that happens for the managers as well, then we need to make it correct.

Of course, we'll take care of this soon. Thank you so much @MarcCeleiro for noticing and letting us know the problem. We really appreciate your effort :)

**Comment by MarcCeleiro** [comment]
Hi, @thebengalboy:

I know it is not the best place to write this, but it is really impressive how poorly your organization manage issues. This incident has been created since August 27. Both I and other users through the forum have reported the malfunction of the search engine and the permissions in the CRM, and the only thing you have done is responded to everyone how the permissions work: We have already understood this, we are simply saying that there is a problem that is not being resolved. In a CRM, this bug is very serious.

You made a pull request for this issue, but analyzing the code, I have not seen any changes on this particular issue (sorry if not). I have tried to fix it manually, changing the code of the program, but it is very poorly organized and not documented. Another big problem, to be honest.

We had planned to buy the Pro version, but we are not going to do it, seeing the support and the speed in solving this type of problems.

**Comment by thebengalboy** [comment]
The issue has been fixed already @MarcCeleiro but it was not possible to reference the commit along with this issue as this one is closed.

Wait for the next release, please.

_[And in case of any new problem, kindly open a new issue so that we can tag proper references]_

Thanks
