### ISSUE TITLE
Customer Transcations View related Expenses

### ISSUE THREAD

**Issue by amikodesign** [wp-erp/wp-erp#1091]
![image](https://user-images.githubusercontent.com/30711235/92086671-126f1500-edfd-11ea-8bda-020d6dd8e4c4.png)

Voucher #3 and #8 are expenses that return back to the customer. So the actual receive amount is 1643.14 and not 6,643.14.

The amount for voucher #1 should be 3,253.14 but it show 3100 ( discount 31 and tax 184.14).

The amount for voucher #2 should be 3,253.14 as Receive Payment but it show 3,243.14.

**Comment by amikodesign** [comment]
![image](https://user-images.githubusercontent.com/30711235/92194755-08512300-ee9e-11ea-8319-1d3c039645a5.png)

The opening balance should be 2 decimal places.

**Comment by emran-wedevs** [comment]
The issue has been solved. will be available in the next release.
