### ISSUE TITLE
Edit product changes product type from service to inventory

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#1094]
**Description**
If you edit a product from the product list with the product type service, it sets the product to inventory after editing/updating. You could not to back to the product type service again.

**How it should work**
It should be service if I do not change it. It should not changes to any other type automatically.

**Reference screencast**
https://d.pr/v/O5ln6x

**Comment by emran-wedevs** [comment]
We have solved the issue. You will find in the next release
