### ISSUE TITLE
CRM date pickers are displayed in the wrong format

### ISSUE THREAD

**Issue by MarcCeleiro** [wp-erp/wp-erp#1099]
Some date pickers do not adapt to the format selected on the WP ERP Settings page. In our WordPress site, the format is dd-mm-yyyy, but the selector is displayed in yyyy-mm-dd format.

The following screenshot shows the Schedule tab, located on a company's tab in the CRM:

![image](https://user-images.githubusercontent.com/11487343/93324753-9ae6b000-f816-11ea-9e8f-d79adf73e8e8.png)

And this is the WP ERP Settings page:

![image](https://user-images.githubusercontent.com/11487343/93325127-1d6f6f80-f817-11ea-956f-a9dde6e5c97b.png)

**Edit: An employee's "Hire Date" and "Employee End Date" option in the Human Resources section also displays the date in the wrong format. I guess all the selectors in the program should be checked.**

**Comment by thebengalboy** [comment]
General date format is not for the selecting date pickers. It's to show/display the date formats.

We'll recheck all the places where the dates need to show and make sure it follows the general date format. But date picker might not be the same dynamically as the general date format. We are not considering it as an issue at this moment.

Thanks

**Comment by MarcCeleiro** [comment]
It does not make any sense. If in settings I select a date format, it should be changed throughout the program, right? Seems very absurd 😅

**Comment by thebengalboy** [comment]
We have implemented the date picker(display part) to be synched with the Global setting. Will be released with the next version.

Thanks
