### ISSUE TITLE
HR employee list shows an extra leftover item

### ISSUE THREAD

**Issue by MarcCeleiro** [wp-erp/wp-erp#1100]
In our WP ERP installation an extra empty user always appears in the list of employees in the Human Resources section. Pressing shows the entire card empty, with no data. If I edit it, the data entered is deleted and everything is empty again. All users with HR permissions see the error.

![image](https://user-images.githubusercontent.com/11487343/93325888-4b08e880-f818-11ea-81a0-5441f298c620.png)

**Comment by thebengalboy** [comment]
That's not a plugin issue @MarcCeleiro, somehow a leftover user data is on your database.

This can happen(rare though) when you delete an employee from the employee list but do not delete it from the user list.(Available as a user with the Employee role).

However, you can take help from our support center in case you can not clean it from the database.

Thanks
