### ISSUE TITLE
Shows FATAL error after disabling modules.

### ISSUE THREAD

**Issue by Rink9** [wp-erp/wp-erp#1110]
**Bug Name:** Shows FATAL error after disabling modules.
**Area Path:** WP ERP> Modules >uncheck one of the modules > Tools > Status >System Status
**Build Number:** Version 1.6.6
**Priority:** High
**Environment:** Windows 10

**Description:**
The site shows fatal error while unchecking one of the modules and then clicking tools, checking system status, hence unable to check module managers.

**Steps To Reproduce:**
1) Login into the site
2) Navigate to the WP ERP >modules> unchecking module
3) Clicked on Tools
4) Clicked on the Status
5) Seen a fatal error on System status.

**Expected Result**: On clicking the status menu, should be prompted to a success page with the Number of modules manager.
![Screenshot_1](https://user-images.githubusercontent.com/44554636/95713132-d8a8ee00-0c87-11eb-934b-8f9e5161a411.png)
”

**Comment by thebengalboy** [comment]
Thank you @Rink9 

I just want to add with you. Same happens when you have the HR module disabled. Error in 'Number of HR Manager'. Ref: https://prnt.sc/uxj73k

Thanks
