### ISSUE TITLE
How to manage payroll and salary slip.

### ISSUE THREAD

**Issue by YuvrajKhavad** [wp-erp/wp-erp#1125]
Hello Team, Thank you very much for the best plugin.
Is there any possibility add payroll, generate salary slip in pdf and sent salary slip by mail.

Thanks

**Comment by thebengalboy** [comment]
Hello @YuvrajKhavad 

Yes, we have an extension for this, called WP ERP Payroll. Due to some upgrade, we have taken it down for a while and hoping to make it available again very soon. It'll be available under this URL: https://wperp.com/downloads/payroll

Thanks

**Comment by YuvrajKhavad** [comment]
Ok, Thank You.
