### ISSUE TITLE
Search for an employee with Arabic letters that does not work

### ISSUE THREAD

**Issue by Hashaft** [wp-erp/wp-erp#1128]
When you add an employee in Arabic letters, everything works well, but when you search for an employee in Arabic letters, he refreshes the page and shows all results, noting when trying with English letters, it works well.

**Comment by thebengalboy** [comment]
Hello @Hashaft 

Replied to you on WordPress.org, can you please provide a screencast? It seems okay to us here.

Thanks

**Comment by Hashaft** [comment]
@tanmayjay Thanks

**Comment by Hashaft** [comment]
@thebengalboy thanks
