### ISSUE TITLE
Currency rendering problem in the PDF invoice for BDT

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#1129]
**Description**
BDT currency is not showing properly on the exported PDF invoice in accounting.

**How to reproduce**
- Please set your currency as BDT from the settings first.
- Create an sales invoice in accounting
- Export is as PDF
- Check the amounts

**Refeence**
Ref. Screenshot: https://prnt.sc/vbxnsq

**Comment by tanmayjay** [comment]
This issue is actually in the pdf invoice plugin. It has been fixed there and will be available after the next release of that plugin. So, I'm closing this issue here. Thank you.
