### ISSUE TITLE
Count in Chart of Accounts Display nothing

### ISSUE THREAD

**Issue by amikodesign** [wp-erp/wp-erp#1130]
![image](https://user-images.githubusercontent.com/30711235/98086475-c4889300-1eb9-11eb-8536-aed7a7fd0b84.png)

**Comment by thebengalboy** [comment]
Hello @amikodesign 

Sorry for being late. Yes, you are right, the count is not showing any value. We are looking at it and hoping to solve it soon.

Thanks

**Comment by emran-wedevs** [comment]
The issue has been fixed. You will find it with the next release.
