### ISSUE TITLE
"erp_crm_inbound_email_scheduled_events" cron not scheduled.

### ISSUE THREAD

**Issue by khaiknievel** [wp-erp/wp-erp#1167]
Unable to schedule event `erp_crm_inbound_email_scheduled_events`.

https://github.com/wp-erp/wp-erp/blob/590ecdc9645ba41103f1d04314d46e45fc91082a/modules/crm/includes/admin/class-settings.php#L894-L910

**Comment by tanmayjay** [comment]
It seems okay in our end. The problem might happen depending on your system. Apart from that, please provide more information and contact our support team.
I am now closing this issue and can be reopened if needed.
