### ISSUE TITLE
Product price is calculated incorrectly.

### ISSUE THREAD

**Issue by lpn672** [wp-erp/wp-erp#1171]
Bug Name: Product price is calculated incorrectly.
Area Path: WP ERP>Accounting>Transactions>New transaction>Create invoice
Build Number: Version 1.7.0
Priority: Medium
Environment: Windows 10

Description:
Product price is calculated incorrectly.
Steps To Reproduce:
1.Login into the site
2.Navigate to the WP ERP>Accounting>Transactions>New transaction>Create invoice

What we have: the product is sand. We sell by weight. We create an invoice, write the amount 256.25, cost 7, result 1792, but it should be 1793.75

![image](https://user-images.githubusercontent.com/32219094/101054441-928a4f80-3591-11eb-8d83-7da37880e420.png)

**Comment by thebengalboy** [comment]
Hello @lpn672 

Thanks for noticing and letting us know.

While it comes to the calculation, it's the top priority to us. We'll analyze this and provide you an update.

Thanks

**Comment by thebengalboy** [comment]
Hello @lpn672 

After several tests(_which was okay so far_), we finally figured out that you somehow used the price in the Quantity field! A quantity can not have friction as you have on the screenshot.

QTY== Quantity
Unit Price== Price per item
Amount== QTY*Unit Price

I hope this helps.

Thanks

**Comment by lpn672** [comment]
Formula: QUANTITY * PRICE PER UNIT = AMOUNT.

QUANTITY - can it ONLY be an integer? It is not right. How then to sell / buy one and a half kilograms (1.5) of sugar / nuts?

See the screen.
1.2 * 2 = 4
2.2 * 2.5 = 5
3.2.5 * 2 = 4 (?)

And what about payment for services - gas, water, electricity? There are no integers in the calculations. Or buying / selling fuel (gasoline)? Both quantity and unit price are not integers!

![image](https://user-images.githubusercontent.com/32219094/101259000-e8482e80-372e-11eb-9d09-2f194aeff3cf.png)

**Comment by thebengalboy** [comment]
Hello @lpn672 

No, it doesn't support friction on the quantity, it needs to be an integer. Unfortunately, it has been designed for the 'Quantity' items only, not the 'Weighted' items.

Rather, you can arrange the products with the variations of weight. Like:

Sand01--- 2KG
Sand02-- 2.2KG
Sand03-- 2.7KG

By doing this, you can avoid weight in the invoice, where the price declared weight-based already.

Thanks

[Note: As this is not an issue(not have that feature), I'm closing the issue here. Rather, you can create a feature request to have the wight based pricing in the invoice]

**Comment by lpn672** [comment]
You have made a very strange decision! Do you propose to create many different categories? This is a joke? There is a product, for example, bottled and it can be put into several different categories, but ... But there is a product that is sold by weight or volume (space occupied). I am in the printing business. We sell square centimeters in a newspaper or magazine. How to sell a print space 25.6 cm2 X 0.8 euro = ???

**Comment by lpn672** [comment]
> [Note: As this is not an issue(not have that feature), I'm closing the issue here. Rather, you can
> create a feature request to have the wight based pricing in the invoice]

Did not understand you. What do you suggest?

**Comment by thebengalboy** [comment]
@lpn672 

WP ERP doesn't serve the purpose/use case you have at this moment. Our system is designed for the fixed weight product, not the variable weight product.

I'm afraid that if having the product with a fixed weight is not possible for you- then WP ERP might not be the good fit for you at this moment, until we offer the weight-based products in the accounting system.

Thanks
