### ISSUE TITLE
Seach by employee id

### ISSUE THREAD

**Issue by Hashaft** [wp-erp/wp-erp#1177]
Is there a possibility to have the search do the search with the employee id as well?
@tanmayjay  @thebengalboy 

Thanks

**Comment by thebengalboy** [comment]
Hello @Hashaft 

Employee ID is not a Mandatory field. So, all Employees may not have ID's. However, keeping this as a note for future reference, we are closing it here. We may consider it in the future if we get enough requests for it.

Thanks
