### ISSUE TITLE
Abstract out the email tracking code

### ISSUE THREAD

**Issue by pcfreak30** [wp-erp/wp-erp#1180]
I am seeing a need to use the email tracking ability in many places, but the main generation logic is in the CRM ajax class. I would like to see this abstracted out to either a class or a function for modularity.

Thanks :)

**Comment by tanmayjay** [comment]
@pcfreak30 Thanks for reaching out. Can you please elaborate exactly what you need? We will consider the details as a feature request and will implement it if needed.

**Comment by pcfreak30** [comment]
I am seeing this as design issues in many places but for email code, I am having to copy your logic for use in custom development since the logic isn't in any sort of individual abstracted/modular components that I could create an instance of or call.

In this specific case, custom development with the email pixel tracking is requiring code duplication.

Overall, I would suggest to abstract out all major logic in admin ajax to reusable classes so both ajax, rest and anywhere else can make use of that logic with a single API interface for it.

Thanks.

**Comment by tanmayjay** [comment]
Hello, @pcfreak30 

We will consider your need and will implement it in near future after some certain researches.
For now, I am closing this as it is not any major issue.

Thanks.
