### ISSUE TITLE
First and Last Names don't handle apostrophes correctly in CRM

### ISSUE THREAD

**Issue by pcfreak30** [wp-erp/wp-erp#1181]
When the first or last name has a `'`, it gets escaped, and then if you try to send an email, it gets double escaped.

Thanks.

**Comment by thebengalboy** [comment]
Hello @pcfreak30 

Thanks for noticing and letting us know. Yes, this is a valid issue and we'll take care of this.

Thanks

**Comment by OpuRockey** [comment]
This issue has been resolved at https://github.com/wp-erp/wp-erp/pull/1200
