### ISSUE TITLE
Reset filter result once click the page number

### ISSUE THREAD

**Issue by amikodesign** [wp-erp/wp-erp#1193]
![image](https://user-images.githubusercontent.com/30711235/103437172-1867ec00-4c5f-11eb-8a41-d00b98b2c038.png)

![image](https://user-images.githubusercontent.com/30711235/103437180-31709d00-4c5f-11eb-9d25-26c6fbbae992.png)

After filter, the page number still showing as 2 instead of 1. If click go to page 2, it will show all the results without the filter values.

**Comment by thebengalboy** [comment]
Thanks for noticing and letting us know @amikodesign. We'll fix it shortly.
