### ISSUE TITLE
CRM Contact/Company search: Match the search term exactly

### ISSUE THREAD

**Issue by MarcCeleiro** [wp-erp/wp-erp#1194]
I suggest adding an option to modify the behavior of the CRM search engines: Now, if someone searches "Word" it will display contacts or companies matching "WordPress" or "Word", but there should be an option to match the search term exactly and display items only matching "Word".

I've tried it with the [WP Extended Search](https://wordpress.org/plugins/wp-extended-search/) plugin, but it doesn't seem to be compatible with WP ERP.

Could you look at it to add it in future versions? It seems like a simple option, and it would improve the CRM a lot. Thanks a lot!

**Comment by thebengalboy** [comment]
Sure, this can be added in future versions. Thanks for the suggestion @MarcCeleiro
