### ISSUE TITLE
CRM agents cannot edit their own companies

### ISSUE THREAD

**Issue by MarcCeleiro** [wp-erp/wp-erp#1195]
CRM agents cannot edit companies that they themselves created in the past (and which are assigned to them).

**You don't have any permission to edit this contact**

I have managed to fix it by removing the following line of code. It should be reviewed because it seems that it also restricts editing to the owners themselves.

[modules/crm/includes/class-ajax.php (line 303):](https://github.com/wp-erp/wp-erp/blob/develop/modules/crm/includes/class-ajax.php#L303)
```
if ( $data['id'] && ! current_user_can( 'erp_crm_edit_contact', $data['id'] ) && $current_user_id !== $data['contact_owner'] ) {
   $this->send_error( __( 'You don\'t have any permission to edit this contact', 'erp' ) );
//}
```

**Comment by thebengalboy** [comment]
Hello @MarcCeleiro 

Thanks for noticing and letting us know the issue. Yes, it's a bug and we'll solve it shortly.

Thanks

**Comment by Rink9** [comment]
@thebengalboy   Reproduced and valid.
https://prnt.sc/xl1n0j

**Comment by thebengalboy** [comment]
Hello @MarcCeleiro 

This issue has been resolved and scheduled to release with the upcoming version.

Thanks
