### ISSUE TITLE
My schedule calendar doesn't show any data

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#1196]
**Description:**
In the CRM->Schedule->My schedules don't show any data even when you have a meeting to call assigned to you.

**How to reproduce**

- Open a contact profile
- Create a schedule(Meeting) assigning to yourself
- Now, visit **Schedules->My schedules**. See, no data here but if you visit 'All schedules' it's listed there.

**How it should be**
It should be on **my-schedule** as well when it's assigned to me.

**Comment by tanmayjay** [comment]
Fixed in #1229
