### ISSUE TITLE
Admin losing their permission

### ISSUE THREAD

**Issue by Rink9** [wp-erp/wp-erp#1197]
**Priority:** High
**Scenario:** Admin losing their permission

**Given:** Admin

**When:** 1.Fresh installation with a mail
                 2.Creating an employee with that mail

**Then:** Admin loses his permission and cant be able to retrieve
**Resource:** https://prnt.sc/x3sffw
**Environment**: wperp free 1.7.4
**Expected Result:** Admin should not lose their access.

**Comment by OpuRockey** [comment]
It will be fixed in the 1.7.5 version.
