### ISSUE TITLE
Issue regarding downloading of Attached file in CRM contacts

### ISSUE THREAD

**Issue by Arif-me** [wp-erp/wp-erp#1207]
ERP does have a feature to attach files in CRM Contacts, It works properly (i,e CRM manager, Agents can attach file).
 
The problem is, there is no further option to download those files.

**ERP Core version 1.7.4**

Reference: 
![image](https://user-images.githubusercontent.com/46082780/105622355-2f06fa80-5e3b-11eb-812b-991d0dd85808.png)

**Comment by ManiruzzamanAkash** [comment]
Needs to upload the attachaments to somewhere, this system is note integrated here.
Ways:
1) Upload in posts table as attachment 
or
2) Create new table for attachments and upload these there and linked on upload.

**Comment by tanmayjay** [comment]
Fixed in #1238
