### ISSUE TITLE
Add shamsi Calendar 

### ISSUE THREAD

**Issue by MrAlfak** [wp-erp/wp-erp#1210]
Hi dear wedev please add shamsi calender

**Comment by thebengalboy** [comment]
Hello @zahedalfak 

I guess the Parsian and the Shamsi Calendar are the same, right?

Where you actually need it? In HR or CRM? Can you please describe a bit more?

Thanks

**Comment by zahedalfak** [comment]
Hi @thebengalboy
Yes same. Need on all section use date.
