### ISSUE TITLE
Chart of accounts > Sales and sales return modification

### ISSUE THREAD

**Issue by Rink9** [wp-erp/wp-erp#1212]
**Bug Name:** Sales and sales return modification
**Build Number:** Version 1.7.4
**Priority:** High
**Environment:** macOS
**Description:**
Sales and sales returns should be modified.
**Steps To Reproduce:**
1.Login into the site
2.Navigate to the WP ERP>accounting>chart of accountants>search for sales> 

**Expected Result:** Sales and sales return should be modified.

**Comment by tanmayjay** [comment]
Updated in #1215
