### ISSUE TITLE
TAX , SALES , PURCHASE EDIT issue

### ISSUE THREAD

**Issue by Rink9** [wp-erp/wp-erp#1214]
Bug Name: TAX , SALES , PURCHASE EDIT issue
Build Number: Version 1.7.4
Priority: High
Environment: macOS
Description:
Cant be able to update/edit TAX, SALES, PURCHASE transactions.
Steps To Reproduce:
1.Login into the site
2.Edit TAX ZONE/TAZ Catagory/Tax Agencies
3.Edit purchase transaction
4.Edit sales transaction
Expected Result: Will be able to edit TAX, SALES, PURCHASE transactions.

**Comment by tanmayjay** [comment]
Fixed in #1211
