### ISSUE TITLE
Invalid Access token (Getting Fatal error)

### ISSUE THREAD

**Issue by Arif-me** [wp-erp/wp-erp#1216]
When reactivating the plugin, this is throwing a fatal error "Invalid Access Token"

Here is the reference: https://prnt.sc/106672k
WP ERP Core version: 1.7.5

Here is the error details :
____________________________________________________________________________________________

Fatal error: Uncaught InvalidArgumentException: Invalid token format in /var/www/html/wp-content/plugins/erp/vendor/google/apiclient/src/Google/Client.php:482 

	Stack trace: #0 /var/www/html/wp-content/plugins/erp/modules/crm/includes/class-google-auth.php(65): Google_Client->setAccessToken(Array) 
	
	#1 /var/www/html/wp-content/plugins/erp/modules/crm/includes/class-google-auth.php(17): WeDevs\ERP\CRM\Google_Auth->init_client() 

	#2 /var/www/html/wp-content/plugins/erp/modules/crm/includes/class-google-auth.php(32): WeDevs\ERP\CRM\Google_Auth->__construct() 

	#3 /var/www/html/wp-content/plugins/erp/wp-erp.php(287): WeDevs\ERP\CRM\Google_Auth::init() 

	#4 /var/www/html/wp-content/plugins/erp/wp-erp.php(122): WeDevs_ERP->instantiate() 

	#5 /var/www/html/wp-content/plugins/erp/wp-erp.php(92): WeDevs_ERP->setup() 

	#6 /var/www/html/wp-content/plugins/erp/wp-erp.php(407): WeDevs_ERP::init() 

	#7 /var/www/html/wp-content/plugins/erp/wp-erp.php(411): wperp() 

	#8 /var/www/html/wp-admin/includes/plugin.php(2299): include('/var/www/html/w...') 

	#9 /v in /var/www/html/wp-content/plugins/erp/vendor/google/apiclient/src/Google/Client.php on line 482

______________________________________________________________________________________________________________________________________
Possible Solution:

**Comment by tanmayjay** [comment]
Fixed in #1225
