### ISSUE TITLE
WP ERP Fail to load

### ISSUE THREAD

**Issue by arievanwyk** [wp-erp/wp-erp#1223]
Wordpress Version 5.7
WP ERP Version 1.7.5
PHP Version 7.4

An Open Source ERP Solution for WordPress. Built-in HR, CRM and Accounting system for WordPress

Version 1.7.5 | By weDevs | View details
 This plugin failed to load properly and is paused during recovery mode.

An error of type E_ERROR was caused in line 8 of the file /home/truetbhz/public_html/wp-content/plugins/erp/includes/framework/Model.php. Error message: Class WeDevs\ERP\Framework\Model contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Queue\QueueableEntity::getQueueableRelations, Illuminate\Contracts\Queue\QueueableEntity::getQueueableConnection, Illuminate\Contracts\Routing\UrlRoutable::resolveRouteBinding)

**Comment by tanmayjay** [comment]
Hello @arievanwyk, have you updated the plugin to the latest 1.8.1 version? Please let me know if the issue still exists.

**Comment by arievanwyk** [comment]
> Hello @arievanwyk, have you updated the plugin to the latest 1.8.1 version? Please let me know if the issue still exists.

Hi 
After uppdate and activation I get the following.

An Open Source ERP Solution for WordPress. Built-in HR, CRM and Accounting system for WordPress

Version 1.8.1 | By weDevs | View details
 This plugin failed to load properly and is paused during recovery mode.

An error of type E_ERROR was caused in line 8 of the file /home/truetbhz/public_html/wp-content/plugins/erp/includes/framework/Model.php. Error message: Class WeDevs\ERP\Framework\Model contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Queue\QueueableEntity::getQueueableRelations, Illuminate\Contracts\Queue\QueueableEntity::getQueueableConnection, Illuminate\Contracts\Routing\UrlRoutable::resolveRouteBinding)

**Comment by tanmayjay** [comment]
Hello, @arievanwyk. Thanks for your reply.
Well, as the issue does not exist in our end, there might be some inconsistency with the site environment. Please contact our technical support team at `support@wperp.com`. They will check and handle the issue accordingly.
