### ISSUE TITLE
Cant be able to delete leave policy with leave type only

### ISSUE THREAD

**Issue by Rink9** [wp-erp/wp-erp#1258]
Bug Name: Cant be able to delete leave policy with leave type only
Area Path: Leave > Policies 
Build Number: Version 1.1.2
Priority: High
Environment: macOS

STEPS TO REPRODUCE:
1 . Click leave
2.Add a new leave type
3. Add policy
4. Delete policy
<img width="1268" alt="leave" src="https://user-images.githubusercontent.com/44554636/121468545-c6c94780-c9dc-11eb-86f9-49729b3f7279.png">

Actual Result: Cant be able to delete the policy
Expected Result: Should be able to delete policy while you there's no entitlement

**Comment by tanmayjay** [comment]
Updated in #1275
