### ISSUE TITLE
Issue with updating job information

### ISSUE THREAD

**Issue by Rink9** [wp-erp/wp-erp#1260]
**Bug Name:** While updating job information it doesn't show selected department, designation, and reporting to items.
**Build Number:** Version 1.8.5
**Priority:** Medium
**Environment:** macOS

**STEPS TO REPRODUCE:**
1 . Click on my profile
2. Click on job section
3. Update job information
Actual Result: Shows deselected items
Expected Result: Will show selected department, designation, and reporting to items.
![image](https://user-images.githubusercontent.com/44554636/123206157-07e15180-d4dd-11eb-93c0-0b685d101cb5.png)

**Comment by tanmayjay** [comment]
Fixed in #1263
