### ISSUE TITLE
Some of the tables are not responsive

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#1266]
**Description**
I found some of the tables(Contact and Request table mostly) in ERP are not mobile-friendly/responsive.

**How it should be**
All of the tables should be mobile responsive

**Screenshots:**
![Screenshot_2021-07-09-16-16-58-491_com android chrome](https://user-images.githubusercontent.com/5962216/125226642-45264b80-e2f3-11eb-8b3d-5de6adebf61b.png)
![Screenshot_2021-07-09-16-18-33-351_com android chrome](https://user-images.githubusercontent.com/5962216/125226651-48213c00-e2f3-11eb-9a1c-636559100597.png)

**Comment by tanmayjay** [comment]
Fixed in #1275
