### ISSUE TITLE
Employee export-import to CSV is not consistent

### ISSUE THREAD

**Issue by tareq1988** [wp-erp/wp-erp#1278]
Exported the employees from a live site and imported in local, it should be imported without any error as it was exported. But it couldn't import any data.

![image](https://user-images.githubusercontent.com/153669/127805225-4ebbe000-758d-417e-ba04-a9ecccb8d4ab.png)

**Comment by tanmayjay** [comment]
@tareq1988  Hello bhaiya.
I presume you have exported the csv file from our demo site or somewhere like that where those data were inserted, perhaps, a long time ago. I found out that, during that time, the usermeta for date of birth was being inserted in a wrong format (d-m-Y) which has been fixed later. Also, the phone number and some other data were not properly sanitized before inserting.
In recent releases, we have improved the sanitization and validation for all those dada while inserting and that's what's creating the inconsistency.
However, I'm looking into it for a possible solution.

**Comment by tareq1988** [comment]
It was exported from Lounge, so it's old. 

We need to run upgraders properly to fix this type of inconsistencies.

**Comment by tanmayjay** [comment]
Okay bhaiya. I will get it done.
And thank you for your response.

**Comment by tanmayjay** [comment]
Fixed in #1274
