### ISSUE TITLE
Fix metabox styling

### ISSUE THREAD

**Issue by tareq1988** [wp-erp/wp-erp#1279]
WordPress has updated the metabox design, but we never caught up with that. Now we are with a broken design, need to fix that.

![image](https://user-images.githubusercontent.com/153669/127953374-e8a138cd-9b0a-4c41-a52b-9e3dca4aa14c.png)

![image](https://user-images.githubusercontent.com/153669/127953305-4cf82699-1fb1-4a75-91be-4305ad98bdc4.png)

**Comment by tanmayjay** [comment]
Updated in #1280
