### ISSUE TITLE
CRM contacts date of birth can't get past 1972

### ISSUE THREAD

**Issue by tanv101** [wp-erp/wp-erp#1368]
Issue description:
In the CRM contacts, the date of birth can't get past the 1972 year.

How to reproduce:
Navigate to WP ERP >> CRM >> Contacts and add/edit a contact, check on the Show Advanced Fields and choose the date of birth.

System status:
WordPress v6.0.1
WP ERP v1.11.1

**Comment by anik-fahmid** [comment]
@tanv101 vai is this issue still exist?

![image](https://user-images.githubusercontent.com/18075711/198521038-0dcf5afb-749b-44fa-b424-95b1a6bcb3f0.png)

**Comment by tanv101** [comment]
@anik-fahmid  bhai, the issue has been resolved.
