### ISSUE TITLE
Image upload permission problem on both HRM & CRM

### ISSUE THREAD

**Issue by nizamuddin** [wp-erp/wp-erp#157]
Everyone can see all the images and can't upload image..

**Comment by tareq1988** [comment]
Can see all the images where?

**Comment by nizamuddin** [comment]
<img width="851" alt="screen shot 2016-03-29 at 7 16 49 pm" src="https://cloud.githubusercontent.com/assets/1357886/14109446/e6032a1c-f5e3-11e5-8800-0894b5c22429.png">

Everyone can see all images in media library

**Comment by sabbir1991** [comment]
Problem fixed. Now users can see their own attachments.
