### ISSUE TITLE
Clear cached query result on new item entry

### ISSUE THREAD

**Issue by ediamin** [wp-erp/wp-erp#160]
There are multiple queries using wp_cache_set() function. So, when a new item is inserted, related cached query should be flushed.

**Comment by tareq1988** [comment]
When object caching is enabled by a persistent backend (redis, memcached), it's creating a huge problem right now as we are not clearing the caches. We could test this by enabling w3-total-cache plugin.

**Comment by tareq1988** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Invalidate WP Cache](https://trello.com/c/q1unJhd7/3-invalidate-wp-cache)

**Comment by tanmayjay** [comment]
Fixed in v1.8.3
