### ISSUE TITLE
Weekly digest email with new leads

### ISSUE THREAD

**Issue by tareq1988** [wp-erp/wp-erp#164]
We could send a weekly newsletter containing new lead stats

<img width="589" alt="screen shot 2016-04-05 at 6 02 36 pm" src="https://cloud.githubusercontent.com/assets/153669/14281168/40074a50-fb59-11e5-80fd-932cb7ca494b.png">

**Comment by thebengalboy** [comment]
Bringing that feature with the WP ERP Pro.

Thanks
