### ISSUE TITLE
HR reporting headcount should exclude terminated employees

### ISSUE THREAD

**Issue by tareq1988** [wp-erp/wp-erp#165]
Seems like headcount is not excluding the employees from the bar chart who were terminated. It only goes up, never comes down.

![screen shot 2016-04-06 at 2 07 07 pm](https://cloud.githubusercontent.com/assets/153669/14309896/edfb5fdc-fc00-11e5-81ca-84d0bda59046.png)

**Comment by nasir9bd** [comment]
Termination date field is not updating while terminating. This bug was fixed but came again somehow. If no termination date, employees are treated as current.

**Comment by tareq1988** [comment]
I've to check the database.

**Comment by sabbir1991** [comment]
Date filed is now updated, when employee status change to terminate.

**Comment by nasir9bd** [comment]
fixed https://github.com/wp-erp/wp-erp/commit/55d6d529c7b532c5855cdaff4964cc6429d13d81
