### ISSUE TITLE
Exclude terminated users from Years of service reporting

### ISSUE THREAD

**Issue by tareq1988** [wp-erp/wp-erp#172]
I think years of service should not include terminated employees. Right now terminated users are being included in that reporting and giving false information.

**Comment by nasir9bd** [comment]
ok, looking into this.

**Comment by nasir9bd** [comment]
Corrected and sent pull request. There is another issue, when a previously terminated employee activates again, the joining date remains old one. Is this normal?

**Comment by tareq1988** [comment]
That becomes complicated. But lets not complicate things at this moment as this will happen rarely.
