### ISSUE TITLE
Unable to delete locations

### ISSUE THREAD

**Issue by mikeand13** [wp-erp/wp-erp#179]
Locations in ERP settings cannot be deleted.

**Comment by ediamin** [comment]
It's ok in my setup. I've tested both for WP 4.4 and 4.5(latest one).
Do you see any error in console?

**Comment by mikeand13** [comment]
I’m on 4.5
No errors in the console.

I am able to edit and update the locations but not delete.


> On Apr 13, 2016, at 16:03, Edi Amin <notifications@github.com> wrote:
> 
> It's ok in my setup. I've tested both for WP 4.4 and 4.5(latest one).
> Do you see any error in console?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/wp-erp/wp-erp/issues/179#issuecomment-209596811>

Mike Anderson
Chief Operations Officer
Necessity Solutions
E: Mike@necessity.solutions <mailto:charlotte@necessity.solutions>
C: 902- <tel:902-430-0400>237-7751
T: 902-454- <tel:902-454-5912>9261

**Comment by ediamin** [comment]
close due to inactivity.
