### ISSUE TITLE
Work Scheduling and Employee Timeclock

### ISSUE THREAD

**Issue by Nexis81** [wp-erp/wp-erp#183]
There should be two additions that don't rely on each other for creating employee schedules and another for a time clock system which can generate reports of total work hours, paid leave, sick leave, vacation, etc.

**Comment by digitalbitsolutions** [comment]
Hello.
I'm trying to use WP ERP, and i need to kow if there is some way to have timeclock for employees.
I mean check in and out, breaks, permissions, etc. and then get a report of everything (work hours, paid leave, sick leave, vacation, etc.).
Thanks in advance.

**Comment by thebengalboy** [comment]
Most of the features are related and implemented on the WPERP Attendance extension.
