### ISSUE TITLE
BUG in Edit Employee

### ISSUE THREAD

**Issue by eziogrieco** [wp-erp/wp-erp#194]
There are some problems when you want to update an employee.
As you can see, when you create a new employee there are some fields in WORK AREA (Department, Designation etc)
![new employee](https://cloud.githubusercontent.com/assets/18718764/14907738/27b63660-0dcd-11e6-92ef-0488833d5ea8.png)

When you want to update the employee and for example update his department it is impossible to manage
![update employee](https://cloud.githubusercontent.com/assets/18718764/14907742/324839f2-0dcd-11e6-9d69-c768431919d6.png)

**Comment by nizamuddin** [comment]
Its not a bug! Its quick update. To update employee department. Please enter employee profile then navigate to **Job** Tab then you will find **Job Information** section in that section please click **Update Job Information** then you will be able to update **Department**, **Job Title** , **Reporting to** & **Location**..
<img width="1133" alt="screen shot 2016-04-29 at 9 53 28 am" src="https://cloud.githubusercontent.com/assets/1357886/14907996/32881dfe-0df2-11e6-8627-c94ddb116130.png">

**Comment by eziogrieco** [comment]
OK! Thanks!
