### ISSUE TITLE
Leave request for employee

### ISSUE THREAD

**Issue by eziogrieco** [wp-erp/wp-erp#195]
An employee should be able to do his own leave request

![leave request](https://cloud.githubusercontent.com/assets/18718764/14907792/fbd45828-0dcd-11e6-9d12-828975c2422c.png)

As you can see, there is no area for him to submit the request

**Comment by nizamuddin** [comment]
Definitely he/she should! To see the option you must need to create at least one leave policy, here is documentation https://wperp.com/docs/hr/leave-management/create-leave-policy/ 
After that employee will see the option to take leave
<img width="814" alt="screen shot 2016-04-29 at 10 12 59 am" src="https://cloud.githubusercontent.com/assets/1357886/14908089/eaee637a-0df3-11e6-9153-54ccb2cf3ea3.png">

<img width="995" alt="screen shot 2016-04-29 at 10 16 08 am" src="https://cloud.githubusercontent.com/assets/1357886/14908098/05798346-0df4-11e6-820e-115bc81e5200.png">

Thank you for using WPERP..

**Comment by eziogrieco** [comment]
Thanks a lot!
