### ISSUE TITLE
My profile in HR

### ISSUE THREAD

**Issue by eziogrieco** [wp-erp/wp-erp#196]
I have just setted a new role (pjkt manager) to give him the project creation capability.
Now this kind of user lost the "my profile" page in HR Module

![pjktmanageruser](https://cloud.githubusercontent.com/assets/18718764/14909148/55c0e61e-0de0-11e6-9e3f-f7f1da73e785.png)

Regular employee are working good

![employee](https://cloud.githubusercontent.com/assets/18718764/14909153/64fe97de-0de0-11e6-805b-b20bc190abc9.png)

**Comment by tareq1988** [comment]
Do you still have this problem with the latest version installed? Can you please check?
