### ISSUE TITLE
Latest Announcement in HRM Overview issue

### ISSUE THREAD

**Issue by ediamin** [wp-erp/wp-erp#197]
When we click title or view full announcement icon wp returns a 500 error and alerts [object object]

<img width="796" alt="screen shot 2016-05-04 at 10 32 01 am" src="https://cloud.githubusercontent.com/assets/1541774/15005429/2dd73072-11e6-11e6-9490-a8661348196a.png">

Error log says,
```
PHP Fatal error:  Call to a member function update() on a non-object in /home/vagrant/www/wp-erp/wp-content/plugins/wp-erp/modules/hrm/includes/class-ajax.php on line 844
```

**Comment by sohelamin** [comment]
Fixed at c77105e
