### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by eziogrieco** [wp-erp/wp-erp#198]
Is it possible to approve the italian translation started in wordpress.org?
![projects translated to italian glotpress wordpress](https://cloud.githubusercontent.com/assets/18718764/15010393/15b8d9b8-11ec-11e6-9865-ca1f8120ef32.png)

**Comment by tareq1988** [comment]
Translations on WordPress.org is totally upto the related language moderator of WordPress translation project, nothing a plugin developer can do about it. In that case, may be you/we have to ask the moderator or host the translation system in our site.
