### ISSUE TITLE
When creating CRM schedule entry, notify did not send email

### ISSUE THREAD

**Issue by jari-at-crew** [wp-erp/wp-erp#202]
Created a meeting on Chrome 49.0 and said notify by email. The email did not go out 5 minutes before meeting. Clocks in client, server were on time with ntp. Tested also with task creation that a "New task has been assigned to you" email went correctly out.

Perhaps the : 5 minutes in the GUI does not mean notify 5 minutes before the meeting by email. As a user that is however how I understand it. Also, my test user I invited to meeting was on same name as me - Maybe the notifier omits this case?

**Comment by pkyadav85** [comment]
Notifications Still Not Working...
System and PHP time : Asia/Kolkata
Server: windows 2012
Website: Dedicated to ERP only.
for Cron: Task Scheduler with repeat after 5 minutes (php-cgi.exe  -f \wp-cron.php )
Note: wordpress schedule post publish works fine (some time delay 5 minutes as cron is set for every 5 minutes)  no of visit on site are very less.
