### ISSUE TITLE
Feature request: CRM Pipeline summary near top of page in CRM Dashboard

### ISSUE THREAD

**Issue by jari-at-crew** [wp-erp/wp-erp#204]
A summary distributed by each life cycle phase is important to quickly understand sales situation and performance. Besides count of leads in each phase, a column of leads in each phase would be good. If you feel the contact/company counts on top of page now suffice or feature request here not ok (email said yes, repo info no), pl. close/remove this issue.

**Comment by tareq1988** [comment]
We will implement this once our **deal** feature is implemented.

**Comment by jari-at-crew** [comment]
Ok thanks Tareq. Opened github issue 204. Communicated w Sekander on 
other items.

-Jari
