### ISSUE TITLE
leave management is broken

### ISSUE THREAD

**Issue by adilsweet** [wp-erp/wp-erp#212]
to the honourable author of the plugin
sir I have installed WP ERP for the leave management of my employees, but i'm sad its not working, I had submitted a requwst on wordpress support but didn't receive any answer there, please fix it as soon as you can, in all request link, it says all (3) approved (0) pending (0) when I click at all or pending, it says no requests found in table below

**Comment by tareq1988** [comment]
Can you please test if this issue still exists in our latest version?

**Comment by adilsweet** [comment]
ok i'll test it then will tell you

**Comment by ediamin** [comment]
closing due to issue author inactivity
