### ISSUE TITLE
Leave Entitlements are missing after assigning

### ISSUE THREAD

**Issue by kdpuvvadi** [wp-erp/wp-erp#221]
After successfully applying the Leave entitlement to the Leave policy, it doesn't show in the leave entitlements, Why is that? It happens even applying for single employee or to entire department.

**Comment by mizziness** [comment]
I am also having this issue.  I fixed it temporarily via the following code change in the file **/plugins/erp/modules/hrm/includes/functions-leave.php** for the function **erp_hr_leave_get_entitlements()**:

Change line 1003 from:
`$from_date = date( $args['year'].'-m-d H:i:s',  strtotime( erp_financial_start_date() ) );`
to:
`$from_date = date( 'Y-m-d H:i:s',  strtotime( erp_financial_start_date() ) );`

Change line 1004 from:
`$to_date   = date( 'Y-m-d H:i:s',  strtotime( erp_financial_end_date() ) );`
to:
`$to_date   = date( 'Y-m-d H:i:s',  strtotime( erp_financial_end_date() ) );`

**Comment by codeshah** [comment]
hello @mizziness and @kdpuvvadi,

Are using the latest version of the plugin on PHP 5.6?
I have tested on my local installation and failed to reproduce!

Did you find any plugin conflict or?
What does your browser console say?

**Comment by kdpuvvadi** [comment]
Using latest version with php7.0

**Comment by ediamin** [comment]
@kdpuvvadi would you please post the steps to reproduce?
