### ISSUE TITLE
Running on Frontend? 

### ISSUE THREAD

**Issue by kdpuvvadi** [wp-erp/wp-erp#222]
is there any way to run the operations from front end at least for employees like using short codes?

**Comment by ediamin** [comment]
At this moment, no. But we have plan to introduce this feature in near future.

**Comment by ediamin** [comment]
Hi @kdpuvvadi, we've release HR Frontend addon today. You can get it from here https://wperp.com/downloads/hr-frontend/

For features and documentation, please see https://wperp.com/docs/hrm-add-ons/hr-frontend/

Thanks
