### ISSUE TITLE
So many fields are missing to update data as ADMIN

### ISSUE THREAD

**Issue by karthik1190** [wp-erp/wp-erp#223]
Hi, In HRM Module, Few fields like Reporting To, Pay rate ....etc to be needed to get update every time.
But these fields are not showing on editable screen to update the data while editing the employee details as ADMIN.

**Comment by tareq1988** [comment]
To keep a history on what changed when and to what, we have moved those items from edit screen and placed them on the employee **Job** tab. From there, you can update each of them and it tracks the history of the employee.
