### ISSUE TITLE
Encryption to email sent from CRM

### ISSUE THREAD

**Issue by kdpuvvadi** [wp-erp/wp-erp#224]
We are migrating current erp to wp erp. Now the issue is all mails sent from crm to the spam and marked as not encrypted even we are SSL and sent from mail as same as the domain.  Is there anyway to prevent from bouncing all our mails to spam and how to use encryption for email?

**Comment by tareq1988** [comment]
Right now we are using default WordPress email system via `wp_mail()` function. So WordPress is handling the mailing option by default and your server is not configured to send emails as encrypted. Configure your server or use a service like [SparkPost](https://www.sparkpost.com/) or [MailGun](https://mailgun.com/) and use them by installing a [SMTP Plugin](https://wordpress.org/plugins/caldera-smtp-mailer/). Next version of WP ERP will come with a SMTP option by default.

**Comment by kdpuvvadi** [comment]
contact form 7 uses the `wp_main()` and other contact and mail sending plugins uses same functionality, my mails never ended up in the spam, why is that happening now?
