### ISSUE TITLE
WP/WooCommerce-Customer vs. WP-ERP-CRM-Customer 

### ISSUE THREAD

**Issue by RobertoDonPedro** [wp-erp/wp-erp#226]
Hi, why are the WP/WooCommerce - Users with role "customer" not available in the WP-ERP-CRM-Customer list?
In my opinion at least every customer (or even every user) should be in the CRM-list out of the box. The user should not exist and maintained twice in the system and all purchases should be tracked automatically with the user.
Thx, Robert

**Comment by codeshah** [comment]
Hello Roberto,
We have not integrated WooCommerce to our system yet. You can use the auto import feature from wp-admin → ERP Settings → Settings → CRM for now.

**Comment by ediamin** [comment]
We have now "WooCommerce Integration" add-on for this. You can download it from here [https://wperp.com/downloads/woocommerce/](url)
