### ISSUE TITLE
Add various lists to CRM-Contacts

### ISSUE THREAD

**Issue by RobertoDonPedro** [wp-erp/wp-erp#227]
It should be possible to add various lists to customers and make combinations evaluable.
For example: 
- products the customer bought 
- seminars the customer took 
- speakers he joined.

And the following filter should then be possible: Which customers took a seminar from Speaker A about Theme B, etc. 
And then send those filtered customers an email.

The lists should be 
- filled automatically with each product purchase the customer makes.
- extendable by hooks with which other plugins can add f.e. seminars the customer took and speakers he joined.

Do you have plans to implement this basic CRM Feature? 
Thx, Robert

**Comment by codeshah** [comment]
Thank you for the ideas. We have a plan to make a plugin for segmentation which will have the features you have mentioned above.

Currently, it is on planning stage and we're experimenting with mockups. If you have more ideas in mind and want to share pencil sketches, please feel free to share them in the reply :)

**Comment by sultann** [comment]
Fixed
