### ISSUE TITLE
Unable to add CRM agent

### ISSUE THREAD

**Issue by kdpuvvadi** [wp-erp/wp-erp#230]
i'm unable to make any user as a CRM agent, i can still any user crm managers but crm agent. why?

**Comment by sabbir1991** [comment]
Please check this link https://wperp.com/docs/frequently-asked-questions/general/change-wordpress-user-access-role-wperp/
You can also do that for employee from employee profile permission tab.

**Comment by kdpuvvadi** [comment]
i'm to change the roles from user profile but unable to change from HR Management > Employee > Permissions

**Comment by sabbir1991** [comment]
Which plugin version you are using now. ? Please check our latest released version. v1.1.0

**Comment by kdpuvvadi** [comment]
Just got update, as 1.0.1 is installed now, i think i should update. tanks though.

**Comment by kdpuvvadi** [comment]
Just update to v1.1.0, now problem changed, i can't remove role from permission tab, as i can do that from user profile
