### ISSUE TITLE
Employees shouldn't change their educational and work history

### ISSUE THREAD

**Issue by kdpuvvadi** [wp-erp/wp-erp#231]
if a employee can add his work experience by himself, how come it good for company. he can manipulate the data right? how we restrict employees changing their work and educational details even  the employee is hr manager. he should change his own details like  this.

**Comment by kdpuvvadi** [comment]
It is not fixed yet?

**Comment by thebengalboy** [comment]
We are not considering this at this moment as we think Employee might need to update their work and work history
