### ISSUE TITLE
WP REST APIs for WP ERP?

### ISSUE THREAD

**Issue by kdpuvvadi** [wp-erp/wp-erp#240]
how can we use wp rest api for erp modules? how to use authentication here?

**Comment by sohelamin** [comment]
We didn't implement REST API feature yet.
But we've a plan to make it in near future. So if you badly needed then you've to define the endpoints by yourself for now :)

**Comment by kdpuvvadi** [comment]
Any time period for this?

**Comment by sohelamin** [comment]
No ETA for now.
