### ISSUE TITLE
CRM: Notification Email Error: 

### ISSUE THREAD

**Issue by pkyadav85** [wp-erp/wp-erp#245]
I tried to check: is this schedule function is working or not by placing Mail() at various stage.

after every schedule i am getting 1st mail  at test@yttest.com but after that no other email (test1@yttest.com/ test2@yttest.com.....) 

**function erp_crm_customer_schedule_notification() {**
    $to = "test@yttest.com";
 $subject = "My subject";
 $txt = "Hello world!";
 $headers = "From: test@yttest.com";
 mail($to,$subject,$txt,$headers);
    **$schedules = \WeDevs\ERP\CRM\Models\Activity::schedules()->get()->toArray();**
    **foreach ( $schedules as $key => $activity ) {**
        **$extra = json_decode( base64_decode( $activity['extra'] ), true );**
$to = "test1@yttest.com";
 $subject = "My subject";
 $txt = "Hello world!";
 $headers = "From: test@yttest.com";
 mail($to,$subject,$txt,$headers);
        **if ( isset ( $extra['allow_notification'] ) && $extra['allow_notification'] == 'true' ) {**
 $to = "test2@yttest.com";
 $subject = "My subject";
 $txt = "Hello world!";
 $headers = "From: test@yttest.com";
 mail($to,$subject,$txt,$headers);
            **if ( current_time('Y-m-d H:i:00') >= $extra['notification_datetime'] ) {**
$to = "test3@yttest.com";
 $subject = "My subject";
 $txt = "Hello world!";
 $headers = "From: test@yttest.com";
 mail($to,$subject,$txt,$headers);
                **erp_crm_send_schedule_notification( $activity, $extra );**
            }
        }
    }
}

**Comment by pkyadav85** [comment]
According to me 
### foreach ( $schedules as $key => $activity ) {

is not picking any schedule activity.. even though one is created..

**Comment by sabbir1991** [comment]
Please pull the latest develop verison and test again.

**Comment by pkyadav85** [comment]
Again tried..

### Still Not Working..
created 2 notifications with gap of 10 minutes..
### getting mail only from if ( empty( $schedules )  "test1@yttest.com" only




function erp_crm_customer_schedule_notification() {
    $schedules = \WeDevs\ERP\CRM\Models\Activity::schedules()->get()->toArray();

    if ( empty( $schedules ) )  {
        **$to = "test1@yttest.com";**
$subject = "My subject";
$txt = "Hello world!";
$headers = "From: test1@yttest.com";
mail($to,$subject,$txt,$headers);
        return;
    }

    foreach ( $schedules as $key => $activity ) {
        $extra = json_decode( base64_decode( $activity['extra'] ), true );
        $to = "test2@yttest.com";
$subject = "My subject";
$txt = "Hello world!";
$headers = "From: test2@yttest.com";
mail($to,$subject,$txt,$headers);
        if ( isset ( $extra['allow_notification'] ) && $extra['allow_notification'] == 'true' ) {
            if ( ( current_time( 'mysql' ) >= $extra['notification_datetime'] ) && ( $activity['start_date'] >= current_time( 'mysql' ) ) ) {
              $to = "test3@yttest.com";
$subject = "My subject";
$txt = "Hello world!";
$headers = "From: test3@yttest.com";
mail($to,$subject,$txt,$headers);
              
                if ( ! $activity['sent_notification'] ) {
                    erp_crm_send_schedule_notification( $activity, $extra );
                }
            }
        }
    }
}

**Comment by pkyadav85** [comment]
Issue Solved.. Please close this..

Thanks for your help and support.. :+1:
