### ISSUE TITLE
SMTP (email)  not working in case of no Authentication....

### ISSUE THREAD

**Issue by pkyadav85** [wp-erp/wp-erp#246]
SMTP mail not working in case if authentication is note required..

I am trying to configure ERP with my local mail server which do not require authentication..

error while testing settings in erp settings (test mail)

**"No email address provided"**

**Comment by sohelamin** [comment]
In order to configure & working the SMTP correctly you should have input the required fields.
Also there is a test option as well, so you will get confirmed once it connected.
