### ISSUE TITLE
Feature request: Add contact group to Search Filter

### ISSUE THREAD

**Issue by RobertoDonPedro** [wp-erp/wp-erp#247]
Hello, could you please extend the Contacts - Search filter to search for contacts which are (and/or are not) members of certain contact groups?
Thx, Robert

**Comment by ediamin** [comment]
closed #247 via cc33df2060a661b5d9ae462ef020e63a4bce6a43

**Comment by ediamin** [comment]
closed #247 via cc33df2060a661b5d9ae462ef020e63a4bce6a43
