### ISSUE TITLE
issue in list/grid display on some browsers.

### ISSUE THREAD

**Issue by pkyadav85** [wp-erp/wp-erp#258]
in Miscrosoft explorer and Edge list display dosent work properly..

Please check the image for ref..
![list blank](https://cloud.githubusercontent.com/assets/19799701/16404548/b336c82e-3d1d-11e6-8b38-a44c20c5f5d1.png)

**Comment by pkyadav85** [comment]
on chrome and firefox it works fine..

**Comment by codeshah** [comment]
Hello @pkyadav85,
I have tested the issue you have mentioned and successfully reproduced. The developer team is already working on legacy browser support.
Hopefully this will be fix on the next update :)

**Comment by thebengalboy** [comment]
Microsoft Edge moved to the chromium engine and explore is dead. So, this issue is not valid anymore.
