### ISSUE TITLE
payments not working.

### ISSUE THREAD

**Issue by pkyadav85** [wp-erp/wp-erp#259]
we are trying to add payments but its not working..

**Comment by codeshah** [comment]
Hello @pkyadav85,
Please mention your issue in detail. Like- what you tried to do and exactly where you got stuck.

**Comment by pkyadav85** [comment]
After filling the complete details submit button is actually not submitting the details..

**Comment by pkyadav85** [comment]
Any solution??

not able to add payments.. 
submit/add payment button just refreshes the page without saving anything..

**Comment by pkyadav85** [comment]
issue solved used php 5.6 instead of 7.0
