### ISSUE TITLE
Payments in others currencies

### ISSUE THREAD

**Issue by kdpuvvadi** [wp-erp/wp-erp#260]
If one customer pay the due amount in USD as the company receives money in INR(as set in the company details), they are not converting into INR as they are just adding into  the money as INR, if the outstanding amount is 4 lacks and customer paid 4k USD and i shows 4 lacks 4 thousands, why is this happening like that?

**Comment by tareq1988** [comment]
We don't yet have multi-currency support. So right now you've to convert that 4k USD to INR and receive the payment with the converted amount in INR.

**Comment by kdpuvvadi** [comment]
Thank you, any future plans on that?

**Comment by tareq1988** [comment]
Yes, we do have plans. But we have other issues with higher priorities and they needs to be solved first.
