### ISSUE TITLE
Sales transactions messing up

### ISSUE THREAD

**Issue by kdpuvvadi** [wp-erp/wp-erp#261]
As a generate invoice for a sale event and added a payment to the due amount outstanding amounts takes both of the added, like if invoice of 4K released and added 4K of payment to that invoice, payments shows Received 8k and status shows 2 paid, this isn't quite r8, as here we only receive 4k

**Comment by tareq1988** [comment]
Can you share a screenshot?

**Comment by kdpuvvadi** [comment]
and BTW payment added as USD also showing as INR, why?
![capture](https://cloud.githubusercontent.com/assets/7326255/16539942/3c0126ae-4070-11e6-885c-daec1b9d4e1c.JPG)

**Comment by tareq1988** [comment]
Seems like all are counted as received, but shouldn't happen. Will take a look on that.

In reply to the other questions, we only have a single currency support for now.

**Comment by kdpuvvadi** [comment]
on the currency,  it is okay, and This is major problem for anyone r8?, please take a look.

**Comment by shawon786** [comment]
The first portion of this issue has been resolved 💯
