### ISSUE TITLE
Accounting currency schema update

### ISSUE THREAD

**Issue by tareq1988** [wp-erp/wp-erp#270]
According to [GAAP](https://en.wikipedia.org/wiki/Generally_accepted_accounting_principles), we should change our database pricing schema (currently `DECIMAL(10,2)`) to `DECIMAL(13,4)` for more precision. 

Ref: [Blog post](https://rietta.com/blog/2012/03/03/best-data-types-for-currencymoney-in/)

**Comment by tareq1988** [comment]
What about the transaction items table?

**Comment by asaquzzaman** [comment]
I will update it later

**Comment by tareq1988** [comment]
You can't close an issue without fully fixing the issue.
