### ISSUE TITLE
User's role isn't showing correctly on edit page

### ISSUE THREAD

**Issue by sohelamin** [wp-erp/wp-erp#271]
When I edit a normal user it is showing an error 

<img width="1106" alt="screen shot 2016-07-17 at 10 59 03 am" src="https://cloud.githubusercontent.com/assets/1708683/16898871/49c0395c-4c0e-11e6-9fe6-9d904245b42d.png">

It's happening only when hr module is deactivated.

**Comment by tareq1988** [comment]
The function should be added via filter from the HR module.
