### ISSUE TITLE
Account Permissions option missing from Employee Permission management

### ISSUE THREAD

**Issue by kdpuvvadi** [wp-erp/wp-erp#274]
I was unable to change the employees permission in EMployee Permission tab as the option is missing from there and i found it in the wordpress user profiles page, why is that? HR managers don't have access to that. how come they are gonna change the permissions of a employees if there is no way for them ti change it.

![User Profile](https://cloud.githubusercontent.com/assets/7326255/16939797/78b77f5a-4da2-11e6-9019-65a447ad1136.JPG)
![User Permission Tab](https://cloud.githubusercontent.com/assets/7326255/16939798/78e1cd00-4da2-11e6-9e7b-6abfcbd03156.JPG)

**Comment by codeshah** [comment]
Hello @kdpuvvadi,
In which version you were having the issue? Is it 1.1.4? I mean the latest version?

**Comment by kdpuvvadi** [comment]
it was 1.1.3 and i can't update it to 1.1.4, after deactivating and deleting the plugin, tried to install it but facing 
`Installation failed: Could not copy file. erp/assets/js/upload.js
`

**Comment by kdpuvvadi** [comment]
if i try to install it by manually uploading from ftp, it is going into infinite redirect loop

**Comment by shawon786** [comment]
Already fixed :)
