### ISSUE TITLE
Payment details not saving..

### ISSUE THREAD

**Issue by pkyadav85** [wp-erp/wp-erp#279]
I am again placing the same issue as before.
Payment details are not saving..

i have also tried to do a fress install but same issue is there.
after clicking on submit button page refreshes without saving anything..

i remember in v1.1 it was working but in v1.1.1 and in latest pull its not working.

same error at both payment location.
1) Receive payments from sale ...
1) add payment within invoice details..

**Comment by codeshah** [comment]
Hello @pkyadav85,
If you are pulling from Github, you must run `composer dumpautoload -o` each time. And you have to make sure that your servers PHP version is 5.6 or higher.

We have tried to reproduce the issue you have reported and failed.

You can install from WordPress.org and check again.

**Comment by pkyadav85** [comment]
Dear Sir,

I have already done what you have suggested many times. 

My php is 7.0.5

I also tried by creating a new Wordpress site and installing v1.1.1 from plugins.  

Still no luck. 

I can provide u my site user id and password to check if it is of any use.

**Comment by codeshah** [comment]
Please try with PHP 5.6. We have not tested with PHP 7 and can not assure you that it would work fine with PHP 7.

If you ever need to provide us the login details, please contact via support@wperp.com

**Comment by pkyadav85** [comment]
WORKING with php 5.6
