### ISSUE TITLE
Uncaught TypeError: $(...).wpColorPicker is not a function

### ISSUE THREAD

**Issue by Prometee** [wp-erp/wp-erp#280]
Hi,

We got this error on all admin pages with the latest version of Wordpress+WP_ERP and on some pages this error break the rest of javascripts processes : 

```javascript
Uncaught TypeError: $(...).wpColorPicker is not a function
```
Could you load your admin scripts only for the pages related to the plugin or load the wpColorPicker before your scripts ?

**Comment by ediamin** [comment]
@Prometee I can't reproduce this error in my current setup. Please, answer the followings and help me to reproduce it:

1. What is your WP version
2. What is your WP ERP version (if from github, please mention which branch).
3. Is there any default admin page we can see this error?
4. Are you seeing this error in some other plugin's admin page? If yes, please mention the plugin name.

**Comment by Prometee** [comment]
Hi,

1. WP : Version 4.5.3
2 WP ERP : Version 1.1.1
3 index of pages or posts
4 All admin pages

I think the problem is https because there is a previous error : 

```javascript
Mixed Content: The page at 'https://.../wp-admin/edit.php?post_type=page' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/ui/1.10.4/jquery-ui.js?ver=e123adf68df847203d53d86b641aa575'. This request has been blocked; the content must be served over HTTPS.
```
I don't know if it's related to the plugin or WordPress but wpColorPicker need jQueryUI (widget plugin part) to be loaded before it. So WP ERP need to load `erp-accounting.js` depending on jquery-ui and not only jquery.

**Comment by ediamin** [comment]
Hi @Prometee , please pull the latest develop branch. I've added wp-color-picker dependency for erp-accounting.js. It should fix your problem. 

By the way, I guess you've disabled HR module, am I right? And the error for jquery-ui, I think some other plugin/theme is responsible for it. In your error log, ui is trying to load from jquery CDN, but WP ERP uses the js from wp core. So, if you're still seeing this error, please disable all plugins and custom themes except WP ERP and check the console for any error.

**Comment by Prometee** [comment]
@ediamin it's ok for cdn jquery-ui, we found that a woocommerce-warehouses plugin is responsible for creating the error.

And yes, you are right we disable HR module.

We will checkout trunk version and test the fix.

Thx !

**Comment by Prometee** [comment]
Bug is fixed thx a lot :)
