### ISSUE TITLE
Send announcement to employee group (department)

### ISSUE THREAD

**Issue by mithublue** [wp-erp/wp-erp#281]
In HR Management > Announcement , New announcement can be assigned to either all employees or selected employees. But when employees are many in number, fact is, it will be tedious adding employee in the announcement list one by one . More over there might be a scenario where , authority might want to send announcement to all employees of specific department.

So, having another option to select a department too, to send announcement could be a good option for addition.

**Comment by sultann** [comment]
Fixed
