### ISSUE TITLE
No option to select contact stage while importing

### ISSUE THREAD

**Issue by codeshah** [wp-erp/wp-erp#290]
When I am using the Contacts importing feature from ERP Settings -> Tools -> Import, I can only select which value goes on which field.

All the contacts have the status "Lead" by default. But I might need to import contacts as customers or any other state.

Please add the option.

Thank you.

**Comment by sohelamin** [comment]
Are you trying to import CSV?
If yes then you can set the default contact owner & life stage from ERP Setting -> Settings -> CRM -> Contacts tab.
