### ISSUE TITLE
Unable to change CRM Contact Owner

### ISSUE THREAD

**Issue by kdpuvvadi** [wp-erp/wp-erp#293]
I'm trying to change the owner of the contact in CRM module, If administrator tries to change ownership,  it just closes after clicking on update but ownership doesn't change and if any other CRM Managers try to change ownership it just shows  `you don't have any permission to edit this contact` and if the contact is created by CRM manager it shows same error for other users but administrator but it doesn't change the ownership.

**Comment by codeshah** [comment]
Hello Kdpuvvadi,

I have just tested this issue with the latest version and everything is working fine. Can you please test again and confirm?

**Comment by jaredanderson1972** [comment]
I have the most recent version. Everything seems to be working except I am also not able to change ownership in CRM. I don't get any errors, it just doesn't save the change. Other fields do save in the edit this client form.

**Comment by jaredanderson1972** [comment]
You did not solve the issue on my above comment. The issue of not being able to change the ownership of a client in the CRM has not been resolved. I have the most recent version and it does not work correctly. I am interested in purchasing the project management plug-in, but want to make sure the other modules such as crm work correctly first. Thanks for your help.

**Comment by ediamin** [comment]
@jaredanderson1972 Is this happening with the contact editor popup? If yes, please pull the latest commit from develop branch. Also you can try changing the ownership from left sidebar "Contact Owner" option in contact single page.

If any of these solution doesn't work for you please provide a screenshot of the page on which you're trying to change the ownership.

**Comment by jaredanderson1972** [comment]
I don't see the single contact page you are referring to. I am providing a screenshot of my issue. 
![screenshot 30](https://cloud.githubusercontent.com/assets/22951267/19576862/fc2cf856-96d1-11e6-9194-9ccd72a033fd.png)
![screenshot 31](https://cloud.githubusercontent.com/assets/22951267/19576861/fc2cbeae-96d1-11e6-8afb-e54ee3a4c8c4.png)

**Comment by ediamin** [comment]
Yes, this error with the popup should fixed by now. But you have to pull the latest commit from develop branch from github. Please confirm whether you pull the latest changes from github develop branch or not.

You can go to the single page by clicking the contact name, or View option. Please see the attached image below...
<img width="418" alt="screen shot 2016-10-21 at 2 37 46 am" src="https://cloud.githubusercontent.com/assets/1541774/19577235/26f93b74-9738-11e6-9dcc-b853a1aee974.png">

**Comment by jaredanderson1972** [comment]
I pulled the latest commit and it works great now. Thanks for all your help! You guys are doing a great job.

**Comment by jaredanderson1972** [comment]
I don't see a way to change owner on that page, maybe the permissions are
set wrong. I went to github to pull the latest commit, but I'll be honest I
am not sure what to grab as there are a bunch of options. Please specify
which one to grab. Thank again.

**Comment by ediamin** [comment]
Here is the commit link https://github.com/wp-erp/wp-erp/commit/1ca0016d6bc07c2cc06d1b6a3c95a2c1e8c31a45

Commit SHA1 1ca0016d6bc07c2cc06d1b6a3c95a2c1e8c31a45

**Comment by ediamin** [comment]
hi @jaredanderson1972, did this commit resolve your issue?

**Comment by jaredanderson1972** [comment]
Yes, thank you. I thought I had already responded. Sorry about that.
