### ISSUE TITLE
Expenses details not saving

### ISSUE THREAD

**Issue by donmed** [wp-erp/wp-erp#294]
Hello
I have version 1.1.3 of WP ERP pluggin installed on wordpress 4.5.3 , PHP version 5.6
Anytime I add a new vendor and try to make a payment voucher, the page reloads to an empty list " no transactions found"
I have tried uninstalling, clearing the sql database and reinstalling the plugin. Have tried multiple fresh installs of the plugin on new wordpress installs too.
I wouldnt mind giving access to see the issue in the event it is not reproducible from your end.

Thank you.

**Comment by asaquzzaman** [comment]
Solved this issue [98ed0a8](https://github.com/wp-erp/wp-erp/commit/98ed0a87e0a596312afa66f9732ccd6af9165bfa)
