### ISSUE TITLE
Invoices: Tax is not calculated correctly when a discount is present

### ISSUE THREAD

**Issue by WhiteaglePT** [wp-erp/wp-erp#295]
Hey guys,

Great work on this, looks amazing.
I've been testing it out and found a bug.

When you've value added taxes on invoices and do discounts at the same time it's not calculating properly.

For instance, in the example bellow where the value is 200€, with a 50% discount and a tax rate of 23%, the tax should be 23€ rather than 46€ since the total value to be paid is 100€.

![tax](https://cloud.githubusercontent.com/assets/1419978/17829362/39c23a72-66a4-11e6-8320-2e1ad6929958.png)

I may try to give it a go to fix it and do a pull request as soon as I manage to figure it out.

Thanks!

**Comment by asaquzzaman** [comment]
Solved the problem [28f3806ba20c86e46d62f3f6452b2a0aa557e37d](https://github.com/wp-erp/wp-erp/commit/28f3806ba20c86e46d62f3f6452b2a0aa557e37d)
