### ISSUE TITLE
Deals

### ISSUE THREAD

**Issue by monogios** [wp-erp/wp-erp#298]
CRM needs a Deals sections so it can be considered as a CRM.

**Comment by codeshah** [comment]
Hello @monogios,

We are already working on the deals feature and it is close to the beta release. All of our paid customers have access to our beta testing program. So if you have purchased any add-on from us, please send an email to support@wperp.com. When it is ready for testing, I will send you via reply.

**Comment by tareq1988** [comment]
Duplicate of #151. The add-on has been created and is in testing.
