### ISSUE TITLE
Overpayment entries are not recognized in accounting invoice

### ISSUE THREAD

**Issue by codeshah** [wp-erp/wp-erp#301]
I have an invoice for $10.
If I enter a payment of $20. The invoice says "Awaiting Payment". Also the calculations and graphs are not working correctly.

**Comment by johnvinsongo** [comment]
By the way, last October 1 I was able to figure out what's causing the double entry of paid transactions / closed transactions on the charts above each page that renders the charts.

It has something to do with the files on \accounting\includes\views\common\transaction-chart.php

Some of the logical statements to count the transactions are set with wrong conditional statements and some with missing conditional statements (especially for total amount of Paid transactions and the counter for the total Paid Items)
