### ISSUE TITLE
CSV Export/Import feature for Accounting module

### ISSUE THREAD

**Issue by sekanderb** [wp-erp/wp-erp#306]
People might want to export data for backup and sharing or reviewing purpose, then correct it and import to the system again.
So this feature would be essential.

**Comment by codeshah** [comment]
Some of the users wanted reports exporting feature. We can make an extension which will allow to export different kind of pie, bar and doughnut bars and export them as images to use in pptx files.

We should also provide CSV and xls exports for the reports.

**Comment by codeshah** [comment]
You can follow google sheets exporting features for reference

**Comment by tanmayjay** [comment]
Hello @sekanderb,
This feature is available from v1.7.0

Thanks.

**Comment by sekanderb** [comment]
Thanks. It's a life-changing feature!

**Comment by Diego-Schmidt** [comment]
There is no option to export all transactions list... where are those exporting options?
