### ISSUE TITLE
Leads and opportunity count does not update unless the page is reloaded

### ISSUE THREAD

**Issue by codeshah** [wp-erp/wp-erp#314]
When I add a new contact on the CRM module, then the contact and all the details are updated successfully.

But the count on the top does not update unless I refresh the page.

And when I move a contact from the opportunity to leads. The data is transferred to the tab but I have to manually refresh the page. Else the data is shown on the tab despite disappearing. Surprisingly the count is updated this time 😝

**Comment by sabbir1991** [comment]
Resolve commit ebc21650ee
