### ISSUE TITLE
unable to install on some hosts

### ISSUE THREAD

**Issue by kdpuvvadi** [wp-erp/wp-erp#315]
I can install the plugin on VPS and cloud hosting but i can't install it on some shared or reseller hosting. getting below error, file name changes every time. Can't install it even manually.
`Installation failed: Could not copy file. erp/vendor/symfony/translation/Tests/Dumper/FileDumperTest.php
`

**Comment by sohelamin** [comment]
Are you trying to install it from github?

If you try to upload it manually to shared hosting from the github version then follow the commands:

1. Clone the repo to your local development machine
2. Install composer dependencies via ```composer install``` & run ```composer du -o```
3. Then zip & upload the plugin to your site

**Comment by monogios** [comment]
I'm using this plugin on https://www.brontobytes.com/web-hosting.php without a problem. It's pretty fast as well.

**Comment by kdpuvvadi** [comment]
I'm not using github version, i'm trying to install the wp repo version, BTW host for some sites is bluehost.

**Comment by codeshah** [comment]
Last time I checked BlueHost, their PHP version was 5.4 on their shared hosting. But WP ERP requires the version to be 5.6.

Can you please check and confirm? If all the requirements are met and you are still unable to activate or install the plugin, please let us know at- support at wperp dot com

**Comment by kdpuvvadi** [comment]
actually PHP 5.6 in installed and set as default

**Comment by monogios** [comment]
I can confirm that this modules works with PHP 7 and 7.1 as well.
