### ISSUE TITLE
Feature Request: Create Separate tabs for importing

### ISSUE THREAD

**Issue by sekanderb** [wp-erp/wp-erp#320]
The current importing system seems a bit confusing. So I have a suggestion to add separate tabs to import the data into different modules.

For an example, you can see this screenshot http://prntscr.com/cwio5h

**Comment by tanmayjay** [comment]
Hello, @sekanderb 
We already have all type of imports in the dropdown where the types have distinct names and so there should be no confusion. However, we will consider your suggestion and apply it if needed.

Thanks.

**Comment by sekanderb** [comment]
Thank you for your prompt response. I love the development speed!
