### ISSUE TITLE
Feature Request: Accounting Invoice Email Does Not Contain Much Information

### ISSUE THREAD

**Issue by sekanderb** [wp-erp/wp-erp#321]
When I email an invoice, the email should say some words like this the item name date and a description.
The link to view the invoice is not clickable.
You can have a look at how the email looks by default http://prntscr.com/cxqpp0

It would be better if we add an email template for the invoice email.

**Comment by thebengalboy** [comment]
WPERP sends the full invoice in PDF now with all the information.
