### ISSUE TITLE
Feature Request: Add recipient field for HR emails

### ISSUE THREAD

**Issue by sekanderb** [wp-erp/wp-erp#322]
The email notifications are sent to respective user roles and they can not be modified from anywhere.

Like when someone creates a leave request, only the HR Manager is notified. But the employee might need to take permission from the group or project lead or the HR manager might need to inform the project lead.

So people might need to add two or more email recipents. You can follow the comma separated format of WooCommerce and allow shortcodes to assign the department head or reporting to person.

**Comment by thebengalboy** [comment]
This feature will come with our upcoming multi-level leave approval system. Thanks
