### ISSUE TITLE
Feature Request: Add leave calculation based on joining date.

### ISSUE THREAD

**Issue by sekanderb** [wp-erp/wp-erp#324]
Suppose, the organization allows 20 paid leaves in a calendar year.
An employee joined after the half calendar year. So he should get 10 days assigned automatically.
Likewise, if someone joins after 8 months, then he should be allowed 3-4 days approx.

So you will get the leave policy for a designation, then divide it by the calendar year and then assign according to the joining date.

**Comment by nurul-umbhiya** [comment]
We added Leave Segregation feature on [Advanced Leave Management](https://wperp.com/downloads/advanced-leave-management/) module.
