### ISSUE TITLE
Issue: Invoice payment not working properly

### ISSUE THREAD

**Issue by sekanderb** [wp-erp/wp-erp#327]
Steps to reproduce the issue:
1. Create an invoice for $10.
2. Now create another invoice for $20. Both of the invoice will be for the same customer.
3. Now go to payments and select the customer name. Two invoices will be displayed and the total amount would be $30.
4. Now enter $100 instead of $10 on the first invoice amount and $220 instead of $200 on the second invoice amount.
- Now the payment voucher will forget everything except the amount. http://prntscr.com/cz0qtk
- The original invoices will still have amount pending.
- The customer profile will not show that he paid extra rather would say that this customer still owes you $30

**Comment by codeshah** [comment]
The issue still exists on the latest develop version 😐

**Comment by shawon786** [comment]
Already Fixed :)
