### ISSUE TITLE
Bug: Can pay more than account balance and select a date before the voucher was created

### ISSUE THREAD

**Issue by codeshah** [wp-erp/wp-erp#328]
1. Create an expense entry double than your petty cash balance on todays date.
2. Enter payment amount larger than the petty cash balance and select a previous date.
you can even select a future date.

**Comment by asaquzzaman** [comment]
[Closed](https://github.com/wp-erp/wp-erp/commit/9eeb8d22bfa8abe6d038ac73eb1550332240eb17)
