### ISSUE TITLE
Feature Request: Set default values for new employees in new employee create form

### ISSUE THREAD

**Issue by sekanderb** [wp-erp/wp-erp#335]
While creating an employee, there should be some fields set by default to save some time. Like-

1. Reporting to - Department Head
2. Employee status - Active
3. Date of hire - current date
4. City - Company City
5. Country - Company Country
6. Pay Type - Monthly
7. Employee ID - Increase 1 with the last record (can add suffix and prefix configuration just like invoices)

We can add settings for default values as well. This would save a lot of time.

**Comment by shawon786** [comment]
Improved HRM has the capability to create contact within a short time :)
