### ISSUE TITLE
Feature Request: New employee with same email

### ISSUE THREAD

**Issue by codeshah** [wp-erp/wp-erp#336]
I have an employee named worker1 and he works on the marketing department. So I have created an email address for him marketing@site.com

Now worker1 is terminated for some reason and I hired worker2 to handle the marketing tasks. But the email address is same!

The system is currently not allowing me to create a new user with the same email.

As the previous one is terminated, the email will not have any notifications or communications that needs to be delivered. I have user ID and employee ID. So these the are different. I can also know the difference from the hiring date.

So I believe, we can modify the filter.

- When there is an active employee with the same address. We will not let add that same email address and will say, "An user with this email address already exists. You can not use the same email address for 2 active employees"

- When the previous user is terminated, then we can use the same email address for the new employee.

**Comment by ediamin** [comment]
Two persons should not have same email ever, even if one of them stop using it. This is not logical and I believe no one use this kind of logic.
