### ISSUE TITLE
New Shift Modal style improvement

### ISSUE THREAD

**Issue by codeshah** [wp-erp/wp-erp#34]
* The add new shift button is not styled correctly
* The modal needs to be well styled.
* Also saving the settings does not show any message that it was saved
* Shift Does not show instantly right after closing the module. Have to save once.
* Clicking on the shift title does nothing
* Can not edit shift once created.

**Comment by nasir9bd** [comment]
fixed and repo updated on bitbucket. thanks for reporting.
