### ISSUE TITLE
Improvement: Vendor Credit does not display any error message for wrong date

### ISSUE THREAD

**Issue by codeshah** [wp-erp/wp-erp#341]
Navigate to wp-admin → Accounting → Expenses → Vendor credit and try to select a previous date on the due date field.
It will reset the field and will not tell that the date is not valid.

**Comment by asaquzzaman** [comment]
[Vendor Credit does not display any error message for wrong date](https://github.com/wp-erp/wp-erp/commit/25ed92eeefae1ae15d897b9383eef264eb62a123)
