### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by johnfelipe** [wp-erp/wp-erp#347]
cd /var/www/html/wp-content/plugins
	sudo sudo apt-get install git 
	sudo git clone https://github.com/wp-erp/wp-erp.git

	change to erp

	sudo chown -R www-data:www-data /var/www/html/wp-content/plugins/erp/

show me this

Warning: include(/var/www/html/wp-content/plugins/erp/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/erp/wp-erp.php on line 201

Warning: include(): Failed opening '/var/www/html/wp-content/plugins/erp/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/wp-content/plugins/erp/wp-erp.php on line 201

Fatal error: Trait 'WeDevs\ERP\Framework\Traits\Hooker' not found in /var/www/html/wp-content/plugins/erp/includes/class-install.php on line 19

**Comment by johnfelipe** [comment]
felipesneideradmin@academiaweb:/var/www/html/wp-content/plugins$ sudo git clone https://github.com/wp-erp/wp-erp.git
	Cloning into 'wp-erp'...
	remote: Counting objects: 17061, done.
	remote: Total 17061 (delta 0), reused 0 (delta 0), pack-reused 17061
	Receiving objects: 100% (17061/17061), 9.97 MiB | 2.33 MiB/s, done.
	Resolving deltas: 100% (10453/10453), done.
	Checking connectivity... done.
	felipesneideradmin@academiaweb:/var/www/html/wp-content/plugins$ cd wp-erp
	felipesneideradmin@academiaweb:/var/www/html/wp-content/plugins/wp-erp$ composer install
	Loading composer repositories with package information
	Installing dependencies (including require-dev) from lock file


	  [RuntimeException]
	  /var/www/html/wp-content/plugins/wp-erp/vendor does not exist and could not
	   be created.


	install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

How solve that issue?

**Comment by ediamin** [comment]
Your directory is not writable. You cloned the repo with `sudo`, which permitted git to write on your disk. Try `sudo composer install`. But it is not a good idea to use `sudo` for these purpose. Problem is your server is running with the user `www-data` and you're logged into as `felipesneideradmin` and trying to write into a directory in which `felipesneideradmin` has no permission.

**Comment by johnfelipe** [comment]
How can solve it?

**Comment by ediamin** [comment]
As I suggested, try `sudo composer install`

**Comment by johnfelipe** [comment]
But this https://getcomposer.org/root, how can solve that?

**Comment by sohelamin** [comment]
@johnfelipe We've no plugins or scripts bounded to the composer.json so you can run as sudo

**Comment by sohelamin** [comment]
Or even if you don't like to run composer command through your server then clone the repo to your local machine's directory, install composer dependencies then zip & upload to your site or server as a plugin.

**Comment by johnfelipe** [comment]
@sohelamin pls give me correct commands for that method
Tnks

**Comment by sohelamin** [comment]
```
git clone https://github.com/wp-erp/wp-erp.git
cd wp-erp
composer install
composer du -o
```
Note: Just add `sudo` before these commands if you want to do that on your current server/site.

We've already a instruction https://github.com/wp-erp/wp-erp#installation

**Comment by johnfelipe** [comment]
"install composer dependencies then zip & upload to your site or server as a plugin."
I can do that in my /home, right?

**Comment by sohelamin** [comment]
You can do it where you put your sites normally. Or just any directory better you can put on Desktop.

**Comment by johnfelipe** [comment]
in /home is not work without sudo, then where put it for use without sudo?

**Comment by sohelamin** [comment]
Make a directory on Desktop then try.

**Comment by Akaikovm** [comment]
Hi, i try all the methods you explain here to install the plugin but i have this error now, 
Fatal error: Uncaught Error: Class 'Appsero\Client' not found in C:\xampp\htdocs\wordpress\wp-content\plugins\wp-erp\includes\class-tracker.php:30 Stack trace: #0 C:\xampp\htdocs\wordpress\wp-content\plugins\wp-erp\includes\class-tracker.php(20): WeDevs\ERP\Tracker->__construct() #1 C:\xampp\htdocs\wordpress\wp-content\plugins\wp-erp\wp-erp.php(272): WeDevs\ERP\Tracker::get_instance() #2 C:\xampp\htdocs\wordpress\wp-content\plugins\wp-erp\wp-erp.php(123): WeDevs_ERP->instantiate() #3 C:\xampp\htdocs\wordpress\wp-content\plugins\wp-erp\wp-erp.php(92): WeDevs_ERP->setup() #4 C:\xampp\htdocs\wordpress\wp-content\plugins\wp-erp\wp-erp.php(395): WeDevs_ERP::init() #5 C:\xampp\htdocs\wordpress\wp-content\plugins\wp-erp\wp-erp.php(399): wperp() #6 C:\xampp\htdocs\wordpress\wp-admin\includes\plugin.php(2223): include('C:\\xampp\\htdocs...') #7 C:\xampp\htdocs\wordpress\wp-admin\plugins.php(175): plugin_sandbox_scrape('wp-erp/wp-erp.p...') #8 {main} thrown in C:\xampp\htdocs\wordpress\wp-content\plugins\wp-erp\includes\class-tracker.php on line 30

 please help!

**Comment by thebengalboy** [comment]
Hello @Akaikovm 

Please download and use the stable released version available here: https://wordpress.org/plugins/erp/

I hope you won't face such errors in the released version :)

Thanks

**Comment by Akaikovm** [comment]
Hi Thanks @thebengalboy  that works! But now i would like to change some things, i need to add/replace the life stages for ( N1,N2,N3,N4,N5,N6,N7,N8) and i need those stages to stay in the dashboard instead of suscriber, lead etc. also i have to change some fields in the add new contact form/add employe form please . would you like to help me with a step by step guide. Im new in the development world!
