### ISSUE TITLE
how update .po file with new .pot file

### ISSUE THREAD

**Issue by johnfelipe** [wp-erp/wp-erp#349]
I have this version

	"Project-Id-Version: WP ERP 1.1.4\n"
	"Report-Msgid-Bugs-To: http://wperp.com/support/\n"
	"POT-Creation-Date: 2016-09-19 15:58:26+00:00\n"
	"MIME-Version: 1.0\n"

but with update i have

	"Project-Id-Version: WP ERP 1.1.6\n"
	"Report-Msgid-Bugs-To: http://wperp.com/support/\n"
	"POT-Creation-Date: 2016-11-09 06:56:00+00:00\n"
	"MIME-Version: 1.0\n"

how add new strings automatically or i need add manually doing compare

Stay alert

**Comment by codeshah** [comment]
Hello @johnfelipe,

If you want to update the file offline, you can read this doc http://www.marketpressthemes.com/blog/how-to-merge-two-po-files-using-poedit/

The latest .po file is available here online https://translate.wordpress.org/projects/wp-plugins/erp

If you need more detailed instructions, please let me know here :)
