### ISSUE TITLE
how translate calendar months and other strings

### ISSUE THREAD

**Issue by johnfelipe** [wp-erp/wp-erp#350]
how translate calendar months and other strings?
Tnks

**Comment by codeshah** [comment]
Hello @johnfelipe,

Thank you for reporting the issue. I to have found translation issues in the HR calendar and informed the developers. I will come back with an update within next 48 hours.

We appreciate your patience and cooperation :)

**Comment by ediamin** [comment]
@johnfelipe WP ERP is using fullcalendar as calendar component. You have to write your translations in JS files. We've added 48 translation files provided by fullcalendar. Take a look at [this commit](https://github.com/wp-erp/wp-erp/commit/474acf7117fd6a7548c61ec5cb6451c500b69464) that @codeshah made a translation file to support `bn_BD`. If you don't find your translation [here](https://github.com/wp-erp/wp-erp/tree/develop/assets/vendor/fullcalendar/lang), then make one and send a pull request. We'll happily merge your code into our core.

**Comment by ediamin** [comment]
closed via 20c856e2af27e91df23d5f44809d70728aecc883
