### ISSUE TITLE
Feature Request: Partial Day Leave Requests

### ISSUE THREAD

**Issue by kaleeraisor** [wp-erp/wp-erp#351]
It would be ideal for employees to be able to request a partial day off, for example Half Day or selecting the hours they will be out of the office.

**Comment by codeshah** [comment]
Hey @kaleeraisor,
We have an extension for [Attendance Management](https://wperp.com/downloads/attendance/). We already have received some requests to add partial day leave and it is on our to-do list.

We will start working on this feature within the second week of December this year.

Thank you

**Comment by kaleeraisor** [comment]
Great to hear partial day leave is being added soon, thanks!

**Comment by theflyingcar** [comment]
Has there been progress made on incorporating partial-day leave requests? My company would like to migrate our records to this system, but require partial-day leave. (Hour-by-hour is ideal, but half-day leave is the bare minimum our HR department needs.)

**Comment by thebengalboy** [comment]
Half-day leave feature will come with our upcoming leave management system. This has planned already.
