### ISSUE TITLE
Tweak Request: Remove currency settings from general settings to avoid confusion

### ISSUE THREAD

**Issue by codeshah** [wp-erp/wp-erp#355]

**Comment by ediamin** [comment]
It was in accounting settings before. But sometimes CRM or HR module/addon which is not depend on Accounting module may require this currency settings. So, it is now in global settings.

**Comment by tareq1988** [comment]
But right now it's on both sections and we can't have that. May be we could only put the currency settings in the general section when accounting module is not active.
