### ISSUE TITLE
Tweak: text fields are not defined on tax class

### ISSUE THREAD

**Issue by codeshah** [wp-erp/wp-erp#357]
Go to wp-admin → ERP Settings → Settings → Accounting → Sales Tax and try to edit any tax class.
You will see something like this http://prntscr.com/d7iwuo

You can see that there are three text boxes but they are not defined and there is no validation.

But if I try to view the tax class details by clicking the name on the left, then the titles appear!

**Comment by asaquzzaman** [comment]
[Solved this problem](https://github.com/wp-erp/wp-erp/commit/7d69af2c136523ebdb853f2a74edd9f36a530698)
