### ISSUE TITLE
add new in page=erp-hr-my-profile page not working

### ISSUE THREAD

**Issue by johnfelipe** [wp-erp/wp-erp#359]
Hi bro in page=erp-hr-my-profile when add new is not working

![add new](https://cloud.githubusercontent.com/assets/428820/20430846/b139e26a-ad64-11e6-911b-fc9c0b03ca9d.png)

That is normal?

**Comment by ediamin** [comment]
Hi @johnfelipe, thanks for pointing this out. An admin shouldn't add a new employee from his/her profile page. So I've removed the `Add New` button and changed the title to `My Profile` from Employee for this my profile page.

**Comment by johnfelipe** [comment]
I do this:

	felipesneideradmin@academiaweb:/var/www/html/wp-content/plugins/wp-erp$ sudo git pull
	remote: Counting objects: 10, done.
	remote: Compressing objects: 100% (10/10), done.
	remote: Total 10 (delta 0), reused 0 (delta 0), pack-reused 0
	Unpacking objects: 100% (10/10), done.
	From https://github.com/wp-erp/wp-erp
	   215ebc7..b20689a  develop    -> origin/develop
	Updating 215ebc7..b20689a
	Fast-forward
	 modules/hrm/includes/admin/class-menu.php | 1 +
	 modules/hrm/views/employee/single.php     | 4 ++--
	 2 files changed, 3 insertions(+), 2 deletions(-)

Its fine do **sudo git pull**

**Comment by johnfelipe** [comment]
Its fine do **sudo git pull**???

**Comment by ediamin** [comment]
Your sentance didn't end with `?` before, so I thought you wanted to tell us that it's fine and closed the issue. Sorry about that :|

I think we had a discussion about directory permission problem in another issue before. You shouldn't use git with sudo. But, if it works for you then go for it. 

How to setup your server is not an ERP related topic, so I'm gonna ignore it here. Basically, i) you should have a WP directory where you can create/edit files with your `felipesneideradmin ` username, ii) your server(apache/nginX etc) should create/edit files in this directory also. There are many ways to achive this. Please google for the best solution that match your needs.
