### ISSUE TITLE
Fatal error on first time plugin activation

### ISSUE THREAD

**Issue by ediamin** [wp-erp/wp-erp#36]
If I try to activate the plugin for first time wp gives an error notice
`Plugin could not be activated because it triggered a fatal error.`

debug.log says,
`[08-Mar-2016 17:49:37 UTC] PHP Fatal error:  Call to undefined function erp_hr_get_roles() in /home/vagrant/www/wp-erp/wp-content/plugins/wp-erp/includes/class-install.php on line 517`

**Comment by ediamin** [comment]
Sent a pull request resolving this issue.

**Comment by karthik1190** [comment]
Hi i am facing same issue./ Can you guide me. how to solve the issue?
