### ISSUE TITLE
Reports is not fully translated

### ISSUE THREAD

**Issue by johnfelipe** [wp-erp/wp-erp#360]
![numempleados](https://cloud.githubusercontent.com/assets/428820/20432215/1d674980-ad6c-11e6-8d80-16b833ecd454.png)

Select Year
Months
Status
Headcount by month

page=erp-hr-reporting&type=age-profile

Employee count
Age categories
Departments
Under
.
.
.

Pls review strings for translate reports
Stay alert

**Comment by johnfelipe** [comment]
Hi bros, pls tell me about my request for reports translation?

**Comment by shawon786** [comment]
@johnfelipe 

This is fixed already.
