### ISSUE TITLE
Bug: Half visible text

### ISSUE THREAD

**Issue by codeshah** [wp-erp/wp-erp#369]
http://prntscr.com/ddx8ps

I could not understand the point of the text on the marked area. Is it indicate the mismatched amount?

If yes, please re-arrange it so that it is clearly visible.

**Comment by asaquzzaman** [comment]
Fixed [8837f4](https://github.com/wp-erp/wp-erp/commit/8837f4750249f2fa8c192e19ec02ce40a9bbec01)
