### ISSUE TITLE
Table 'wp-erp.wp_erp_crm_campaigns' doesn't exist

### ISSUE THREAD

**Issue by ediamin** [wp-erp/wp-erp#37]
After a plain installation, CRM > Campaigns page has this error. Please check the attached image,
<img width="548" alt="screen shot 2016-03-09 at 10 30 32 am" src="https://cloud.githubusercontent.com/assets/1541774/13625465/3c4386d6-e5e2-11e5-971a-3a2022e24201.png">

**Comment by tareq1988** [comment]
Campaigns removed from core.
