### ISSUE TITLE
Feature Request: Recurring Invoice

### ISSUE THREAD

**Issue by sekanderb** [wp-erp/wp-erp#375]
There should be a checkbox to select if that invoice is recurring.
At the end of the period, the invoice will duplicate automatically and will be pending for approval.
Also an email notification will be sent to notify that the invoice duplication will start tomorrow and another notification after finishing the process.

**Comment by sultann** [comment]
**Add-on Idea: Subscription Invoice / Recurring Invoice** 
If anyone is running membership base business and want to create invoices in Accounting Module with kind of payment that members paid monthly then this feature is a must for them.

**Comment by sekanderb** [comment]
In my personal understanding, memberships are for clubs and small organizations. There some sites who have a large number of members and subscriptions but I do not think they would use an ERP or accounting module to keep track of those. They have bookkeeping solutions from the payment gateways and existing systems on their site.

It would be better if we keep in mind the offline transactions. Like- catering business, monthly bills of ISP, payments to rent a cars and other type of vendors.

**Comment by thebengalboy** [comment]
This feature will be released with our new extension 'Recurring Transactions'. Thanks

**Comment by metaline** [comment]
Hi, is there any news for new extension "Recurring Transactions"?
