### ISSUE TITLE
Run the updater - 500 Error

### ISSUE THREAD

**Issue by monogios** [wp-erp/wp-erp#381]
I've upgraded the WP plugin to the latest version, and once I click "Run the updater", the URL is redirected and I'm getting the following 500 Error.

https://domain.com/wp-admin/admin.php?page=erp-company&wperp_do_update=1

The domain.com page isn’t working
domain.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by codeshah** [comment]
Hello @monogios,

We apologize for the inconvenience.

If you have deactivated the accounting module, please enable it to run the updater. After updating the plugin, you can disable the accounting module.

If you get the same issue despite having the accounting module enabled, please contact support at wperp dot com for further assistance.

**Comment by monogios** [comment]
Thanks. It worked.

**Comment by ediamin** [comment]
Congratulations!
As you have resolved the issue. I am closing it for now.

We would love to hear a word or two from you on the review section of our plugin https://wordpress.org/plugins/erp
