### ISSUE TITLE
Awesome Support

### ISSUE THREAD

**Issue by tareq1988** [wp-erp/wp-erp#389]
Add integration with a native WordPress support plugin: https://wordpress.org/plugins/awesome-support/

**Comment by ben-milkshake** [comment]
Would be nice to have Support tickets connected to CRM yes.

**Comment by nschvabenitz** [comment]
I would like to add my vote to this. Our company uses Awesome Support entirely for all customer service, sales, and support. Adding Awesome Support would be HUGE for us. We would love to see this added.

**Comment by sultann** [comment]
Done
