### ISSUE TITLE
Add all the available currencies in the world

### ISSUE THREAD

**Issue by codeshah** [wp-erp/wp-erp#393]
Here is a list of all the currencies and wikipedia has all the currency symbol.
https://www.countries-ofthe-world.com/world-currencies.html

You can assign someone from the support or content or QA team to format those data and send a pull request.

Also the currency codes need to be alphabetically sorted to find things faster.

**Comment by ben-milkshake** [comment]
hi, this would be awesome adding a  defaut currency into all forms.
Also, if each company could have his own currency, 
as a company can be in any country, would be logical to define the currency of this country !
thanks
