### ISSUE TITLE
Make custom CRM admin user form

### ISSUE THREAD

**Issue by ben-milkshake** [wp-erp/wp-erp#395]
Hi, 
CRM is good, for project needs i did buy the custom field extension, even I didn't see the reduction coupon for christmas (shame on me !!!) I have surprise I cannot order fields as I want into the CRM add client form.
neither I can change some fields or hide base ones.

I am a developper, but I wish to know how to do my needs.
having titles to separate custom fields as my project requires, 
hidding fields, adding fields and making the form looking like I want. everything in admin pages of course, for main company contact and other users as wel 

Is there a way to keep ERP update possible and hooking to load a custom form ( created from the same ERP core files with my modifications but named differently)?

Do you have any tips?

thanks
regards

**Comment by ben-milkshake** [comment]
hi, I really need some inputs for this. any information would be appreciated.
regards

**Comment by ediamin** [comment]
@ben-milkshake could you provide a mockup/design of your form please?

**Comment by ben-milkshake** [comment]
Hi, I have some excel defined inputs, nothing in mokups
pero basicaly it is to implement specific parts into your form
Separate specific information for the contact where we would add our specific fields.
also into your form there's some fields we do not need.
I got that it is the same form for companies and contact, using conditionning and the framework vue.js with php files.
The awesome thing would be the possibility to overwrite those files for personal modification without loosing the update feature of your main plugin and extensions !
any idea :D 

thanks and have a good new year eve !

**Comment by ben-milkshake** [comment]
Hi, any idea to help please ? thanks

**Comment by ediamin** [comment]
Hi @ben-milkshake, I've added a filter hook for js template path. Checkout this commit ebf314a3ad6bd9d9571b153be1d8539bd5dcf0a9

So, now you can use your own customer form template. The form template is in use located at `wp-erp/modules/crm/views/js-templates/new-customer.php`. Copy and paste into your custom plugin directory and use following code to override,
```php
add_filter( 'erp_crm_js_template_file_path', function ( $file_path, $id ) {

    if ( 'erp-crm-new-contact' === $id ) {
        $file_path = dirname( __FILE__ ) . '/new-customer.php';
    }

    return $file_path;

}, 10, 2 );
```

Then after save the contact use `erp_crm_save_contact_data` action hook to execute your custom function. You can find it in `wp-erp/modules/crm/includes/class-ajax.php` file in `create_customer` method.

Thank you.

**Comment by ben-milkshake** [comment]
Awesome ediamin, thanks I'm gonna digg in this to see what I get.
for sure, this snippet gives the possibility to use my custom file. 
so for each ERP update I'll have to compare files to insert the new code, to keep using my custom version with the new features of ERP.
Except if you gives the possibility to make it happen.

thanks.
regards

**Comment by ediamin** [comment]
@ben-milkshake I'm closing this issue for now. If you have any question, feel free to reopen it.
