### ISSUE TITLE
Priority improvement: Change User searching method

### ISSUE THREAD

**Issue by rananrahim** [wp-erp/wp-erp#400]
Typing 3 letters of employees, vendors, contacts or customer is just ridiculous and tiresome to use. it is not possible to remember the first 3 letters always or exactly. Managers or admin needs to go back to the employee list or vendor list and every other list every time to check for the name and then search.
the current system is highly impractical, disturbing and time consuming. I have been using this since the first release and i hate it as a user.

**Suggested change:**
A list of last queried/selected users to be displayed upon click and an ajax search box inside the drop down menu.
This change should be in all modules, add ons and even core settings. I can get someone to make a list of where these function is being used.
![screenshot at jan 08 12-17-15](https://cloud.githubusercontent.com/assets/12949224/21747755/6a6fee78-d59c-11e6-9b0c-bcd178d437fe.png)

**Comment by tareq1988** [comment]
I was thinking to do the same for a while.

**Comment by thebengalboy** [comment]
This has been fixed already. Thanks
