### ISSUE TITLE
custom-field-builder is not working

### ISSUE THREAD

**Issue by johnfelipe** [wp-erp/wp-erp#406]
![pantallazo-0092](https://cloud.githubusercontent.com/assets/428820/21904218/e909239e-d8d0-11e6-814b-67108cc78e70.png)

Add new field button is not working, i have latest version in develop branch with hrm modification

How solved?

**Comment by shawon786** [comment]
Hi,
It's working fine on my local server. 
Can you confirm the following?

1. The PHP and MySQL version of your server is 5.6
2. You are using the latest version of WP ERP
3. There is no theme or plugin conflict (be sure to check your browser console each time)

Cheers :)

**Comment by johnfelipe** [comment]
Hi bro, pls check this

http://67.205.147.152/phpinfo.php

I do this for install wp-erp with git

	git clone https://github.com/wp-erp/wp-erp.git
	cd wp-erp/

	git checkout develop

	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

	php -r "if (hash_file('SHA384', 'composer-setup.php') === '55d6ead61b29c7bdee5cccfb50076874187bd9f21f65d8991d46ec5cc90518f447387fb9f76ebae1fbbacf329e583e30') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

	php composer-setup.php

	php -r "unlink('composer-setup.php');"

	php composer.phar install

	php composer.phar dump-autoload -o
I have network
I have default theme and none plugin in that instance

Stay alert

**Comment by johnfelipe** [comment]
i change to master branch and still not working

https://goo.gl/kXp7tn

Tnks

**Comment by ediamin** [comment]
@johnfelipe please add `define( 'SCRIPT_DEBUG', true );` in your `wp-config.php` and try again.

**Comment by johnfelipe** [comment]
My requeriments in php and mysql is fine?

**Comment by johnfelipe** [comment]
This is my plugin
https://goo.gl/O4jDKZ

This is add line
https://goo.gl/O4jDKZ

An button do nothing, pls view this video

https://goo.gl/wbH66a

Stay alert

**Comment by johnfelipe** [comment]
Hi, me again, pls tell me how solve this?

**Comment by shawon786** [comment]
Resolved :)

**Comment by ediamin** [comment]
Closing this since it is resolved with our customer support.
