### ISSUE TITLE
Accounting- Doesn’t show proper awaiting payment records

### ISSUE THREAD

**Issue by shawon786** [wp-erp/wp-erp#407]
a) I would like to submit my findings about the sales and expenses records in the accounting module.
After the Closing and Opening of balances after 2016, I have noticed that the records are displayed correctly but on the filters, it says Awaiting Payment (0). Even if I have many Awaiting Payment records. All says (0).

b) On the accounting dashboard, the Invoice payable and receivable section below doesn't show the dues properly. it shows zero.

c) I have noticed that after the opening and closing of balances after 2016, on Sales and Expenses, 

Filters on top like "Awaiting Payment (0), Closed (0)", etc., there says (0) but if you click, it just displays 1 page of records and we can't see beyond that because we have hundreds of records. It only shows 25 records and no page links.

And even on the chart of accounts, when I click on sales with 200+ records, it only displays 25 records and no page links, now we can’t see the older records.

**Comment by sultann** [comment]
Fixed
