### ISSUE TITLE
All Accounting Sales and Expense transactions fail

### ISSUE THREAD

**Issue by heretiq** [wp-erp/wp-erp#410]
We are experiencing a "Couldnotcreatetransaction" error message with every sales and expenses transaction we enter into WP ERP. This occurs with the following Accounting transactions:

- Sales (Payment and Invoice) 
- Expenses (Payment Voucher and Vendor Credit) 

We have ruled out the following:
- theme conflict: the error occurs with the Wordpress 2017 theme as well;  
- browser issue: the issue occurs on multiple browsers on Mac and Windows;
- javascript issue: there are no errors or warnings shows in the browser console.

Please see attached screenshot.

![sales_transaction_error](https://cloud.githubusercontent.com/assets/230799/22848981/523e2324-efbe-11e6-88fa-92faf40843ff.jpg)

**Comment by heretiq** [comment]
PING!

**Comment by ediamin** [comment]
fixed from wperp.com support channel
