### ISSUE TITLE
Graphs are not updating (Accounting -> Sales)

### ISSUE THREAD

**Issue by shawon786** [wp-erp/wp-erp#411]
No changes occurred after several transactions.

For clarification, see the screenshot:
http://prntscr.com/e7be8q

**Comment by ashique12009** [comment]
There are 3 state transactions are not inserted in calculation, and they are:
1. void
2. draft
3. awaiting for approval
So, in your screenshot i am watching $700 is in awaiting for approval.
So it won't come to calculation or won't update the graph.
