### ISSUE TITLE
"HR Manager" role always remains checked in the permission section 

### ISSUE THREAD

**Issue by shawon786** [wp-erp/wp-erp#413]
If you uncheck the permission of an employee, it shows as uncheck after saving. But if you uncheck "HR Manager", then it remains checked after saving. 

But there is a point to notice. That is, it's working fine functionally. In the "users" tab this employee does not get the permission of  "HR Manager" if he is unchecked there on the permission tab.

**Comment by sultann** [comment]
Fixed #413
