### ISSUE TITLE
Dynamic Life Stages Display Issues

### ISSUE THREAD

**Issue by heretiq** [wp-erp/wp-erp#423]
Thank you for the quick reply and fix for Issue #422 @ediamin. Your commit fixed the hard-coded life stages issue; however there are two remaining display issues:

1. The height of the Dashboard Contacts and Companies summaries assume that only four life stages will be used. So, when a fifth life stage is added, it is partially cut off because the container heights stay fixed.

2. The Dashboard Recently Added sidebar widgets display the custom life stages incorrectly: It shows the $life_stages array index/key and not the array value.

Here is the plugin code segment that uses the 'erp_crm_life_stages' filter to return the custom life stages array ($life_stages):

```php
// Core Plugin Function 
function customize_wperp_crm_life_stages( $life_stages ) {
	$life_stages = [
        'stage1'	=> __( get_option('crm_life_stage_1'), 'wp-erp' ),
        'stage2'	=> __( get_option('crm_life_stage_2'), 'wp-erp' ),
        'stage3'	=> __( get_option('crm_life_stage_3'), 'wp-erp' ),
        'stage4'	=> __( get_option('crm_life_stage_4'), 'wp-erp' ),
        'stage5'	=> __( get_option('crm_life_stage_5'), 'wp-erp' )
    ];
    return $life_stages;
}
add_filter( 'erp_crm_life_stages', 'customize_wperp_crm_life_stages' );
```

Please see attached screenshot showing both of these issues.
![crm-dashboard-dynamic-life_stage-issues](https://cloud.githubusercontent.com/assets/230799/24070289/333c7314-0b88-11e7-931e-37f4204fd01d.jpg)

Please advise on the recommended way to address these issues.

Thanks!

**Comment by ediamin** [comment]
@heretiq please pull the latest changes from develop branch. It should be fixed by now. Thank you very much for reporting this issue.

**Comment by heretiq** [comment]
@ediamin your'e welcome. Commit [b9e1d7d](https://github.com/wp-erp/wp-erp/commit/b9e1d7d837cbc080a08201239f174af0d97609b3) corrected both issues. Thank you very much for your responsiveness and efficiency! Your dynamic life stages fixes now enable a very important enhancement to WP-ERP CRM: I can now use my WP ERP CRM Custom Life Stages plugin to further customize WP-ERP CRM for clients. Thanks again.
