### ISSUE TITLE
CRM Meetings Bugs and UX Issues

### ISSUE THREAD

**Issue by xcentric-solutions** [wp-erp/wp-erp#425]
WP-ERP rocks! Here are some bugs and UX issues that when fixed will make it even more awesome!

The WP-ERP CRM Schedules has the following bugs and usability issues:

## Bugs:
1. Editing a Meeting automatically resets meeting time to 12:00am (00:00)
2. Editing a meeting only allows the start time to be changed -- you can not change meeting end time
![crm edit meeting issues](https://cloud.githubusercontent.com/assets/230799/24121203/7acb307c-0d85-11e7-8be6-5b5f440f250d.jpg)

3. Edited meetings will not render on meeting detail popup on either CRM Overview or Schedules calendar -- the popup is displayed and the activity indicator is displayed but the details are never rendered 
![crm overview meeting detail popup not rendering](https://cloud.githubusercontent.com/assets/230799/24121216/877372ee-0d85-11e7-8894-847065a6a185.jpg)

## Usability Issues:
1. Meetings can only be edited from the company or contact activity logs -- it should be possible to trigger meeting editing view from any place a meeting is displayed (CRM Overview/Schedules calendar, Activities, meeting details popup, etc.
2. The Meeting Creation view has several UX issues (It is not possible to type in data or time though this is preferable to the sliders, sliders are unintuitive, no AM/PM indication on slider invites errors, errors are only visible after meeting is created and fixing those errors is problematic due to the bugs reported above.)  
![crm meeting creation ux issues](https://cloud.githubusercontent.com/assets/230799/24121742/65ee547a-0d87-11e7-8126-362de9df9af6.jpg)

**Comment by sultann** [comment]
Resolved.
