### ISSUE TITLE
Changing CRM Contact Email Can Overwrite Existing Admin User Details

### ISSUE THREAD

**Issue by xcentric-solutions** [wp-erp/wp-erp#426]
In CRM, changing a Contact Email to an existing email overwrites the existing user account with the edited CRM contact details. This occurs silently so if you erroneously enter an existing email address while editing a contact you will lost the original account details without any indication. 

Example:

## Example Accounts
A: Existing Account: Admin account with abc@def.com email
B: Existing CRM contact 

## How to Reproduce Bug
1. Edit CRM Contact B and change contact email to abc@def.com
2. Save changes
3. View admin account A -- notice Admin account details are overwritten by CRM Contact account details 

This should not be allowed to occur without explicit user consent. In fact, it probably should not be allowed under any circumstances.

**Comment by sultann** [comment]
Fixed
