### ISSUE TITLE
Redirect employees to WooCommerce my-account page after login

### ISSUE THREAD

**Issue by shawon786** [wp-erp/wp-erp#433]
If WooCommerce plugin is activated while WP ERP is in use, 
it won't redirect employees to the dashboard (backend). It redirects them to "my-account" page of WooCommerce.

**Comment by ediamin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix wp-erp issue#433](https://trello.com/c/B5djNUBw/4-fix-wp-erp-issue-433)
