### ISSUE TITLE
Leave Request to "reporting employee"

### ISSUE THREAD

**Issue by shawon786** [wp-erp/wp-erp#435]
Whenever an employee applies for a leave it should also go to the reporting employee/lead for approval. 
Both the admin and reporting employee should have the approval permission.

**Comment by tareq1988** [comment]
I don't think it's a good idea and can be implemented.

The reporting employee can get a notification about the application, but not the approval decision should be upon the reporting employee. Only the HR admin can do that.

**Comment by shawon786** [comment]
Great point!
Then we may add a feature like- 
"Reporting employee" will get a notification about the leave request. But he will not be able to approve or reject that. But he will be notified of the approval or rejection."

**Comment by tareq1988** [comment]
It doesn't have to have any notice. If the admin turns a checkbox *ON*, we could send a notification to the reporting employee as well.

**Comment by ediamin** [comment]
Introduced a new hook `erp_new_leave_request_notification_recipients` to add any user or user role in the notification recipients list. Admin can make a custom plugin to implement this feature. 
Closed via 03e5ee5b43345
