### ISSUE TITLE
Leave request status colors CSS

### ISSUE THREAD

**Issue by iShubhamRaj** [wp-erp/wp-erp#458]
Leave request status colors would make more sense when the **pending** status is in yellow and **rejected** status is in red.
Sort of like traffic signals. Currently they are swapped.
Though its just my opinion. I thought this would make more sense while reading the status. 😅 

Currently it is like this:
![requests](https://cloud.githubusercontent.com/assets/5956116/26031698/b8d08bca-389a-11e7-8103-b8a903653d67.png)

**Comment by ediamin** [comment]
@iShubhamRaj nice catch. I'll fix it in next release.
