### ISSUE TITLE
Footer is not included in the emails sent from CRM -> Contacts

### ISSUE THREAD

**Issue by shawon786** [wp-erp/wp-erp#466]
I am trying to set up the email footer for sending out emails via your crm.
Everything works fine with IMAP settings. I can send and receive emails.
Only the footer (ERP Settings > Email > Footer text ) is not attached.

**Comment by ediamin** [comment]
At the moment, only the notification emails found in `Settings > Emails > General` will include this footer. You can use an email template to solve this problem.
