### ISSUE TITLE
Who is Out Section shows past dates which have already been completed

### ISSUE THREAD

**Issue by mainul11** [wp-erp/wp-erp#468]
This section shows the leaves which have been completed already. In the screenshot, it is showing previous days of leaves such as June 1, 5, 6 whereas its already 8th June. Only upcoming dates should be shown here. showing previous leaves may confuse other employees.
![hrm prob](https://user-images.githubusercontent.com/20102452/26910306-c607374e-4c27-11e7-99dd-4598771c23be.png)

**Comment by ediamin** [comment]
closes via a0d3235e4dd0f626588fc5bbca2a39eaf8d752a5
