### ISSUE TITLE
Accounting: Issue with invoice link in Arabic 

### ISSUE THREAD

**Issue by shawon786** [wp-erp/wp-erp#490]
## Invoices links have RTL issues see:
http://staff.mte.sa?query=readonly_invoice&trans_id=164&auth=387b5c799ca92152531d9489d706d1ecc707a110c57327e7731d71e66a63a07a

The correct form of this in Arabic is RTL direction of body tag and right alignment for columns.

**Comment by thebengalboy** [comment]
Hello @shawon786

This issue should be fixed with our latest version 1.5.4. Please check it once again.

Thanks
