### ISSUE TITLE
Not able to update Department, designation in work section after added the employee

### ISSUE THREAD

**Issue by arvindkutty** [wp-erp/wp-erp#492]
![screenshot-192 168 10 40-2017-08-10-10-02-00](https://user-images.githubusercontent.com/30592456/29154649-8d426790-7db3-11e7-9792-31a6c88975b0.png)
![screenshot-192 168 10 40-2017-08-10-10-05-21](https://user-images.githubusercontent.com/30592456/29154648-8d414568-7db3-11e7-891e-a1e0ef643309.png)

**Comment by mainul11** [comment]
Hi arvindkutty,

You can edit the work details including departments, designations etc. from Employee Profile → Jobs Tab → Job Information Section → Update Job Information
Please see the attached screenshot. 
Thank you
![screenshot_1](https://user-images.githubusercontent.com/20102452/29155206-1efeba6e-7dbc-11e7-8914-758eae788a76.png)

**Comment by mathetos** [comment]
I came here to create this issue, but I see your suggested way to update that information above and it does work as you describe. I think though that this is not intuitive at all. 

It's most intuitive to update the information in the same place you created the employee.

But, if you don't prefer to have the Designation or other job role specific information in the same place then it would be helpful to the user to have an inline notice in the Employee popup that links them to the Employee Profile to update those settings. I think it would also be beneficial to at least be able to SEE those fields there, even if they are set to read only. 

That would be my suggestion: when updating an employee from the popup, have all the same fields visible, but the ones you want edited on the Profile page set to "read-only" and have a description below those fields saying "Job Designations and other role-specific fields can be edited [here](https://example.com/wp-admin/admin.php?page=erp-hr&section=employee&action=view&id=12&tab=job)

**Comment by thebengalboy** [comment]
Hello @mathetos 

The UI need to be enhanced, we can feel as well. However, we have a plan to bring a brand new UI in the near future.

Thanks and your suggestion has been noted :)
