### ISSUE TITLE
BUG: Rest API, Contacts life_stage returns 'null'

### ISSUE THREAD

**Issue by Frankniesten** [wp-erp/wp-erp#507]
If I request a contact trough the REST api (/wp-json/erp/v1/crm/contacts/177). In the response the life_stage is always 'null'.

{
    "id": 177,
    "first_name": "Madisen",
    "last_name": "Nienow",
    "email": "tHarvey@gmail.com",
    "company": "",
    "phone": "517.709.8784",
    "mobile": "",
    "other": "",
    "website": "http://www.Runolfsson.com/",
    "fax": "",
    "notes": "",
    "street_1": "6143 Jan Valleys Suite 827",
    "street_2": "",
    "city": "Yadiraland",
    "state": "FL",
    "postal_code": "97214",
    "country": "US",
    "currency": "ILS",
    "types": [
        "contact"
    ],
    "user_id": 0,
    **"life_stage": null,**
    "_links": {
        "self": "wp-json/erp/v1/crm/contacts/177",
        "collection": "/wp-json/erp/v1/crm/contacts"
    }
}

**Comment by sultann** [comment]
Fixed
