### ISSUE TITLE
Unable to delete Leave Requests

### ISSUE THREAD

**Issue by arvindkutty** [wp-erp/wp-erp#513]
Not able to delete the Leave Requests. Please have a look at it.
![screenshot-192 168 10 31-2017-09-12-10-33-05](https://user-images.githubusercontent.com/30592456/30308948-1e05b7ee-97a6-11e7-9856-d1dd849a11d9.png)

**Comment by shawon786** [comment]
@arvindkutty ,
Are you using any plugin for permission/user role management?

**Comment by arvindkutty** [comment]
Yes...

**Comment by shawon786** [comment]
@arvindkutty 
This plugin could be a reason as these types of plugin overrides the roles (or some capabilities under a role) most of the time. Try WP ERP without using this role management plugin and hope everything will work perfectly.
