### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by monogios** [wp-erp/wp-erp#537]
The limitation of attaching files or receiving attached files makes the CRM plugin hard or even impossible to use.

**Comment by shawon786** [comment]
@monogios,
Could you please tell us some points that makes CRM module useless to you?
That will be great and very helpful.

Thanks :)

**Comment by monogios** [comment]
@shawon786, here is an everyday scenario, which I believe will also fit lots of businesses:

We create PDF quoatation using our Accounting software and we attach them to our conversation with the client. The client then has to print and sign the quotation to show his/her acceptance and email us back the scanned file.

**Comment by shawon786** [comment]
@monogios,

Thanks for describing the scenario.
I can understand your needs. Just listed this feature for future development. 
We'll surely try to bring it in WP ERP -> CRM module in future.

Good day :)

**Comment by monogios** [comment]
Thanks for the prompt reply.

Hope this feature will be released soon as you have an overall excellent CRM app.

**Comment by advertiseit** [comment]
+1 

I agree. CRM attachments and documents are must haves. I have a client that would like to complete  job and credit applications and have attached to contacts. Even if it's attaching form Data from WeForms or Gravity Forms.
