### ISSUE TITLE
Mass mail

### ISSUE THREAD

**Issue by Ninos** [wp-erp/wp-erp#549]
Hey there,
I'm missing a feature to send mass mails to contacts.

- Admins should be able to send mass mails to contacts defined by a list with filtering functionality (allow a multiple groups, disable some groups, select specific contacts...)
- In the mass mail module variables and statements should be possible, e.g. {if gender=male lastname!=empty}Dear Mr. {lastname}{elseif gender=female lastname!=empty}Dear Miss {lastname}{else}Dear Sir or Madam{endif}
- Allow some users to send mass mails to just a specific group (or more) + vise versa, e.g. leads to their employee
- Mass mails should be sent by an interval to avoid spam rating (possible to define on options page)
- User should be able to select email account defined by admin or itself
  - Admin should be able to define multiple email accounts for each group
  - User should be able to define multiple email accounts for itself

Would be awesome if you could implement such functionality.

**Comment by shawon786** [comment]
Hi,

We have an extension named "Email Campaign" with these features. 
You may have a look at it here- https://wperp.com/downloads/wp-erp-email-campaign/

Thanks :)

**Comment by Ninos** [comment]
Oh nice, thx. So just some functionality is missing:
- Select specific users or groups (I would use select2 for that instead of checkboxes for the current group lists)
- In the mass mail module variables and statements should be possible, e.g. {if gender=male lastname!=empty}Dear Mr. {lastname}{elseif gender=female lastname!=empty}Dear Miss {lastname}{else}Dear Sir or Madam{endif}
- Allow some users to send mass mails to just a specific group (or more) + vise versa, e.g. leads to their employee
- User should be able to select email account defined by admin or itself (e.g. only smtp-accounts are possible, to avoid abuse)
  - Admin should be able to define multiple email accounts for each group
  - User should be able to define multiple email accounts for itself
- Template for regular emails is missing (email should look like an individual mail written e.g. via thunderbird)

**Comment by Ninos** [comment]
Oh nice, thx. So just some functionality is missing:
- Select specific users or groups (I would use select2 for that instead of checkboxes for the current group lists)
- In the mass mail module variables and statements should be possible, e.g. {if gender=male lastname!=empty}Dear Mr. {lastname}{elseif gender=female lastname!=empty}Dear Miss {lastname}{else}Dear Sir or Madam{endif}
- Allow some users to send mass mails to just a specific group (or more) + vise versa, e.g. leads to their employee
- User should be able to select email account defined by admin or itself (e.g. only smtp-accounts are possible, to avoid abuse)
  - Admin should be able to define multiple email accounts for each group
  - User should be able to define multiple email accounts for itself
- Template for regular emails is missing (email should look like an individual mail written e.g. via thunderbird)

**Comment by Ninos** [comment]
Hey @sultann why was this ticket closed?

**Comment by sultann** [comment]
@Ninos,
1. You can create a group and select specific contacts or segment.
2. You can use our email campaign extension for the custom template and send emails https://wperp.com/downloads/wp-erp-email-campaign/
3. You can customize any kind of email template from the email settings section

So, considering those we have planned not to duplicate features.

**Comment by Ninos** [comment]
@sultann Are all the functions listed above possible? I don't think so. It would be awesome if you could enhance your massmail plugin, otherwise it's not usable.
