### ISSUE TITLE
WooCommerce integration

### ISSUE THREAD

**Issue by Ninos** [wp-erp/wp-erp#550]
Wanted to ask you how much woocommerce is integrated into wp-erp. I recommend following:

- [ ] Use WC customer database for contacts instead of own table + extend
- [ ] Use WC gateways instead of own once
- [ ] Instead of own invoice plugin I recommend adding functionality to woocommerce, also the woocommerce subscription module could be interesting for you
- [ ] Sync woocommerce membership (plugin) users to an own contacts group + possibility to define leads to that group

Kindest regards

**Comment by advertiseit** [comment]
+1 for each one of those.

**Comment by thebengalboy** [comment]
Hello @Ninos 

We are not considering this at this moment as it doesn't match with our core philosophy. Not all of our users are using WooCommerce and hence, if someone doesn't have WooCommerce, there'd not be a option to save the contacts.

Thanks

**Comment by Ninos** [comment]
You could add an additional plugin for such integration (e.g. sync wp-erp contacts with woocommerce).
