### ISSUE TITLE
CalDAV & CardDAV (Sync between Contacts & Calendars of smartphones to make CRM handier)

### ISSUE THREAD

**Issue by Ninos** [wp-erp/wp-erp#563]
Hey there,
lots of companies want to sync contacts (to which employee has access) and calendars (to which employee has access) to the smartphones or mail client of their employees.

I hope to see such functionality implemented into wp-erp.

**Comment by advertiseit** [comment]
+1

**Comment by shawon786** [comment]
@Ninos 
Thanks a ton for your suggestion. I've added it to our future log and will surely try to bring this feature in near future.

**Comment by sultann** [comment]
We can not do this syncing directly with smartphones as we do not have any mobile apps yet. But we will have a way so, you can sync your calendar and contacts with WP ERP plugin soon.

**Comment by Ninos** [comment]
@sultann huh? You just need to implement CalDAV & CardDAV into your plugin. No app is needed here. Than the synchronisation can be done by various apps available in the app stores....

I lose hope in this ERP system. You're closing all relevant tickets for plugin improvements in enterprise environment.

**Comment by dotancohen** [comment]
CardDAV is a standard, so whether or not wp-erp has its own apps is irrelevant. Implement CardDAV, then if you still see the need create an app.
