### ISSUE TITLE
Feature: Leave in advance for next year

### ISSUE THREAD

**Issue by shawon786** [wp-erp/wp-erp#567]
The ability to have leave policies for the next year is a must-have feature. 
Most people book their holiday at least a few months in advance. So if anyone wants to book a leave in January, he has to apply for it in December at least.

**Comment by shawon786** [comment]
http://prntscr.com/i9uyz4

**Comment by thebengalboy** [comment]
The feature will come with our upcoming leave management system. This has planned already.
