### ISSUE TITLE
Schema "wp_erp_crm_save_search" not included

### ISSUE THREAD

**Issue by sohelamin** [wp-erp/wp-erp#58]
Schema/Table "wp_erp_crm_save_search" doesn't exists in installation class or anywhere.
<img width="1109" alt="screen shot 2016-03-09 at 9 22 41 pm" src="https://cloud.githubusercontent.com/assets/1708683/13639968/4d738bb2-e63d-11e5-9ba4-5b7ad9210f16.png">

**Comment by sabbir1991** [comment]
Issue resolved :+1:
