### ISSUE TITLE
CRM E-mail functions (Capability of sending emails from several addresses)

### ISSUE THREAD

**Issue by shawon786** [wp-erp/wp-erp#612]
Currently, all E-mails go through ONE Email address. However, we have several users/representatives and they have their own E-mail address and their own contacts.
When a contact receives an E-mail from us, they only see system E-mail address. We would prefer that our representative's Email address is shown to customers instead of system E-mail address.
Is there a better practice where our contacts can reply E-mails to “representative's E-mail address” ?
We wish for an Mail Client integrated with your CRM, where all correspondences between customers and our representatives can still be archived and retrieved from CRM activities.
Can you please consider this important feature in your next update? Since we have purchased WPERP and extensions. We would really like it to integrate into our work.

**Comment by advertiseit** [comment]
+1

**Comment by sultann** [comment]
As we are using SMTP for all mail outgoing and have mail inbound feature. So, technically we cant do that.

**Comment by advertiseit** [comment]
Why not? Just about every CRM allows separate SMTP settings for each user. There’s really no technical reason it can’t be done.
