### ISSUE TITLE
error in menu wordpress

### ISSUE THREAD

**Issue by katusoftware** [wp-erp/wp-erp#621]
for some reason it is crushing the appearance and plugin menu in the wordpress sidebar when activated

![old](https://user-images.githubusercontent.com/36487221/36223286-ee4b6ec0-1191-11e8-8079-ace2eac600bc.jpeg)

![after](https://user-images.githubusercontent.com/36487221/36223283-e98bcb3c-1191-11e8-8d68-c4c2137aca65.jpeg)

**Comment by shawon786** [comment]
@katusoftware 

Sorry for this inconvenience. Just tried on a live site. But I didn't see something like this.
Could you please contact us [here](https://wperp.com/contact/) with temporary login details?
We'd like to have a closer look at your site and find out the reason behind this.

Thanks for your cooperation :)

**Comment by shawon786** [comment]
@katusoftware 
Have you managed to fix it yet?
Waiting for your response so that we can help!

**Comment by shawon786** [comment]
@katusoftware 
As you did not respond in last 13 days, I hope that you've already found the reason behind this.
Feel free to inform us if not!

Thanks :)
