### ISSUE TITLE
Accounting Module Sales Feature - Filter Labels Are Not Working Correctly

### ISSUE THREAD

**Issue by rounakahmed** [wp-erp/wp-erp#632]
None of the Filter Labels (Except Draft) are showing the right numbers in brackets.

There are more invoices under each Filter than the Labels show.

Please check the screenshots attached.

![screenshot_2](https://user-images.githubusercontent.com/36122952/36942687-74d460e0-1fa3-11e8-95a5-9f4a7b501e76.png)
![screenshot_3](https://user-images.githubusercontent.com/36122952/36942710-cfbb0c7a-1fa3-11e8-8e4c-9d616978ee1f.png)

**Comment by shawon786** [comment]
@rounakahmed apu,
This can only happen if and only if someone deletes a customer from the database who is involved with any transaction already. By default, WP ERP won't allow you to delete a customer involved with any transaction. You should get an error message if you try to do so. 

If you look at the transactions closely, you will notice that some customers are not available on the customer list (Accounting -> Customer). It means somehow the customers were deleted from the database and that is the only reason behind this issue!

Thank you :)
