### ISSUE TITLE
Currency choice in setup wizard does not work.

### ISSUE THREAD

**Issue by rasmuserik** [wp-erp/wp-erp#651]
How to reproduce: Go through the setup wizard after a new install, choose other currency that USD (in this case Danish Krone). Currency in ERP-settings is still USD after install.

Minor issue, as you can easily configure the currency after the install, - but impact impression of wp-erp when the wizard does not work as expected.

**Comment by shawon786** [comment]
@rasmuserik 
Thanks for such great notice and let us know!
We will surely look into this.

Best regards :)
