### ISSUE TITLE
All CRM agents are getting access to entire customer database on WP-ERP CRM

### ISSUE THREAD

**Issue by ssgaindia** [wp-erp/wp-erp#653]
Hi,

I dont want my CRM Agents access customer database created by CRM Managers. Is there a way I can restrict their view or access.

Requesting help!

**Comment by shawon786** [comment]
@ssgaindia 
By default, there is no way to restrict the access. In that case, you will need to customize the permission of agents.

Thanks!

**Comment by ssgaindia** [comment]
Thanks Sharon.

Can we customize the permission of agents using WP-ERP admin panel in
WordPress or do we require to write additional codes in the editor.

Regards
SSGA


On 22 Apr 2018 8:57 am, "Shawon Chowdhury" <notifications@github.com> wrote:

@ssgaindia <https://github.com/ssgaindia>
By default, there is no way to restrict the access. In that case, you will
need to customize the permission of agents.

Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wp-erp/wp-erp/issues/653#issuecomment-383352479>, or mute
the thread

**Comment by shawon786** [comment]
@ssgaindia 
Yes, you will need to write additional codes in the core.

Thanks :)
