### ISSUE TITLE
How do I clean out currently existing entries from the database?

### ISSUE THREAD

**Issue by OyeBenny** [wp-erp/wp-erp#654]
pls

**Comment by shawon786** [comment]
@OyeBenny 
This simple plugin will help you to clean the database-
https://github.com/wp-erp/erp-cleaner


Thanks!

**Comment by OyeBenny** [comment]
I'm not looking to destroy everything. I just want to clear all my journal entries.

**Comment by shawon786** [comment]
@OyeBenny, 
This table "erp_ac_journals" records all Journal entries. 
So you can make this table **empty** to clear the journal entries. 

Thanks!
