### ISSUE TITLE
Error: Payment amount is more than Due!

### ISSUE THREAD

**Issue by mehroz1** [wp-erp/wp-erp#659]
Hello,

I have recently encountered another error while reciving payment on an invoice. I generated a test invoice of 9,821,498.00. When I tried to recieve payment of 600,000 it says 

> Error: Payment amount is more than Due!

I am attaching screen shot of the issue.

![wp-erp-bug-2](https://user-images.githubusercontent.com/9348863/40541826-e8275ca4-6036-11e8-807b-80470c2a25bd.jpg)

**Comment by shawon786** [comment]
@mehroz1 
Thanks for such great notice!
We are working on this and soon it will be fixed.

Cheers!

**Comment by mehroz1** [comment]
actually i have found and fixed this on my local instance.. and still trying to fix the issue when we recieve payments for multiple invoices as you can see in the image below while also showing total remaining payments (that needs to paid in future) on invoice.

![wp-erp-work-inprogress](https://user-images.githubusercontent.com/9348863/40603654-fd11efb2-6275-11e8-9d6e-4c317ed692f4.jpg)

**Comment by shawon786** [comment]
@mehroz1 
Have you tried downloading the developed version from our git repo? 
You can also make the changes in the following file on your local-
https://github.com/wp-erp/wp-erp/commit/48b1b4063a882087a659a087490d45affc4c1ca4

Please let me know if you are still facing the same :)

**Comment by mehroz1** [comment]
No i haven't got chance to do that. But that file was patched soon after i posted this bug

i have temporarly resolved it by replacing it with following code: 

```
var totalPay = $('#price_total').val();
totalPay     = totalPay.replace(/\,/g, '');
totalPay     = totalPay.replace(ERP_AC.decimal_separator, '.');

var totalDue = $('#total_due').val();
totalDue     = totalDue.replace(/\,/g, '');
totalDue     = totalDue.replace(ERP_AC.decimal_separator, '.');
```
