### ISSUE TITLE
Accounting: Incorrect Status of Invoices After Reciving Payment and Deleting Payment Entry

### ISSUE THREAD

**Issue by mehroz1** [wp-erp/wp-erp#660]
Hello,

I have caught another issue when we recieve payment from a customer which have multiple invoices with "Awating Payments" status. The status of other invoices for which we have set 0.00 Amount changes to "Partially Paid" which is incorrect if someone has not deleted the row and changed the value to 0 then the status of those invoices should not be updated . As showen in the images below: 
![wp-erp-work-inprogress-3](https://user-images.githubusercontent.com/9348863/40607447-025d5dd8-6282-11e8-8f08-bb6c395ea7e3.jpg)
![wp-erp-work-inprogress-4](https://user-images.githubusercontent.com/9348863/40607448-0298073a-6282-11e8-94bd-3c128d6af336.jpg)

Similarly when I void the payment entry or delete it entirely. It should update the status of involved invoices appropriately. Explained in image below:

After Voiding:
![wp-erp-work-inprogress-5](https://user-images.githubusercontent.com/9348863/40607748-d213ca6c-6282-11e8-9afd-cb7d5bed2af6.jpg)

After Deletion:
![wp-erp-work-inprogress-7](https://user-images.githubusercontent.com/9348863/40607953-61b8b3c6-6283-11e8-919c-66b0c7d33ba2.jpg)

**Comment by shawon786** [comment]
@mehroz1 
Thanks for pointing out the issues.
The first one is logged as an issue and we will fix this.

Regarding the second and third-
In the developed version I am not facing things like you mentioned! Please clone or download the latest developed version and have a try.

Regards :)

**Comment by mehroz1** [comment]
Ok i will test it again on separate instance with new package from github as i have made some major changes in my package since this tickets was opened.

**Comment by shawon786** [comment]
@mainul11 
Are you still facing these problems?
Please update us.

Thanks :)

**Comment by thebengalboy** [comment]
This has been fixed with the new accounting.
