### ISSUE TITLE
Fetal Error

### ISSUE THREAD

**Issue by princ-imran** [wp-erp/wp-erp#675]
Do not find vendor file...After install vendor..
Fatal error: Uncaught Error: Class 'WeDevs\ERP\Admin\Form_Handler' not found in C:\laragon\www\test\wp-content\plugins\wp-erp-develop\includes\admin\class-admin.php:48 Stack trace: #0 C:\laragon\www\test\wp-content\plugins\wp-erp-develop\includes\admin\class-admin.php(11): WeDevs\ERP\Admin\Admin_Page->init_classes() #1 C:\laragon\www\test\wp-content\plugins\wp-erp-develop\includes\admin\class-admin.php(221): WeDevs\ERP\Admin\Admin_Page->__construct() #2 C:\laragon\www\test\wp-content\plugins\wp-erp-develop\wp-erp.php(229): require_once('C:\\laragon\\www\\...') #3 C:\laragon\www\test\wp-content\plugins\wp-erp-develop\wp-erp.php(120): WeDevs_ERP->includes() #4 C:\laragon\www\test\wp-content\plugins\wp-erp-develop\wp-erp.php(92): WeDevs_ERP->setup() #5 C:\laragon\www\test\wp-content\plugins\wp-erp-develop\wp-erp.php(335): WeDevs_ERP::init() #6 C:\laragon\www\test\wp-content\plugins\wp-erp-develop\wp-erp.php(339): wperp() #7 C:\laragon\www\test\wp-admin\includes\plugin.php(1897): include('C:\\laragon\\www\\...') #8 C:\laragon in C:\laragon\www\test\wp-content\plugins\wp-erp-develop\includes\admin\class-admin.php on line 48

**Comment by shawon786** [comment]
@princ-imran 
Have you downloaded WP ERP from WordPress.org (https://wordpress.org/plugins/erp/)? 

But if you've downloaded it from our git repo, then you need to run two additional command-
1. composer install & 2. composer dump -o

Thanks :)

**Comment by princ-imran** [comment]
Hello sir,
Already install.
 but now Fatal error: Class 'WeDevs\ORM\Eloquent\Model' not found in C:\laragon\www\test\wp-content\plugins\wp-erp-develop\includes\framework\Model.php on line 10

**Comment by shawon786** [comment]
@princ-imran 
This seems unfortunate!
Please contact our support (www.wperp.com/contact) and our technical team will help you with it.

Thanks :)
