### ISSUE TITLE
Unable to use email address with (') 

### ISSUE THREAD

**Issue by shawon786** [wp-erp/wp-erp#686]
We recently ran into an issue where users were unable to enter an email address containing an apostrophe (') into the contact form in the CRM module (eg. tom.o'malley@test.com).

The message "Please provide a valid email address" pops up instead.

While uncommon, email addresses containing apostrophes before the @ are valid.

**Comment by rafsuntaskin** [comment]
Email addresses containing apostrophes are not valid in general. Neither gmail or WordPress supports emails with this character. 

This is the warning from gmail. And we are using built in WP function `is_email` to validate emails.

<img width="432" alt="screen shot 2018-08-06 at 11 57 10 am" src="https://user-images.githubusercontent.com/7523321/43699292-071711e6-9970-11e8-89d9-67beb28c290a.png">

Thanks
