### ISSUE TITLE
How to add CRM Life Stages to CRM Reports!?

### ISSUE THREAD

**Issue by WarenGonzaga** [wp-erp/wp-erp#706]
This one helps me a lot to add custom stages...
https://github.com/wp-erp/wp-erp/wiki/CRM-Filters

But the problem is I can't see them on reporting... anyone know how to do this right?
How to include it on the reporting? Thanks!

**Comment by thebengalboy** [comment]
Hello @WarenGonzaga 

It might not be possible to have the custom stages on the reporting by default at this moment. However, I'll try this and let you know an update :)

Thanks

**Comment by WarenGonzaga** [comment]
@thebengalboy that's awesome! Thank for the response!
