### ISSUE TITLE
Error in activating this commit 2d18505

### ISSUE THREAD

**Issue by edmonaft** [wp-erp/wp-erp#714]
It says:

Plugin could not be activated because it triggered a fatal error.

Fatal error: Uncaught Error: Class ‘WeDevs\ERP\CRM\Google_Auth’ not found in C:\xampp\htdocs\wp-content\plugins\erp\wp-erp.php:260 Stack trace: #0 C:\xampp\htdocs\wp-content\plugins\erp\wp-erp.php(123): WeDevs_ERP->instantiate() #1 C:\xampp\htdocs\wp-content\plugins\erp\wp-erp.php(92): WeDevs_ERP->setup() #2 C:\xampp\htdocs\wp-content\plugins\erp\wp-erp.php(337): WeDevs_ERP::init() #3 C:\xampp\htdocs\wp-content\plugins\erp\wp-erp.php(341): wperp() #4 C:\xampp\htdocs\wp-admin\includes\plugin.php(1897): include(‘C:\\xampp\\htdocs…’) #5 C:\xampp\htdocs\wp-admin\plugins.php(178): plugin_sandbox_scrape(‘erp/wp-erp.php’) #6 {main} thrown in C:\xampp\htdocs\wp-content\plugins\erp\wp-erp.php on line 260

**Comment by rafsuntaskin** [comment]
Looks like you are using the develop version from Github. Please make sure you run composer install to install all dependencies.

**Comment by edmonaft** [comment]
hi @rafsuntaskin,

May i know how to run it under xampp on Windows?

Thank you.

**Comment by rafsuntaskin** [comment]
You need to have composer installed if you want to run this. Or you can simply download the stable zipped version from [WordPress](https://wordpress.org/plugins/erp/).

**Comment by edmonaft** [comment]
I've installed composer.
I've CD'ed to the downloaded wp-erp in github on my downloads folder
I've run composer install, this is the result.
I don't know the next step though (or if i did it correctly)
![image](https://user-images.githubusercontent.com/37152971/46863387-e1bd1580-ce49-11e8-8c1f-78525ab93387.png)

**Comment by edmonaft** [comment]
It is still the same though when i activated this latest github build :-(

![image](https://user-images.githubusercontent.com/37152971/46863716-b129ab80-ce4a-11e8-988c-ada8cee6f3da.png)

**Comment by edmonaft** [comment]
I tried the latest commit 5462bf5. I am getting these errors still:

Fatal error: Uncaught Error: Class 'WeDevs\ERP\CRM\Google_Auth' not found in C:\xampp\htdocs\wp-content\plugins\erp\wp-erp.php:260 Stack trace: #0 C:\xampp\htdocs\wp-content\plugins\erp\wp-erp.php(123): WeDevs_ERP->instantiate() #1 C:\xampp\htdocs\wp-content\plugins\erp\wp-erp.php(92): WeDevs_ERP->setup() #2 C:\xampp\htdocs\wp-content\plugins\erp\wp-erp.php(353): WeDevs_ERP::init() #3 C:\xampp\htdocs\wp-content\plugins\erp\wp-erp.php(357): wperp() #4 C:\xampp\htdocs\wp-admin\includes\plugin.php(1897): include('C:\\xampp\\htdocs...') #5 C:\xampp\htdocs\wp-admin\plugins.php(178): plugin_sandbox_scrape('erp/wp-erp.php') #6 {main} thrown in C:\xampp\htdocs\wp-content\plugins\erp\wp-erp.php on line 260

**Comment by rafsuntaskin** [comment]
Please download from [this](https://github.com/wp-erp/wp-erp/releases/download/v1.4.0/erp-v1.4.0.zip) . It has the dependencies zipped within it.
