### ISSUE TITLE
State field dropdown is empty on the Employee address

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#723]
'State' field doesn't work on the Employee address or adding Employee form. Suppose, you have selected USA as a country, and then you need to select the state but the dropdown is empty.

Thanks

**Comment by mehroz1** [comment]
Covering states for every country would be difficult and lengthy task. I recommend state drop down should be replaced by a text field.

**Comment by thebengalboy** [comment]
@rafsuntaskin The issue persists yet on the Accounting-> Customers-> Create new customer-> http://prntscr.com/lh7idf

Please fix this as well. Thanks
