### ISSUE TITLE
HR: Though the user is on leave, it's not showing on the widget.

### ISSUE THREAD

**Issue by tareq1988** [wp-erp/wp-erp#726]
Related to #587 

![screen shot 2018-11-19 at 2 25 29 pm](https://user-images.githubusercontent.com/153669/48694895-cfcc5080-ec07-11e8-8212-652ca1f376f4.png)
![screen shot 2018-11-19 at 2 31 01 pm](https://user-images.githubusercontent.com/153669/48694903-d3f86e00-ec07-11e8-9b05-7524fc7c4b4f.png)

**Comment by thebengalboy** [comment]
Hello @tareq1988 

We are sorry that we are unable to provide the commit reference at this moment but we have fixed the issue already. I just checked the issue again to be sure and all seems okay so far. Employee 'On Leave' and upcoming leave are showing on the widget accordingly.

Thanks
