### ISSUE TITLE
Remove the "Checkin" button.

### ISSUE THREAD

**Issue by tareq1988** [wp-erp/wp-erp#729]
The current admin bar **checkin** button is confusing and showed to everyone. People gets checked-out by accidental clicking. So remove the button for avoiding confusion.

![screen shot 2018-11-19 at 2 43 32 pm](https://user-images.githubusercontent.com/153669/48695528-98f73a00-ec09-11e8-91b2-036be73ca93c.png)

**Comment by thebengalboy** [comment]
This has been removed already.
