### ISSUE TITLE
Not Compatible with Divi Theme

### ISSUE THREAD

**Issue by WarenGonzaga** [wp-erp/wp-erp#739]
It is not compatible with Divi Theme and also with Divi Builder. Please fix this one I will report this also to the developer of Divi Theme. Screenshot below.

![image](https://user-images.githubusercontent.com/15052701/49817346-ee5add00-fdaa-11e8-8d69-995ce9e35d4d.png)

**Comment by thebengalboy** [comment]
Hello @WarenGonzaga 

Divi usages a massive number of CSS and JS files which really not possible to make it compatible with. We recommend our users to use any other theme rather than a page builder who engaged with so many things!

Thanks

**Comment by WarenGonzaga** [comment]
@thebengalboy alright, I understand... but please do support this plugin because there are so many users of it so the use of WP ERP will not limit by one very popular theme in WordPress.

**Comment by woroschilow** [comment]
Hello,

I did already mention this issue in this thread here.
https://wordpress.org/support/topic/wp-erp-back-end-display-issues/

It's really sad, that this issue exists for so long and no change so far.
I understand the complexity and that there are priorities, but Divi is THE biggest theme for Wordpress and I believe that it is important to invest some time into this issue.

Divi users are regularly at the back end and it is hard to recommend WP ERP to other Divi users, as long this issue isn't solved.
A broken style tends to give the feel of a plugin being shabby.

WP ERP so far is the best CRM plugin so far out there and I would love to recommend this to other Divi users.

Regards
