### ISSUE TITLE
Company logo can not be uploaded

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#751]
Seems the 'Upload Company Logo' option is broken somehow-> http://prntscr.com/m1bh0l

Thanks

**Comment by itowhid06** [comment]
I was not able to reproduce this one. Is there any errors in console?

**Comment by ediamin** [comment]
@thebengalboy when you report an error, please report with errors found in browser console and debug.log. If you don't find any, mention that too.

**Comment by itowhid06** [comment]
@thebengalboy, https://github.com/wp-erp/wp-erp/issues/732 was fixed in 2dec2d9bd2835e6261b5049791bc66b4442df6a5. Can you please pull develop branch and try again?

**Comment by thebengalboy** [comment]
@itowhid06 Sorry, I was in master branch and did not notice the commit#732. This can be closed.

@ediamin Sure thing. I'll follow this from the next time if I get any issue further :)

Thanks

**Comment by madcapnick** [comment]
I am experiencing this same error, console shows the following: 
![image](https://user-images.githubusercontent.com/47468472/52516237-e40f6080-2bec-11e9-8072-306d610d1217.png)
