### ISSUE TITLE
Cannot get it working on a local windows Bedrock WordPress

### ISSUE THREAD

**Issue by distributev** [wp-erp/wp-erp#753]
https://roots.io/bedrock/

I tried without success to install using both methods Composer / github and through the user interface Add New plugin

With composer / github when I was clicking the wp erp UI I was getting exceptions like Illuminate class X interface declares N methods so your class either needs to implement these methods or to be abstract.

Using the Add New plugin UI I was getting internal server error or script x.php exceeded 30 seconds maximum allowed running time (when trying to "Install" the plugin)

**Comment by distributev** [comment]
I tried again Add New Install UI and this is the error I get

Installing Plugin: WP ERP – HRM, CRM & Accounting Solution For WordPress 1.4.1
Downloading installation package from https://downloads.wordpress.org/plugin/erp.1.4.1.zip…

Unpacking the package…

Fatal error: Maximum execution time of 30 seconds exceeded in C:\Projects\myproject\web\wp\wp-admin\includes\class-wp-filesystem-direct.php on line 76

**Comment by thebengalboy** [comment]
Hello @distributev 

We are sorry for being late. Somehow overlooked this!

However, are you still getting the same issue? Do you have any error log?

Thanks
