### ISSUE TITLE
Invalid Date issue from Mobile

### ISSUE THREAD

**Issue by saiftheboss7** [wp-erp/wp-erp#755]
The upcoming birthday field shows "Invalid Date" when viewing the /wp-erp page from mobile. However, the section works okay from PC.

Screenshot: https://i.imgur.com/SCRNK7S.png

![Screenshot WP Erp](https://i.imgur.com/SCRNK7S.png "Logo Title Text 1")

**Comment by thebengalboy** [comment]
Hello @saiftheboss7 

Tested with several Android devices but it seems okay so far. Would you please mention the device name and OS version?

Thanks

**Comment by saiftheboss7** [comment]
Device iPhone 8 on iOS 12.1.4

**Comment by thebengalboy** [comment]
Hello @saiftheboss7 

Tried several devices but was not able to reproduce the issue. We are closing this for now. If you find the same, feel free to open the issue again.

Thanks

**Comment by saiftheboss7** [comment]
Hello @thebengalboy 

The issue is not fixed as of yet. https://www.loom.com/share/7c2fa17c9ea74eb394995f2643f985d7


iOS 13.7 
Device: iPhone11
Browser: Safari

**Comment by saiftheboss7** [comment]
As of 12-Oct-2022, it's fixed (iPhone 11, iOS 16.0.2)
