### ISSUE TITLE
Problem with country list field

### ISSUE THREAD

**Issue by manjur90** [wp-erp/wp-erp#767]
I did not find Scotland in the country list. and also I figure out few countries name missing in the field.
https://prnt.sc/m8coo5

**Comment by thebengalboy** [comment]
It's being considered under the United Kindom. Also, as it's under the UK, the country code(GB) needs to be the same but it's not possible to have multiple countries with the same country code. 

So, if you are from Scotland, please consider choosing the UK as the country.
