### ISSUE TITLE
SMTP settings not working

### ISSUE THREAD

**Issue by sshettyusa** [wp-erp/wp-erp#773]
SMTP conncection throwing an error as follow. 
![capture](https://user-images.githubusercontent.com/46901129/51754793-39932b80-208b-11e9-99ef-9b15554d99a5.JPG)
Email Domain is hosted in Godaddy.

**Comment by thebengalboy** [comment]
@sshettyusa For SMTP, You have to enable this from your Gmail settings-> https://myaccount.google.com/lesssecureapps?pli=1

**Comment by sshettyusa** [comment]
Still facing the same issue.
