### ISSUE TITLE
Employee update action data could be more useful

### ISSUE THREAD

**Issue by emshach** [wp-erp/wp-erp#777]
Change data passed to `erp_hr_employee_update` is 
```php
wp_parse_args( $this->data, $this->changes )
```
which hides any changes behind current data since `$this->changes` is in the position of the default data. It seems it would be better if it were the other way around. Also `data` and `changes` are deep arrays so I'm not sure how useful a shallow merge is. I found it more useful to pass `changes` as a separate argument to the action.

**Comment by thebengalboy** [comment]
Thanks @emshach 

The pull request was merged but somehow the issue was not closed. I'm closing it here.

Thank you so much for contributing to WP ERP. Please be with us :)

Thanks
