### ISSUE TITLE
Company logo doesn't open a screen

### ISSUE THREAD

**Issue by madcapnick** [wp-erp/wp-erp#779]
@itowhid06 Sorry, I was in master branch and did not notice the commit#732. This can be closed.

@ediamin Sure thing. I'll follow this from the next time if I get any issue further :)

Thanks

_Originally posted by @thebengalboy in https://github.com/wp-erp/wp-erp/issues/751#issuecomment-450613921_

**Comment by madcapnick** [comment]
![image](https://user-images.githubusercontent.com/47468472/52516254-40728000-2bed-11e9-8eda-a26bab55e254.png)

**Comment by madcapnick** [comment]
![image](https://user-images.githubusercontent.com/47468472/52516271-7e6fa400-2bed-11e9-981d-4eb66962c000.png)

**Comment by thebengalboy** [comment]
This has been fixed already in the development branch. Please follow #732 issue.

**Comment by madcapnick** [comment]
> This has been fixed already in the development branch. Please follow #732 issue.

Totally overlooked that. Thanks for the help.
