### ISSUE TITLE
Importing customer from the existing users doesn't pull the address

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#783]
Suppose, I have a user on WordPress and I'd like to import this user as a customer. I can do but if I import that user as a customer, it doesn't get the address. None of the address field getting the values from the existing profile.

**Comment by paulrjohnson1404** [comment]
Any updates on fixing this issue please?

**Comment by thebengalboy** [comment]
Hello @paulrjohnson1404 

We have investigated a bit on this but have not decide anything yet. As WP users don't have address fields by default, then we might need to take the address from the WooCommerce address of a user. But, one can choose not to use WooCommerce and there will not have any fields for the address of a user.

So, we might not consider taking the WooCommerce or any other 3 party address from the user profile at this moment.

**Comment by paulrjohnson1404** [comment]
Hi Mehedi

I am sorry but this sounds crazy. How can a CRM system only have the ability to put in an address when an order is placed.

Communicating with potential customers before the order is probably the most important aspect a CRM system need to track.

People still do use mail to send out proposals etc so not to have this at an earlier stage makes no sense at all.



On 4 Mar 2019, at 16:34, Mehedi Hasan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @paulrjohnson1404<https://github.com/paulrjohnson1404>

We have investigated a bit on this but have not decide anything yet. As WP users don't have address fields by default, then we might need to take the address from the WooCommerce address of a user. But, one can choose not to use WooCommerce and there will not have any fields for the address of a user.

So, we might not consider taking the WooCommerce or any other 3 party address from the user profile at this moment.
