### ISSUE TITLE
Strings that are not translatable

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#796]
Those strings are found all over the CRM, in different places.

- Customers;
- Leads;
- Opportunities;
- Subscribers;
- Trash;
- Search Contact;
- Contact Name;
- Email address
- Phone;
- Life Stage;
- Owner;
- Created At;
- Bulk actions;
- Apply;
- Filter by owner;
- Filter by segment;
- Filter by company;
- Filter;
- No results found;
- Please enter 3 or more characters;
- Delete;
- Assign group;
- Edit;
- View;
- Delete;
- Search segment;
- Lead;
- Show advanced fields;
- Others info;
- Mobile; Traduzir para - Tipo de Imóvel
- Select;
- Phone number;
- Others;
- Notes;
- Edit this contact;
- Hide Search segment;
- New Note;
- Type Your Note;
- Log activity;
- Schedule;
- Tasks;
- From;
- To;
- Filter;
- Log a Call;
- Log a meeting;
- Log an Email;
- Log an SMS;
- Log;
- Notes;
- Tasks;
- Types;
- Print;
- To;

**Comment by norwebcl** [comment]
Accounting 
HR
