### ISSUE TITLE
CRM Agents should not delete the contact group

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#802]
CRM agents can delete the contact groups from the bulk actions. Please revoke their access to delete any contacts or contact groups that he/she has not created.

**Comment by lazaroliria** [comment]
Related to this issue, there is another little issue: You create an "Private Group", The other agents can see the "private group" and click in the title and see your contacts inside the group, also click the contacts and see the contact info. 

Should be private, right? Regards.
