### ISSUE TITLE
update version 1.4.3 broke site

### ISSUE THREAD

**Issue by mslill** [wp-erp/wp-erp#810]
I am running 5.1.1  and I updated with your newest version.  All of the wordpress dashboard menu icons disappear.  I downgraded to my old version.  Thought you should know.

**Comment by thebengalboy** [comment]
Hello @mslill 

Have you tried updating the PHP version to PHP 7.2 or so on? I'm not sure why you are facing such kind of issue but it's well tested with the PHP 5+ as well.

However, just to be sure, have you checked if there is any [conflict with any other theme or plugin](https://thebengalboy.com/best-practice-find-wordpress-theme-plugin-conflicts/)?

Regards,

**Comment by lazaroliria** [comment]
This issue is true. I try to update from the repository files because I want the fuction to notify the agents when they have a new contact assign and the site breaks. Error 500. So, I downgrade. 

Ill be in attention to a possible solution.
Regards.

**Comment by lazaroliria** [comment]
> This issue is true. I try to update from the repository files because I want the fuction to notify the agents when they have a new contact assign and the site breaks. Error 500. So, I downgrade.
> 
> Ill be in attention to a possible solution.
> Regards.

I update the PHP Version to 7.2 and nothing, still Error 500. 

Regards.

**Comment by itowhid06** [comment]
Please navigate to `wp-erp` directory and run `composer install`. Then run `composer dump-autoload -o`. Let us know if the problem still persists. Thanks.

**Comment by lazaroliria** [comment]
Look, I update Wordpress to last version: 5.1.1 and re install the plugin from the Wordpress Repository and works, then i try to "install" the functionality to send emails when a contact is assigned and Error 500: #809

**Comment by thebengalboy** [comment]
Please avoid the commit 809 at this moment as it's causing you a problem. We'll have a look at this further before releasing our next update.

Thanks
