### ISSUE TITLE
CRM Should Notify Agents when they have a new "lead" assigned.

### ISSUE THREAD

**Issue by lazaroliria** [wp-erp/wp-erp#812]
Hi, right now as CRM Manager I assign a lead to an Agent but if the Agent don't go inside the backend he don't realize that he have a new lead.

The System Should notify when you have a new lead by email. Or you guys should add this fuction to the workflow addon.

Regards.

**Comment by thebengalboy** [comment]
Hello @lazaroliria 

We have added this feature already with the commit #809 

This will be released with our next version.

Thanks
