### ISSUE TITLE
Mention Customer In the Schedule Emails

### ISSUE THREAD

**Issue by lazaroliria** [wp-erp/wp-erp#813]
Hi guys, im trying to create a Calendar Integration with Zapier (yes, in my way).

How I want to do this is basically creating a filter in my email and saying that All emails coming from my CRM email address and Contain "Schedule" in the subjects take the body info and create an event (I just gonna put the date and time in the body part) and in the Subject Part I want to put "Schedule w/Customer Name" because now just say "ERP Schedule" But you don't have Idea with who is this schedule.

I try with this... But didn't work, dont send the emails (the crm)... 

function erp_crm_send_schedule_notification( $activity, $extra = false ) {
    if ( ! $extra ) {
        return;
    }

    switch ( $extra['notification_via'] ) {

        case 'email':
            $users = [];

            foreach ( $extra['invite_contact'] as $contact ) {
                $users[] = get_the_author_meta( 'user_email', $contact );
            }

            $created_user = get_the_author_meta( 'display_name', $activity['user_id'] );
            $people_info = erp_get_people_by('id', $activity['user_id']);
            $contact_name = $people_info->first_name . ' ' . $people_info->last_name;
            // var_dump($activity);
            // $created_user = get_the_author_meta( 'first_name', $activity['created_by'] ) . ' ' . get_the_author_meta( 'last_name', $activity['created_by'] );
            array_push( $users, $created_user );

            foreach ( $users as $key => $user ) {
                $body = sprintf( __( '%s', 'erp' ), date( 'F j, Y, g:i a', strtotime( $activity['start_date'] ) ) );
                // $body = print_r($activity, true);
                // $body = print_r($people_info, true);
                erp_mail( $user, sprintf( __( 'Schedule w/%s - %s', 'erp' ), $contact_name, date( 'F j, Y, g:i a', strtotime( $activity['start_date'] ) ) ), $body );
            }
            erp_crm_update_schedule_notification_flag( $activity['id'], true );
            break;

        default:
            do_action( 'erp_crm_send_schedule_notification', $activity, $extra );
            break;
    }
}

Is there a global function that will return information on a contact if i already know the contact_id, not the wordpress user id, CONTACT ID and return information on the CONTACT not the wordpress use??

**Comment by lazaroliria** [comment]
Problem solved:

function erp_crm_send_schedule_notification( $activity, $extra = false ) {
    if ( ! $extra ) {
        return;
    }



    switch ( $extra['notification_via'] ) {

        case 'email':
            $users = [];

            foreach ( $extra['invite_contact'] as $contact ) {
                $users[] = get_the_author_meta( 'user_email', $contact );
            }

            $created_user = get_the_author_meta( 'user_email', $activity['created_by'] );
            $people_info = erp_get_people_by('id', $activity['user_id']);
            $contact_name = $people_info->first_name . ' ' . $people_info->last_name;
       
            array_push( $users, $created_user );


            foreach ( $users as $key => $user ) {
                $body = sprintf( __( '%s', 'erp' ), date( 'F j, Y, g:i a', strtotime( $activity['start_date'] ) ) );
                erp_mail( $user, sprintf( __( 'AAREG Associate Portal Appoiment w/%s - %s', 'erp' ), $contact_name, date( 'F j, Y, g:i a', strtotime( $activity['start_date'] ) ) ), $body );
            }
            erp_crm_update_schedule_notification_flag( $activity['id'], true );
            break;

        default:
            do_action( 'erp_crm_send_schedule_notification', $activity, $extra );
            break;
    }
}

**Comment by thebengalboy** [comment]
Thanks @lazaroliria 

However, we have a future plan to bring Zapier integration. Keep in touch :)

Regards,
