### ISSUE TITLE
fix: tooltips load off the screen in admin

### ISSUE THREAD

**Issue by mathetos** [wp-erp/wp-erp#816]
Currently in WP-Admin, specifically on the "WP-ERP > Settings > General" screen, the tooltips when hovered over, load below the fold where no one can see them, and when you scroll they disappear because your mouse is no longer hovering. 

It seems the plugin is using this OLD jQuery library which hasn't been updated in 9 years: https://github.com/drewwilson/TipTip

The "fix" for this problem in my opinion, would be to replace that jQuery library, with [hint.css](https://github.com/chinchang/hint.css) -- it's a pure CSS solution which is very stable. We use it in the GiveWP plugin and haven't had one problem with it so far at all.

**Comment by tareq1988** [comment]
Hello Matt, thanks for noticing this. Though in my installation it's working fine. Maybe something is conflicting in your installation? But also, we shouldn't be using an old library. Hint looks good btw, we will update the tooltip implementation :)
