### ISSUE TITLE
Future Schedules not showing in the Schedule Tab / SMS Notification not working

### ISSUE THREAD

**Issue by lazaroliria** [wp-erp/wp-erp#817]
**Hi my friends, the plugin is looking everyday better.** 

I just found today 2 issues: 

- When people choose be notified by SMS about their schedules, they never get the sms. (The CRM is not sending the SMS) 

- and the tab "Schedules" only is showing past schedules, not futures schedules.  (In the overview tab the calendar is working properly.)

Regards

**Comment by thebengalboy** [comment]
Hello @lazaroliria 

I'm afraid but I found the all the future schedules are showing on the calendar properly. See the screenshots> http://prntscr.com/nk0kq1

Also, as the SMS Notification is a paid extension, we better not to talk about it here. If you are facing any issue with any of the paid extensions, please feel free to open a support ticket. We'll help you out :)

Thanks
