### ISSUE TITLE
Schedule Notifications

### ISSUE THREAD

**Issue by lazaroliria** [wp-erp/wp-erp#818]
Hi, notifications by email or sms not working after update 1.4.4.

By the way, i know the plugin really well and everything is configure exactly how it should be (I said that to avoid being treat like I'm missing something related with "Allow Less Secure Apps in Gsuite" or something relate with authentication. 

Just to let you know also: Emails between agents and contacts works, notification when a new contact is created works. **Only problem detected is the schedule notifications.**

Before was working normal. 

Regards.

**Comment by thebengalboy** [comment]
Hello @lazaroliria 

I just checked after hearing from you but it all seems okay so far. See I got the schedule email-> http://prntscr.com/nlxvqk

Maybe you have not set the notification requirements properly?-> http://prntscr.com/nlxwp0

If you need help on this further, please contact our support center. As long as this is not a plugin issue, I'm closing it here.

Thanks
