### ISSUE TITLE
feature request: support Documents in HR Frontend

### ISSUE THREAD

**Issue by mathetos** [wp-erp/wp-erp#819]
The Document Manager works great in combination with HR features in the Admin. But currently the documents that are uploaded to employees profiles are NOT visible via the HR Frontend at all. This means we cannot use the HR Frontend as we hoped.

This would be an excellent and needed feature so that the HR Frontend has all the necessary features that the Admin currently has as well.

**Comment by thebengalboy** [comment]
Hello @mathetos 

Bringing all the HR extension features(Including Document manager, Recruitment, Asset manager and all) in HR Frontend is already on our working list. We are hoping to start working with them soon.

Also, we encourage to open a support ticket for anything related to the paid extensions. You can join the other ERP users on our active forum-> https://wperp.com/discussions/

As this is not a core plugin issue, I'm closing it here and taking your request as a note to start enhancing our HR Frontend sooner. 

Thanks for being with WPERP :)
