### ISSUE TITLE
Fresh install bug on Latest ERP Blogs

### ISSUE THREAD

**Issue by AmauryVanEspen** [wp-erp/wp-erp#821]
Please,

see the follow picture for related bug
https://framapic.org/PhYQ4DcQjNmi/mQQk3JiBhYLI.png

maybe related to "no content" post
Warning: Invalid argument supplied for foreach() in C:\wamp64\www\wordpresserp\wp-content\plugins\erp\includes\admin\views\erp-overview.php on line 19

**Comment by thebengalboy** [comment]
Hello @AmauryVanEspen 

It should show something like this-> http://prntscr.com/nn46l3

I'm not sure why you are getting the error but the issue does not persist with the core as I have checked it in several ways. However, You can follow the steps below:

**1. Cleaning your WPERP database and installing it again.**

- Deactivate and delete the WPERP from your site.
- Now, download this cleaner plugin and install, activate on your site. This will clear all of the previous databases. (Note: Will lose everything on WPERP)
- After running the cleaner, install and activate the WPERP again.
- Then try to install the extension that was causing the problem.

**2. [Check if you are running with any conflict](https://thebengalboy.com/best-practice-find-wordpress-theme-plugin-conflicts/)**

Thanks
