### ISSUE TITLE
Error updating employee permission

### ISSUE THREAD

**Issue by tareq1988** [wp-erp/wp-erp#825]
When I'm updating the permission of an employee and hitting **Update Permission**, I get this error.

![image](https://user-images.githubusercontent.com/153669/58001078-4d601300-7afc-11e9-9218-360f35634162.png)

**Comment by itowhid06** [comment]
Fixed in https://github.com/wp-erp/wp-erp/commit/93ee48d8f9c151c1434be08f966bad2325ce843c.
