### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by ahangarha** [wp-erp/wp-erp#826]
Hi

What is the license of the project? license.md file is missing.

**Comment by thebengalboy** [comment]
Hello @ahangarha 

I'm sorry but the license details are mentioned on the readme file-> https://github.com/wp-erp/wp-erp/blob/develop/readme.txt

Also, we have already confirmed you from our support team that it is under the GPL license.

Thanks

**Comment by ahangarha** [comment]
Yes! I contacted you guys on your website. My question is personal. I think it is very much standard practice to keep license in a specific file called LICENSE of LICENSE.md

So please include the license file in the repo
