### ISSUE TITLE
Public search segment is not visible to all the managers

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#832]
There has an option showing a search segment to all the users while saving the segment but it doesn't work. I have selected 'Show this segment to all' and then switched to another user who is a manager as well, but he could not see it.

Reference screenshot: http://prntscr.com/odfl7w

Thanks

**Comment by abstractive-gary** [comment]
Any word on when this might be fixed?

**Comment by thebengalboy** [comment]
Hello @abstractive-gary 

This issue is already on our working list. You'll be notified when it's done.

Thanks

**Comment by thebengalboy** [comment]
This has been fixed and released with the version 1.5.4.
