### ISSUE TITLE
CRM Company Name Max Characters is 30

### ISSUE THREAD

**Issue by tjlabais** [wp-erp/wp-erp#837]
How to extend characters for company name?

Many of our clients have more than 30 characters for company name.

**Comment by thebengalboy** [comment]
Hello @tjlabais 

Generally, a company name doesn't exceed over 30 characters. However, if you need to increase the limit, you can do it on the following file: `.../wp-erp/wp-content/plugins/wp-erp/modules/crm/views/js-templates/new-customer.php`; Line: 75.

Thanks

**Comment by itowhid06** [comment]
Hello @tjlabais, 
If you are using latest develop version then you can use more than 30 characters by putting the following code in your theme's `function.php` file
`add_filter( 'erp_crm_custom_attr_length', function() {
    return 100;
});`

**Comment by tjlabais** [comment]
@itowhid06 thanks for the tip! This fixed our problem.
