### ISSUE TITLE
Can't select older Training during assign a training to Employees

### ISSUE THREAD

**Issue by mmarj** [wp-erp/wp-erp#838]
In WPERP -> HR -> Employees Profile -> Training Tab -> Add New Training: during assigning any Training to the employee it's only showing the last 5 Training's list to select.

There's should be any scroll bar or something like this to choose previous Training.

[Reference video](https://drive.google.com/open?id=1JoRBEnKTc7jOUC4_NDyQ6ZGF39XDFjeE)

**Comment by nadim1992** [comment]
Fixed on erp-hr-training add-on
