### ISSUE TITLE
Sending file attachments is not saving/receiving over the CRM-Contact Email Thread

### ISSUE THREAD

**Issue by mmarj** [wp-erp/wp-erp#840]
Once a conversation is taking place over the CRM-Email section. It's rendering the reply accordingly but not receiving/showing the sent attachment documents over the activity Email thread.

[Reference Video](https://drive.google.com/open?id=1aEXkr7o3hbKxEZ7db4qrH65eQR4LcXYH)

**Comment by nadim1992** [comment]
Can't reproduce.
