### ISSUE TITLE
WP ERP - HR - Announcement tab.

### ISSUE THREAD

**Issue by zeon01** [wp-erp/wp-erp#841]
There are two issues:
1. It should be plural "Announcements".
2. After clicking on Announcement tab, the top navigation bar disappears. See image below:
![Screenshot 2019-08-06 at 5 24 52 PM](https://user-images.githubusercontent.com/5868528/62685499-98dfda00-b9e4-11e9-9d90-b33ad74aa596.png)

**Comment by thebengalboy** [comment]
Hello @zeon01 

1. We'll change it soon.
2. Announcements are post types, and WordPress generally doesn't have/allow top menus or navbar. If you navigate to **wp-admin->posts**, you'll see the same. None of the top menus/nav there.

Thanks
