### ISSUE TITLE
The Asset Request button of the Asset-Management add-on's an employee’s profile is not working from the Version-1.4.4 to Latest

### ISSUE THREAD

**Issue by mmarj** [wp-erp/wp-erp#842]
Since the WPERP core plugin 1.4.4, The Asset Request button of the Asset-Management add-on's an employee’s profile is not working.

[Please check this testing video.](https://drive.google.com/open?id=1PC2DEOBKT8zHBEFeNqNIfH5H_s52xIos)

**Comment by itowhid06** [comment]
It was an issue of Asset Management add-on and it has been fixed in develop branch.

**Comment by yiyeluwei** [comment]
> It was an issue of Asset Management add-on and it has been fixed in develop branch.

May I ask what actually caused the issue?
