### ISSUE TITLE
Missing "class-erp-acct-bg-process-1.5.1.php" cause admin to break.

### ISSUE THREAD

**Issue by tnchuntic** [wp-erp/wp-erp#845]
Admin not able to loging because of the wperp error.

**See server error log:**
mod_fcgid: stderr: PHP Fatal error: require_once(): Failed opening required '/var/www/vhosts/domainname.com.au/httpdocs/wp-content/plugins/erp/includes/updates/bp/class-erp-acct-bg-process-1.5.1.php' (include_path='.:/opt/alt/php71/usr/share/pear') in /var/www/vhosts/domainname.com.au/httpdocs/wp-content/plugins/erp/wp-erp.php on line 238, referer: https://www.domainname.com.au/wp-login.php

**Temporary Solution:**
- Copy class-erp-acct-bg-process-1.5.1.php file from git to live website

**Comment by thebengalboy** [comment]
Hello @tnchuntic 

We have released a new version 1.5.2. Please update/install the new version to get rid off from the issue you were facing.

We are really sorry for the unexpected inconvenience.

Thanks
