### ISSUE TITLE
Upgrade to 1.5.2 Accounting Module bug list

### ISSUE THREAD

**Issue by tjlabais** [wp-erp/wp-erp#846]
my recent backup is 1.4.6 with custom field builder

BUGS:
1. VENDOR - contact is made required when the company is more important when doing purchases
2. CUSTOMER - contact is made default / if your business is selling to companies and not individuals, this new system has no option to change default
3. REFERENCE # - this is gone in the new system... but custom field builder is not working on the new accounting module
4. MEMO - internal memo been replaced with PARTICULARS, but the content we had were not migrated
5. PRODUCT/SERVICE - <VENDOR required> if you are offering services only, there is no vendor for it; so why make it required?
6. INVOICE description - all sales code 400 were moved to sales revenue 1402; however, the description were not carried over. (at least auto generate products/services for this?)
7. CUSTOM FIELD BUILDER - is not working on adding Tax ID# on vendors
8. PDF EXPORT - is not working in INVOICE view (more action button only shows email as the option), sending as pdf works though you need to wait for the email prior to getting a copy of the PDF
9. VENDOR COMPANY - tried to create a new vendor and company automatically is removed
10. VENDOR - could not browse the list (clicking next page returns 'no items found') PaginateCustomers appears

**Comment by tjlabais** [comment]
11. after upgrading to 1.5.2, all EXPENSES are moved to PURCHASES. What we did in the old 1.4.6 is to create a journal entry for PURCHASES since there is no function for it.
12. JOURNAL - still figuring it out where all the entries went since the new 1.5.2 is empty after upgrade from 1.4.6

**Comment by thebengalboy** [comment]
Hello @tjlabais 

Most of the issues you mentioned are not bug or issue with the plugin actually. However, as you have already created a support ticket, please wait to hear from our support team. They'll answer all of your queries and hope that will clear all the confusion :)

Thanks

**Comment by tjlabais** [comment]
@thebengalboy 

yes, the bugs are not all plugin bugs, but migration bugs. so, for the info of everyone else I will separate the plugin bugs from the migration bugs:

PLUG-IN BUGS:
1. Vendor Contact List - v.1.4.6 Company name is default in 1.5.3 contact first name / last name is default
2. Reference# removed in 1.5.3 <create invoice> thereby disabling cross referencing between invoices and payments
3. Custom Field Builder 1.2 is not working on Vendor List 1.5.3
4. Browse Vendor List only shows the first page

MIGRATION BUGS:
1. PARTICULARS 1.5.3 replace MEMO 1.4.6 - data not migrated by update program
2. PRODUCT/SERVICE 1.5.3 replace invoice DESCRIPTION 1.4.6 - old data not migrated by update program
3. EXPENSES 1.4.6 migrated into PURCHASES 1.5.3 table instead of EXPENSES 1.5.3 table
4. JOURNAL 1.4.6 not migrated to JOURNAL 1.5.3
