### ISSUE TITLE
plugin translation

### ISSUE THREAD

**Issue by arthurterramarques** [wp-erp/wp-erp#848]
There's a bug when i set the language to french (made by me) or spanish (made by you) the module accounting doenst work at all. White page.

The new version can't be translated anymore.

**Comment by thebengalboy** [comment]
It has been fixed with the commit here-> https://github.com/wp-erp/wp-erp/commit/8ea27951e0e73e43d69052cd71308bb5825e9073

We are hoping to release these fixes within this week.

Thanks
