### ISSUE TITLE
Accounting invoice PDF export is not working

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#849]
**Accounting->Invoice-> More action-> Export as PDF**- is not working. Reference screenshot: https://prnt.sc/p78c7q

**Comment by itowhid06** [comment]
fixed 11c8e82e73123e497534c41d4cf9bf339b88bbec

**Comment by tjlabais** [comment]
work around to use pdf export:
1. open invoice
2. send to mail -> arbitrary email and check attach as pdf -> send
3. close send mail form
4. click <export to pdf> should work now since pdf has been generated in
wp-content/uploads/erp-pdfs/
