### ISSUE TITLE
Transactions Particulars are not visible in invoices, only appears in the editable profile section.

### ISSUE THREAD

**Issue by mmarj** [wp-erp/wp-erp#854]
Transactions Particulars are not visible in invoices, only appears in the editable profile section.
https://ibb.co/9rPkP5M

**Comment by tjlabais** [comment]
in update 1.5.4 this is fixed; however, in the PDF export, Particulars is labeled "Payment Information". For others, the label can be edited in transactions.php / also, the stamps (badges) can be changed in this same file if you are using different stamps for PENDING, PAID, etc.
