### ISSUE TITLE
New update cause PDF not showing Due Date

### ISSUE THREAD

**Issue by chanifalfath** [wp-erp/wp-erp#857]
Hello,

New release WP ERP cause PDF not showing due date.
It's only show transaction number & transaction date.

Thanks
Chanif

**Comment by tjlabais** [comment]
need to edit accounting/includes/functions/transactions.php and add the following code after Set Issue Date

    // Set Date Due
    $datedue = ! empty( $transaction->due_date) ? $transaction->due_date : $transaction->datedue;
    $trn_pdf->set_reference( erp_format_date( $datedue), __( 'Date Due', 'erp' ) );

**Comment by tjlabais** [comment]
![date_due](https://user-images.githubusercontent.com/1410197/65572908-1dd68100-df9c-11e9-8d3e-83288c953b69.JPG)

**Comment by chanifalfath** [comment]
still got same issue, already add 

> 
> 
> need to edit accounting/includes/functions/transactions.php and add the following code after Set Issue Date
> 
> ```
> // Set Date Due
> $datedue = ! empty( $transaction->due_date) ? $transaction->due_date : $transaction->datedue;
> $trn_pdf->set_reference( erp_format_date( $datedue), __( 'Date Due', 'erp' ) );
> ```

Already add this, but still had same issue.

**Comment by chanifalfath** [comment]
![ss-invoice-due-date](https://user-images.githubusercontent.com/1436709/65578331-ccc88c00-df9f-11e9-80b2-ad5c1c808763.png)

**Comment by tjlabais** [comment]
the new accounting module does not regenerate the pdf. I had to delete the pdf files in wp-content\uploads

to generate new pdf, you need to send email to arbitrary email as an attachment then you can get the new pdf export with the Due Date

**Comment by chanifalfath** [comment]
Ok its worked good now. Thanks!
I'll close this issued. 
I hope this will be include on next version :)
