### ISSUE TITLE
AC 1.5.5 PDF Export Amount is garbled

### ISSUE THREAD

**Issue by tjlabais** [wp-erp/wp-erp#860]
**If there is no TAX, the amount figures appears normal**

![pdf01](https://user-images.githubusercontent.com/1410197/65668799-fdc6c080-e074-11e9-90c4-5194f5945c0a.JPG)

**if TAX is included, square character appears in amount**

![pdf02](https://user-images.githubusercontent.com/1410197/65668889-277fe780-e075-11e9-875f-2c655786b458.JPG)

**Comment by itowhid06** [comment]
@tjlabais, I was unable to reproduce this. Screenshot attached.
![image](https://user-images.githubusercontent.com/12055657/65852812-256d9f80-e379-11e9-8192-8e77693ac18b.png)

**Comment by thebengalboy** [comment]
Hello @tjlabais 

The issue maybe with some of the specific currencies. What is the currency you have tried with? We need to check for that particular currency.

Thanks

**Comment by tjlabais** [comment]
@thebengalboy 

I followed your sample using price point at hundreds only and could not produce the problem. which means the problem occurs in the thousands range.

**price point hundreds:**
![invoice03](https://user-images.githubusercontent.com/1410197/65856032-214e7b80-e393-11e9-8f05-097c85ee474f.JPG)

**price point thousands:**
![invoice04](https://user-images.githubusercontent.com/1410197/65856288-ccf7cb80-e393-11e9-8b45-2107ed8217de.JPG)

**price point ten thousands:**
![invoice05](https://user-images.githubusercontent.com/1410197/65856396-1ba56580-e394-11e9-8834-8cd552bd4f6e.JPG)

**Comment by tjlabais** [comment]
I tried switching to USD, still the same bug.

**Comment by thebengalboy** [comment]
Hello @tjlabais 

PDF is being generated initially when the invoice is created. So, it won't have an effect on changing the currency. You need to create an invoice again after changing the currency.

**Comment by tjlabais** [comment]
@thebengalboy 

yes I know this. you can easily generate new pdf by more actions -> send email -> attach as pdf before exporting again. ;-)

@itowhid06 
as mentioned above, when amount is above 10,000 + taxes added to price, you will get the square character bug.

**Comment by tjlabais** [comment]
**FIX FOR MISSING DUE DATE**

```
// Set Date Due
$datedue = ! empty( $transaction->due_date) ? $transaction->due_date : $transaction->datedue;
$trn_pdf->set_reference( erp_format_date( $datedue), __( 'Due Date', 'erp' ) );
```

**FIX FOR SQUARE CHARACTER BUG**

        // Add Table Items
        foreach ( $transaction->line_items as $line ) {
            //$trn_pdf->add_item( [ $line['name'], $line['qty'], $line['unit_price'], $line['discount'], $line['tax'], $line['line_total'] ] );
            $trn_pdf->add_item( [ $line['name'], $line['qty'], $line['unit_price'], $line['discount'], $line['tax'], html_entity_decode($line['line_total']) ] );
        }

**Comment by tjlabais** [comment]
![invoice06](https://user-images.githubusercontent.com/1410197/66029641-45948e80-e532-11e9-90ae-5f1dbdaf986c.JPG)

**Comment by thebengalboy** [comment]
Hello @tjlabais , you can have a pull request with the code you wrote :)
