### ISSUE TITLE
AC 1.5.5 Product/Services better input method

### ISSUE THREAD

**Issue by tjlabais** [wp-erp/wp-erp#861]
> The product/services list contain both items that you sell and items that you buy for your business. It is best to separate BUY and SELL products similar to TAX zone. Otherwise, you will browse a very long list of products and services mixed together. It's very confusing.
> 
> When you create a Sales Invoice, only SELL products should be retrieved not everything.
> 
> When you create Purchase Invoice, only BUY products should also be retrieved.
> 
> When you add a SELL product, vendor is not needed, sale amount is required.
> When you add a BUY product, vendor is required, sale amount is not required.

**Found a better solution which can be implemented faster. Please see last comment. Thanks!**

**Comment by tjlabais** [comment]
![product01](https://user-images.githubusercontent.com/1410197/65670175-67e06500-e077-11e9-95cd-81fd3fc4378c.jpg)

**Comment by tjlabais** [comment]
**To simplify the creation of invoices/purchases, please put product categories filter**
![invoice10-01](https://user-images.githubusercontent.com/1410197/66380525-3ad27180-e9ea-11e9-8f2b-470e5b050bdd.JPG)

**Comment by thebengalboy** [comment]
Hello @tjlabais 

We do not manage the selling and buying products separately. I even not sure if anyone do that! In the B2B type businesses, the product is single. Means, what you buy and what you sell is the same item, with just the inventory changes.

Let's say, 7 up. You purchase 7 up 100 copies and then sell it. So, the product is one/single here. Your inventory is just changing.

So no, we are not considering to have separate products.

Thanks
