### ISSUE TITLE
AC 1.5.5 Problem creating Purchase transaction due to Vendor defaults

### ISSUE THREAD

**Issue by tjlabais** [wp-erp/wp-erp#864]
**AC 1.4.6 Vendor default is the vendor company name**

![vendor03](https://user-images.githubusercontent.com/1410197/65676544-acbdc900-e082-11e9-99d0-175bb645943b.JPG)

**AC 1.5.4 Vendor default is the vendor first name and last name**

![Vendor04](https://user-images.githubusercontent.com/1410197/65676585-be9f6c00-e082-11e9-8a7d-05e09b36133b.JPG)

**if I want to pay to Vendor - facebook company, I can not create a purchase transaction because company name will not appear in new purchase dropdown box**

![vendor05](https://user-images.githubusercontent.com/1410197/65676754-04f4cb00-e083-11e9-8995-1fa68cb1fcdb.jpg)

**Comment by tjlabais** [comment]
while waiting for the fix, you can put COMPANY NAME in First Name and put <space> for Last Name

**Comment by thebengalboy** [comment]
Hello @tjlabais 

We are not considering the company name in the search instead of the Vendor name. It's all based on the Vendor and their name only. The search will work based on the vendor name as well.

You can instead use the Company name for your vendors.
