### ISSUE TITLE
Upgrade from pre 1.5.0 version will interchange Chart of Account Values

### ISSUE THREAD

**Issue by tjlabais** [wp-erp/wp-erp#878]
**AC 1.4.6 Chart of Accounts**
![chartacct01](https://user-images.githubusercontent.com/1410197/66185947-8c5dc200-e6b3-11e9-81a6-d7c920ebbd96.JPG)

**AC 1.5.4 Chart of Accounts**
![chartacct02](https://user-images.githubusercontent.com/1410197/66185923-7bad4c00-e6b3-11e9-8334-6c9cea84ef22.JPG)

_**After the upgrade, values between EQUITY and EXPENSES are interchanged**_

**Comment by nadim1992** [comment]
Hello, 
We have migrated previous data accordingly. And it will not affect your transactions in any ways.

Thanks

**Comment by tjlabais** [comment]
My data expenses and equity is interchanged after migrating from 1.4.6; so, creating a new bill payment will cause the drop down box to show equity listing instead of expenses listing.

I checked if it were a fresh install of the plugin, bill payments shows the proper expense listing.
