### ISSUE TITLE
AC 1.5.5 Add New Vendor Custom Field value is not saving

### ISSUE THREAD

**Issue by tjlabais** [wp-erp/wp-erp#883]
**Accounting->Users->Vendors->Add New Vendor**
**Custom Field set to be placed on top (TIN)**
![customfield01](https://user-images.githubusercontent.com/1410197/66302082-e0261080-e92a-11e9-824f-995f174f1bfd.JPG)

**After saving, only way to view vendor custom field is to edit vendor; however, the value is blank.**
![customfield02](https://user-images.githubusercontent.com/1410197/66302160-ff24a280-e92a-11e9-999d-d970ef2e2810.JPG)
![customfield03](https://user-images.githubusercontent.com/1410197/66303305-54fa4a00-e92d-11e9-8c84-93b6213f567f.JPG)

**Comment by nadim1992** [comment]
Fixed https://github.com/wp-erp/wp-erp/issues/885
