### ISSUE TITLE
AC 1.5.5 Missing Filter by Customer or Transaction Type

### ISSUE THREAD

**Issue by tjlabais** [wp-erp/wp-erp#886]
**Accounting->Transactions->Sales**
**In 1.4.6 there is a filter bar to search the company and transaction type**
![search01](https://user-images.githubusercontent.com/1410197/66304561-16b25a00-e930-11e9-826e-ddb11b352afa.JPG)

**In 1.5.5 only Status and Date filters are available**
![search02](https://user-images.githubusercontent.com/1410197/66304639-42cddb00-e930-11e9-8853-94fab3003efa.JPG)

**Comment by tjlabais** [comment]
Transaction Type: Payment or Invoice

**Comment by thebengalboy** [comment]
Hello @tjlabais 

The filter has been added and will be released with the next update.

Thanks
