### ISSUE TITLE
AC 1.5.5 Chart of Accounts intermittent editing error

### ISSUE THREAD

**Issue by tjlabais** [wp-erp/wp-erp#887]
**End User Entries for Chart of Accounts have an intermittent EDITING error. Sometimes it works. Most of the time, you can't.**
![characct04](https://user-images.githubusercontent.com/1410197/66371651-5c296280-e9d6-11e9-9213-f8e6b760b08e.JPG)

**Comment by itowhid06** [comment]
Hello, @tjlabais, you can not add a chart of account which matches with the name or code of an existing account, hence the error. And about the screenshot, there is already a system account with code `90`, hence you are getting the error.

**Comment by tjlabais** [comment]
I know this. Even if I change the values to any other values, I still get the same error. You can try it yourself to understand what I am saying.

**Comment by mhmdadel** [comment]
Yes It happens with me too
