### ISSUE TITLE
On purchase, the unit price disappears when going to view this purchase

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#891]
When I save a new purchase, the unit price disappears when going to view this purchase. Reference screenshot: https://prnt.sc/pi9dun

**Comment by nadim1992** [comment]
Can't reproduce.
![Screenshot 2019-10-14 at 2 59 25 PM](https://user-images.githubusercontent.com/8221832/66739785-482ca780-ee93-11e9-8af4-3836cb9e565c.png)
