### ISSUE TITLE
Changing currency position doesn't reflect on Accounting

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#901]
Changing currency position doesn't reflect on Accounting, including the accounting dashboard. 
Reference screenshot of settings: https://prnt.sc/pkkjjl
Reference screenshot of Accounting dashboard: https://prnt.sc/pkkkpt

**Comment by chanifalfath** [comment]
+1 for this

I just upgrade my version to 1.5.6, and same case happened.
Also i reckon that there is no currency on PDF Invoice too.

Thanks

**Comment by mhmdadel** [comment]
This problem appears to me too after the update to version 1.5.6
