### ISSUE TITLE
Products and Inventory Reports

### ISSUE THREAD

**Issue by mhmdadel** [wp-erp/wp-erp#903]
When creating the products at first time, I create them as a service and then changed them to inventory. Data not recognized right and in reports too.
(1) When changing from service to inventory, the data not correct as you see below:
https://prnt.sc/plpc1e
(2) When viewing "Inventory Purchase Report" no data appears;
https://prnt.sc/plpc1x
(3)Inventory Report, Item Summery.. It shows the product cost of goods sold and this amount is the amount of the sale to the customer. See Purchase, Sales Prices and Data from the report:
https://prnt.sc/plpc27
https://prnt.sc/plpc0n
https://prnt.sc/plpbvo

**Comment by mhmdadel** [comment]
Any updates about this problem

**Comment by thebengalboy** [comment]
Hello @mhmdadel 

You actually can not change the product type. If you need it, you can delete the product and create new. From the next version, you will be able to edit any other fields except the product type.

Thanks
