### ISSUE TITLE
Hyperlink text causing problem with the email template in CRM

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#904]
Suppose, you have created an email template in CRM and the template body has a text with a hyperlink.

So, when you send an email selecting this template, the user/contact gets the email but hyperlink doesn't work. I have attached a sample screenshot of how the email is being sent: https://d.pr/i/90R3Kk

Thanks

**Comment by nadim1992** [comment]
Fixed https://github.com/wp-erp/wp-erp/pull/908/commits/236d1fec4fcd4cc0cf840e0bf470ebc5602b7e0f
