### ISSUE TITLE
Send Announcement to email not working in HR Fronted

### ISSUE THREAD

**Issue by theusf** [wp-erp/wp-erp#919]
The send option selected dont get effetive on creation of the Announcement

![image](https://user-images.githubusercontent.com/29910542/68593017-3b3fab80-0473-11ea-81ec-1e86c05516c7.png)

![image](https://user-images.githubusercontent.com/29910542/68595289-ee120880-0477-11ea-8f51-93b02027dd32.png)

![image](https://user-images.githubusercontent.com/29910542/68595325-fd915180-0477-11ea-9bab-88427732d364.png)

Theres a way to me fix this by myself?

thx

**Comment by theusf** [comment]
Im tryng to send to all Employees but turns to Selected Employee option after i publish

**Comment by thebengalboy** [comment]
Hello @theusf 

As HR Frontend is a paid extension and the repository is being managed somewhere else than the core WPERP, I'd recommend you to contact our support center directly. The issue you are facing more likely happening based on your site. You can contact us here-> https://wperp.com/contact/

Thanks
