### ISSUE TITLE
Vendors Statement Balance Error

### ISSUE THREAD

**Issue by mhmdadel** [wp-erp/wp-erp#923]
When viewing a vendor statement the balances are not correct:
https://imgur.com/sSQuBCx

**Comment by thebengalboy** [comment]
Hello @mhmdadel 

Can you please explain what's wrong and the whole process of how we can reproduce the issue? We have tried but seem okay so far.

![Screenshot 2019-11-28 at 4 34 29 PM](https://user-images.githubusercontent.com/5962216/69800753-103db180-1200-11ea-8118-56be6d430452.png)

**Comment by mhmdadel** [comment]
I reinstall a fresh copy and I will feedback again

**Comment by mhmdadel** [comment]
The problem repeated again with new installation of WordPress
I will send you through support the login credential to check the problem

**Comment by itowhid06** [comment]
Fixed in https://github.com/wp-erp/wp-erp/commit/a68d625cc62bf8c820883b15ff1bdab6437b9df9
