### ISSUE TITLE
New Customer, Cannot add all customer data

### ISSUE THREAD

**Issue by mhmdadel** [wp-erp/wp-erp#924]
When I adding a new customer I am adding all its details and image. When save it freeze and the only thing to do is to refresh the page.
The only way is to add the mandatory data and then update the customer data to add the new data

**Comment by thebengalboy** [comment]
Hello @mhmdadel 

We have tried the same as you mentioned but it seems the issue does not persist here. Can you please give us any other hints or a screencast that can help us to identify the problem?

Thanks
