### ISSUE TITLE
VOID Purchase transaction which is already paid

### ISSUE THREAD

**Issue by mhmdadel** [wp-erp/wp-erp#927]
When I Void a purchase transaction which is already paid the status of the **payment transaction** not changed as you see; https://prnt.sc/q3xyil
I think it must be connected with the main transaction and also when viewing the main transaction and the payment should be any sign to say it Void,
Please see mock view suggested: 
1) Purchase Transaction: https://prnt.sc/q3xyve
2) Pay Purchase Transaction: https://prnt.sc/q3xywq
Thank you

**Comment by itowhid06** [comment]
Transactions with 'Paid' status should not show "Void" status. It has been fixed in https://github.com/wp-erp/wp-erp/commit/8e3b3d50ebead0911c25c9a2867eea5c458e1bb4. Sorry for the inconvenience.
