### ISSUE TITLE
Unit Price is "Zero" in Purchase viewing

### ISSUE THREAD

**Issue by mhmdadel** [wp-erp/wp-erp#928]
When viewing any Purchase transaction the unit price is ZERO
https://prnt.sc/q3yhck

**Comment by thebengalboy** [comment]
Hello @mhmdadel 

We were unable to reproduce the issue. Would you please check it back again with a new installation?

Thanks

**Comment by mhmdadel** [comment]
This screenshot from new installation of whole WordPress not only the plugin

**Comment by thebengalboy** [comment]
Okay, as this is working on our test and local sites, I assume there is something else happing on you.  Would you please contact our support for further assistant?

Thanks

**Comment by mhmdadel** [comment]
I will send you through support the login credential to check the problem
