### ISSUE TITLE
Void Purchase transaction makes a problem with Trial Balance, and Cash Account

### ISSUE THREAD

**Issue by mhmdadel** [wp-erp/wp-erp#930]
I reinstalled a fresh copy of ERP and was entering the purchases related to year 2018, then when I make the payment for this purchase transaction with amount 190.89 I made it by mistake in year 2019 not in 2018.
I void this purchase transaction with amount of 190.89. 
When I finished entering all transactions related to year 2018 and the trial balance is OK and then Closed Balances.
I find in 2019 Trial Balance, and Cash Account Balances not correct and the difference was with the above mentioned amount.
I need urgent fix to that problem, Please as soon as possible

**Comment by itowhid06** [comment]
Related https://github.com/wp-erp/wp-erp/issues/927

**Comment by mhmdadel** [comment]
Thank you for submitting updates and fix to the problem.
but I have updated to the latest version and the Trial Balance still not equal with amount mentioned above.
How to fix trial balance?

**Comment by thebengalboy** [comment]
Hello @mhmdadel 

Would you please knock us on the support further for this? It seems okay to us so far and we need to have a look at your site.

Thanks
