### ISSUE TITLE
Problem with updating the contact and company owner when they have user account

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#937]
**Description**: When the contact and company have user account on the site, the owner of that particular contact/company could not be updated.

**How to Reproduce**: Try to update a contact or company owner. Make sure this company or contact has a user account on your site.

**Expected behavior**: It should be updated anyway.
 
**Additional input (Screenshot/video)**:

Company - contact owner issue: https://www.dropbox.com/s/ra89bbc40f9k1vn/company%20owner%20issue.mov?dl=0

_Not able to update contact owner of a company if the company is also a WP user_

Contact - contact owner issue: https://www.dropbox.com/s/0cqmey6laiw6y5e/contact%20owner%20issue.mov?dl=0

_Not able to update contact owner of contact from the overview screen (it will not save the update). Only saves if you click into the contact FIRST, then update and save._

Thanks

**Comment by woouser** [comment]
Hi, how can we get someone assigned to this issue? It's a pretty core feature of the plugin that seems to not be working properly, and is holding back our progress in using the 3 **paid for** add-ons we've purchased from WP ERP.

Thank you!

**Comment by thebengalboy** [comment]
Fixed in #939
