### ISSUE TITLE
Apostrophe charachter encoding issue in company names & email campaign add-on

### ISSUE THREAD

**Issue by woouser** [wp-erp/wp-erp#940]
If a company name has an apostrophe in the title, when the company is saved the apostrophe is converted to a \' 
[https://www.dropbox.com/s/ilu1sp2mvxs97yr/Screen%20Shot%202019-12-30%20at%203.12.31%20PM.png?dl=0](url)

Also, a similar issue happens in the premium Email Campaign Add-on... when you send an email, apostrophe's are converted to â€™ 
[https://www.dropbox.com/s/u5062q1h5vb0fha/Screen%20Shot%202019-12-30%20at%203.09.23%20PM.png?dl=0](url)

**Comment by thebengalboy** [comment]
Hello @woouser 

The company name apostrophe issue has been fixed with the commit #941 

For the issue in the Email Campaign, please contact support center by opening a support ticket from your WPERP account as the paid extensions are not being managed with the core repository.

Thanks

**Comment by woouser** [comment]
Thanks!
