### ISSUE TITLE
Contact group subscription is not working 

### ISSUE THREAD

**Issue by FaraziF** [wp-erp/wp-erp#961]
**Steps:**
- Click WP ERP settings and click CRM tab
- Click subscription link and enable signup confirmation 
- Configure the subscription forms following the documents https://wperp.com/docs/crm/tutorials/subscription-forms/
- Submit the subscription form
 
**Expected Result:** Subscriber will be saved in the contact group
**Actual Result:** Form is not submitted, **Please provide a valid email address** message is showing.

**Comment by thebengalboy** [comment]
Issue Resolved already.
