### ISSUE TITLE
Missing strings in translation

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#966]
**Description**
In the CRM, `Bulk Actions`, `Apply`, `Filter` stings are not translateable in CRM

**Reference**
Screenshot removed due to the privacy and added below by @ jcarloscid

**Comment by jcarloscid** [comment]
Clarification on this issue. 

Fields in red do not appear on the translation file.

Fields in orange appear, they have a translation, but the translated string is not shown.

I will add some other places where this is happening.

**Comment by jcarloscid** [comment]
CRM - Companies

![image](https://user-images.githubusercontent.com/35863705/73524222-f8a3c480-440c-11ea-87d1-e6c57b378942.png)

**Comment by jcarloscid** [comment]
CRM - Activities

![image](https://user-images.githubusercontent.com/35863705/73525107-c4310800-440e-11ea-8f0a-215c9efd5d53.png)

**Comment by jcarloscid** [comment]
CRM - Contacts

![73514985-e3836180-441d-11ea-81db-8c6492f0817f](https://user-images.githubusercontent.com/35863705/73525768-1fafc580-4410-11ea-9b78-37f225d6be43.png)

**Comment by jcarloscid** [comment]
CRM - Schedules - Meeting details

![image](https://user-images.githubusercontent.com/35863705/73526287-30ad0680-4411-11ea-8ff5-1b54c6d44542.png)

**Comment by jcarloscid** [comment]
CRM - Contacts - New Email and the same on CRM - Company - New Email

![image](https://user-images.githubusercontent.com/35863705/73526572-d19bc180-4411-11ea-80ea-7df451d1241e.png)

**Comment by jcarloscid** [comment]
CRM - Contacts and also CRM - Companies / Filtering contact or company activity

![image](https://user-images.githubusercontent.com/35863705/73532527-27299b80-441d-11ea-94f6-f4aa75245b11.png)

**Comment by jcarloscid** [comment]
CRM - Contacts and also CRM - Companies / New task

![image](https://user-images.githubusercontent.com/35863705/73532726-93a49a80-441d-11ea-9ff4-2c2453826105.png)

**Comment by jcarloscid** [comment]
CRM - Contacts and also CRM - Edit Contact/Company details

![image](https://user-images.githubusercontent.com/35863705/73532972-1168a600-441e-11ea-9906-68a0e7cc876a.png)

**Comment by jcarloscid** [comment]
CRM - Contacts and also CRM - Companies - Contact/Company basic info - Life stage field

![image](https://user-images.githubusercontent.com/35863705/73533182-81772c00-441e-11ea-9fb0-c58634419365.png)

**Comment by jcarloscid** [comment]
CRM - Contacts and also CRM - Companies - Search Segment

![image](https://user-images.githubusercontent.com/35863705/73533745-ce0f3700-441f-11ea-931c-7c294a8e3220.png)

![image](https://user-images.githubusercontent.com/35863705/73534100-9d7bcd00-4420-11ea-9c4e-6914c93e521a.png)

**Comment by jcarloscid** [comment]
Filters - Two different cases appearing in several places:
- CRM - Contacts listing
- CRM - Companies listing
- CRM - Activities listing 

![image](https://user-images.githubusercontent.com/35863705/73534415-5e9a4700-4421-11ea-8604-0b1edcf158cc.png)

![image](https://user-images.githubusercontent.com/35863705/73534518-9d300180-4421-11ea-8fa3-026e32abcc8d.png)

**Comment by jcarloscid** [comment]
There are a few additional cases on the settings screens, but as long as this is not a common place for CRM agents, there's not a big issue having some elements in English.

**Comment by jcarloscid** [comment]
Clarification for screen shots 1st and 3rd: There is an additional item to translate:  the word "items" on the pagination controls.

**Comment by nadim1992** [comment]
This https://github.com/wp-erp/wp-erp/commit/cb9ed852de395d327de2171348d1d4f81767f49f fixes most of the above translation issues

**Comment by jcarloscid** [comment]
@nadim1992, after installing the changes, some strings can be translated, but not "most".

Some others are half way of translation, as "Show Advanced Fields".

The fields marked in orange color, still do not appear with the translation set on the PO/MO files.

**Comment by thebengalboy** [comment]
Hello @jcarloscid 

We have covered most of the strings. Please check them back again. If you find more strings that are not translatable, please report again.

We appreciate your cooperation :)

Thanks
