### ISSUE TITLE
Accounting > Add New Tax Rate is not working

### ISSUE THREAD

**Issue by mmarj** [wp-erp/wp-erp#976]
**Description:**
The Tax Rate option in Accounting → Tax is not working after creating all the pre-required Tax Zones, Categories, Agencies.

**How to Reproduce:**
1. First, create the Tax Zones
2. Then Tax Categories
3. Then Tax Agencies
4. Now, navigate to Tax→Tax Rates. Click on the “Add Tax Rate” button
5. Select Tax Zones from the list, insert Component Name, Select Agency, Category & insert Tax Rate. Now click on **Save** button.
6. You will notice it's showing an [error message](http://prntscr.com/qzhvxd)

Additional input (video):
[Screencast as reference](https://drive.google.com/file/d/1kHygnA8Rk7S20QBnYz1q0giuP7AT6pWM/view?usp=sharing)

**Comment by thebengalboy** [comment]
This has been fixed already and pinned to ship with the next release.

Thanks
