### ISSUE TITLE
Couldn't show the correct amount of money larger than 100 mil 

### ISSUE THREAD

**Issue by nguyentuanwinston** [wp-erp/wp-erp#988]
I used our currency (Vietnamese dong) to create the invoice in Accounting module . With the invoice with the amount is larger than 100 mill they show 99,999,999.00 instead of the correct amount larger than that number. 
![amount](https://user-images.githubusercontent.com/61407938/75138811-b9237c00-571d-11ea-8da1-0b9755f9307a.png)

**Comment by nguyentuanwinston** [comment]
![issue](https://user-images.githubusercontent.com/61407938/75139237-b37a6600-571e-11ea-9105-a5221c6323f7.png)
another pix

**Comment by namdk89** [comment]
Vấn đề này do khai báo tạo bảng độ dài chỉ có 10 thôi. Trong thời gian chờ bên này sửa Tuấn có thể tìm all source code dòng number(10) và sửa nó thành 15 là được. Nếu đã cài rồi và không muốn cài lại thì vào DB sửa trực tiếp là được.

**Comment by thebengalboy** [comment]
Hello @nguyentuanwinston and @namdk89 

Actually, the system allows 10 digits(0-9) only at this moment. We are also concerned about the Vietnamese Dong and the currencies that crosses the 10 digits.

It may take some time to get a decision/solution on this. So, I'm keeping this issue **open** for now.

Thanks

**Comment by nurul-umbhiya** [comment]
Updated field value to decimal(20,2), you can safely store upto 18 digits now
