### ISSUE TITLE
Contact is not removing from the database table after deleting it from the CRM-contacts section

### ISSUE THREAD

**Issue by mmarj** [wp-erp/wp-erp#991]
**Description:**
Contact is not removing from the database table after deleting it from the CRM-contacts section.  The same thing is happening for the CRM-Company, it's also not removing the company from the DB table.

**How to reproduce:**
- Create a contact or company from your CRM - Contact or company section. 
- Then delete the contact/company from the list.
- Once deleted then re-create another contact/company with the same email address. You will notice it will show the user already exists.

**Reference screenshot:**
Please[ check out this video](https://drive.google.com/file/d/1XWsF9PzxAhNN0KdiAdr6EWQSqL-urmL0/view?usp=sharing) for a better understanding.

Thanks

**Comment by nurul-umbhiya** [comment]
After deleting a contact, it goes to trash. You'll have to remove the deleted contact from trash first.

**Comment by mmarj** [comment]
Thanks for pointing me over the **Trash** option. I over-looked that on my previous checking. 

However, I just checked again with the **Trash** and found it's still not removed contacts/company from the DB after deleting from the **Trash**. As a result, if I going to create another contact with the same name it's not activating the **Add New** button.

Please [check out this video](https://drive.google.com/file/d/1hm0w25DuFxmbhwXoYPaV5DgaG4byIbl6/view?usp=sharing). Am I still missing anything?

I hope this will be helpful to you.
