### ISSUE TITLE
Accounting dashboard continually loads

### ISSUE THREAD

**Issue by SerialIterator** [wp-erp/wp-erp#995]
I installed wperp on a local server for development. I have a new install of Wordpress 5.3.2 and deactivated all other plugins. I can go to all the other dashboards and pages of wperp but the accounting dashboard just shows a spinning loading symbol. I have tried using safari and google chrome but same issue. I have also tried deactivating and reactivating wperp although it won't let me uninstall and reinstall without ftp access granted

**Comment by thebengalboy** [comment]
Hello @SerialIterator 

Please change the site permalink to `post name` from the settings. Problem should be solved :)

Thanks

**Comment by SerialIterator** [comment]
thank you @thebengalboy! That was a quick fix but why does only that page need post name Permalinks?

**Comment by thebengalboy** [comment]
Some of the libraries work better in the post-name permalink. So, no choice for now.

Happy to hear it helped :)
